#pragma once

//Currently 1 free Ability (ABILITY_UNUSED)

#define ABILITY_NONE 0
#define ABILITY_STENCH 0x1
#define ABILITY_DRIZZLE 0x2
#define ABILITY_SPEEDBOOST 0x3
#define ABILITY_BATTLEARMOR 0x4
#define ABILITY_STURDY 0x5
#define ABILITY_DAMP 0x6
#define ABILITY_LIMBER 0x7
#define ABILITY_SANDVEIL 0x8
#define ABILITY_STATIC 0x9
#define ABILITY_VOLTABSORB 0xA
#define ABILITY_WATERABSORB 0xB
#define ABILITY_OBLIVIOUS 0xC
#define ABILITY_CLOUDNINE 0xD //Also Air Lock
#define ABILITY_COMPOUNDEYES 0xE
#define ABILITY_INSOMNIA 0xF //Also Vital Spirit
#define ABILITY_COLORCHANGE 0x10
#define ABILITY_IMMUNITY 0x11
#define ABILITY_FLASHFIRE 0x12
#define ABILITY_SHIELDDUST 0x13
#define ABILITY_OWNTEMPO 0x14
#define ABILITY_SUCTIONCUPS 0x15
#define ABILITY_INTIMIDATE 0x16
#define ABILITY_SHADOWTAG 0x17
#define ABILITY_ROUGHSKIN 0x18 //Also Iron Barbs
#define ABILITY_WONDERGUARD 0x19
#define ABILITY_LEVITATE 0x1A
#define ABILITY_EFFECTSPORE 0x1B
#define ABILITY_SYNCHRONIZE 0x1C
#define ABILITY_CLEARBODY 0x1D //Also White Smoke
#define ABILITY_NATURALCURE 0x1E
#define ABILITY_LIGHTNINGROD 0x1F
#define ABILITY_SERENEGRACE 0x20
#define ABILITY_SWIFTSWIM 0x21
#define ABILITY_CHLOROPHYLL 0x22
#define ABILITY_ILLUMINATE 0x23
#define ABILITY_TRACE 0x24
#define ABILITY_HUGEPOWER 0x25 //Also Pure Power
#define ABILITY_POISONPOINT 0x26
#define ABILITY_INNERFOCUS 0x27
#define ABILITY_MAGMAARMOR 0x28
#define ABILITY_WATERVEIL 0x29
#define ABILITY_MAGNETPULL 0x2A
#define ABILITY_SOUNDPROOF 0x2B
#define ABILITY_RAINDISH 0x2C
#define ABILITY_SANDSTREAM 0x2D
#define ABILITY_PRESSURE 0x2E
#define ABILITY_THICKFAT 0x2F
#define ABILITY_EARLYBIRD 0x30
#define ABILITY_FLAMEBODY 0x31
#define ABILITY_RUNAWAY 0x32
#define ABILITY_KEENEYE 0x33
#define ABILITY_HYPERCUTTER 0x34
#define ABILITY_PICKUP 0x35
#define ABILITY_TRUANT 0x36
#define ABILITY_HUSTLE 0x37
#define ABILITY_CUTECHARM 0x38
#define ABILITY_PLUS 0x39
#define ABILITY_MINUS 0x3A
#define ABILITY_FORECAST 0x3B
#define ABILITY_STICKYHOLD 0x3C
#define ABILITY_SHEDSKIN 0x3D
#define ABILITY_GUTS 0x3E
#define ABILITY_MARVELSCALE 0x3F
#define ABILITY_LIQUIDOOZE 0x40
#define ABILITY_OVERGROW 0x41
#define ABILITY_BLAZE 0x42
#define ABILITY_TORRENT 0x43
#define ABILITY_SWARM 0x44
#define ABILITY_ROCKHEAD 0x45
#define ABILITY_DROUGHT 0x46
#define ABILITY_ARENATRAP 0x47
#define ABILITY_TRANSISTOR 0x48 //Was ABILITY_VITALSPIRIT
#define ABILITY_DRAGONSMAW 0x49 //Was ABILITY_WHITESMOKE
#define ABILITY_NEUTRALIZINGGAS 0x4A //Was ABILITY_PUREPOWER
#define ABILITY_SHELLARMOR 0x4B
#define ABILITY_HUNGERSWITCH 0x4C
#define ABILITY_UNUSED 0x4D //Was ABILITY_AIRLOCK - DON'T COMMENT THIS OUT!!!
#define ABILITY_SWEETVEIL 0x4E
#define ABILITY_SKILLLINK 0x4F
#define ABILITY_MOTORDRIVE 0x50
#define ABILITY_MULTISCALE 0x51
#define ABILITY_TECHNICIAN 0x52
#define ABILITY_SCRAPPY 0x53
#define ABILITY_SUPERLUCK 0x54
#define ABILITY_SNIPER 0x55
#define ABILITY_REGENERATOR 0x56
#define ABILITY_PRANKSTER 0x57
#define ABILITY_ADAPTABILITY 0x58
#define ABILITY_BIGPECKS 0x59
#define ABILITY_MAGICBOUNCE 0x5A
#define ABILITY_RECKLESS 0x5B
#define ABILITY_SHEERFORCE 0x5C
#define ABILITY_IRONFIST 0x5D
#define ABILITY_RIVALRY 0x5E
#define ABILITY_SANDFORCE 0x5F
#define ABILITY_SOLARPOWER 0x60
#define ABILITY_HEATPROOF 0x61
#define ABILITY_DRYSKIN 0x62
#define ABILITY_TINTEDLENS 0x63
#define ABILITY_UNSEENFIST 0x64 //Was ABILITY_SOLIDROCK
#define ABILITY_FILTER 0x65 //Also Solid Rock
#define ABILITY_INFILTRATOR 0x66
#define ABILITY_DOWNLOAD 0x67
#define ABILITY_POISONHEAL 0x68
#define ABILITY_ICEBODY 0x69
#define ABILITY_MOODY 0x6A
#define ABILITY_HYDRATION 0x6B
#define ABILITY_HEALER 0x6C
#define ABILITY_SNOWCLOAK 0x6D
#define ABILITY_TANGLEDFEET 0x6E
#define ABILITY_SNOWWARNING 0x6F
#define ABILITY_QUICKFEET 0x70
#define ABILITY_SAPSIPPER 0x71
#define ABILITY_OVERCOAT 0x72
#define ABILITY_MAGICGUARD 0x73
#define ABILITY_BULLETPROOF 0x74
#define ABILITY_GALEWINGS 0x75
#define ABILITY_MOXIE 0x76 //Also Grim Neigh
#define ABILITY_AFTERMATH 0x77
#define ABILITY_CURSEDBODY 0x78
#define ABILITY_GOOEY 0x79 //Also Tangling Hair
#define ABILITY_MUMMY 0x7A
#define ABILITY_GRIMNEIGH 0x7B //Was ABILITY_IRONBARBS
#define ABILITY_SANDRUSH 0x7C
#define ABILITY_ANALYTIC 0x7D
#define ABILITY_NOGUARD 0x7E
#define ABILITY_MEGALAUNCHER 0x7F
#define ABILITY_TOUGHCLAWS 0x80
#define ABILITY_STRONGJAW 0x81
#define ABILITY_VICTORYSTAR 0x82
#define ABILITY_STORMDRAIN 0x83
#define ABILITY_DARKAURA 0x84
#define ABILITY_FAIRYAURA 0x85
#define ABILITY_AURABREAK 0x86
#define ABILITY_REFRIGERATE 0x87
#define ABILITY_PIXILATE 0x88
#define ABILITY_AERILATE 0x89
#define ABILITY_NORMALIZE 0x8A
#define ABILITY_UNBURDEN 0x8B
#define ABILITY_SIMPLE 0x8C
#define ABILITY_UNAWARE 0x8D
#define ABILITY_DEFIANT 0x8E
#define ABILITY_COMPETITIVE 0x8F
#define ABILITY_DEFEATIST 0x90
#define ABILITY_SLOWSTART 0x91
#define ABILITY_TOXICBOOST 0x92
#define ABILITY_FLAREBOOST 0x93
#define ABILITY_FURCOAT 0x94
#define ABILITY_WONDERSKIN 0x95
#define ABILITY_PROTEAN 0x96 //Also Libero
#define ABILITY_PARENTALBOND 0x97
#define ABILITY_MOLDBREAKER 0x98 //Also Turboblaze, Teravolt
#define ABILITY_ASONE_GRIM 0x99 //Was ABILITY_TURBOBLAZE
#define ABILITY_ASONE_CHILLING 0x9A //Was ABILITY_TERAVOLT
#define ABILITY_ZENMODE 0x9B
#define ABILITY_BATTLEBOND 0x9C
#define ABILITY_BEASTBOOST 0x9D
#define ABILITY_CORROSION 0x9E
#define ABILITY_DISGUISE 0x9F
#define ABILITY_EMERGENCYEXIT 0xA0 //Also Wimp Out
#define ABILITY_FLUFFY 0xA1
#define ABILITY_STEELYSPIRIT 0xA2
#define ABILITY_PERISHBODY 0xA3
#define ABILITY_WANDERINGSPIRIT 0xA4
#define ABILITY_POWERCONSTRUCT 0xA5
#define ABILITY_PRISMARMOR 0xA6
#define ABILITY_RKS_SYSTEM 0xA7
#define ABILITY_SCHOOLING 0xA8
#define ABILITY_SHADOWSHIELD 0xA9
#define ABILITY_SHIELDSDOWN 0xAA
#define ABILITY_SLUSHRUSH 0xAB
#define ABILITY_SOULHEART 0xAC
#define ABILITY_STAMINA 0xAD
#define ABILITY_STEELWORKER 0xAE
#define ABILITY_FULLMETALBODY 0xAF //Was ABILITY_TANGLINGHAIR
#define ABILITY_TRIAGE 0xB0
#define ABILITY_WATERBUBBLE 0xB1
#define ABILITY_WATERCOMPACTION 0xB2
#define ABILITY_STALL 0xB3
#define ABILITY_MULTITYPE 0xB4
#define ABILITY_ELECTRICSURGE 0xB5
#define ABILITY_GRASSYSURGE 0xB6
#define ABILITY_MISTYSURGE 0xB7
#define ABILITY_PSYCHICSURGE 0xB8
#define ABILITY_SURGESURFER 0xB9
#define ABILITY_GRASSPELT 0xBA
#define ABILITY_ANGERPOINT 0xBB
#define ABILITY_ANTICIPATION 0xBC
#define ABILITY_FOREWARN 0xBD
#define ABILITY_FRISK 0xBE
#define ABILITY_CONTRARY 0xBF
#define ABILITY_UNNERVE 0xC0
#define ABILITY_WEAKARMOR 0xC1
#define ABILITY_HEAVYMETAL 0xC2
#define ABILITY_LIGHTMETAL 0xC3
#define ABILITY_STEADFAST 0xC4
#define ABILITY_IMPOSTER 0xC5
#define ABILITY_JUSTIFIED 0xC6
#define ABILITY_RATTLED 0xC7
#define ABILITY_MERCILESS 0xC8
#define ABILITY_AROMAVEIL 0xC9
#define ABILITY_FLOWERVEIL 0xCA
#define ABILITY_LEAFGUARD 0xCB
#define ABILITY_KLUTZ 0xCC
#define ABILITY_FLOWERGIFT 0xCD
#define ABILITY_BADDREAMS 0xCE
#define ABILITY_PICKPOCKET 0xCF
#define ABILITY_PORTALPOWER 0xD0
#define ABILITY_POISONTOUCH 0xD1
#define ABILITY_MAGICIAN 0xD2
#define ABILITY_STANCECHANGE 0xD3
#define ABILITY_PRIMORDIALSEA 0xD4
#define ABILITY_DESOLATELAND 0xD5
#define ABILITY_DELTASTREAM 0xD6
#define ABILITY_GORILLATACTICS 0xD7
#define ABILITY_BERSERK 0xD8
#define ABILITY_LONGREACH 0xD9
#define ABILITY_LIQUIDVOICE 0xDA
#define ABILITY_QUICKDRAW 0xDB //Was ABILITY_QUEENLYMAJESTY
#define ABILITY_INNARDSOUT 0xDC
#define ABILITY_DAZZLING 0xDD //Also Queenly Majesty
#define ABILITY_GLUTTONY 0xDE
#define ABILITY_HONEYGATHER 0xDF
#define ABILITY_FRIENDGUARD 0xE0
#define ABILITY_HARVEST 0xE1
#define ABILITY_TELEPATHY 0xE2
#define ABILITY_ILLUSION 0xE3
#define ABILITY_CHEEKPOUCH 0xE4
#define ABILITY_SYMBIOSIS 0xE5
#define ABILITY_STAKEOUT 0xE6
#define ABILITY_COMATOSE 0xE7
#define ABILITY_DANCER 0xE8
#define ABILITY_BATTERY 0xE9
#define ABILITY_RECEIVER 0xEA //Also Power of Alchemy
#define ABILITY_CURIOUSMEDICINE 0xEB //Was ABILITY_POWEROFALCHEMY
#define ABILITY_NEUROFORCE 0xEC
#define ABILITY_GALVANIZE 0xED
#define ABILITY_INTREPIDSWORD 0xEE
#define ABILITY_DAUNTLESSSHIELD 0xEF
#define ABILITY_BALLFETCH 0xF0
#define ABILITY_COTTONDOWN 0xF1
#define ABILITY_MIRRORARMOR 0xF2
#define ABILITY_GULPMISSILE 0xF3
#define ABILITY_STALWART 0xF4 //Also Propellor Tail
#define ABILITY_STEAMENGINE 0xF5
#define ABILITY_PUNKROCK 0xF6
#define ABILITY_SANDSPIT 0xF7
#define ABILITY_ICESCALES 0xF8
#define ABILITY_RIPEN 0xF9
#define ABILITY_ICEFACE 0xFA
#define ABILITY_POWERSPOT 0xFB
#define ABILITY_MIMICRY 0xFC
#define ABILITY_SCREENCLEANER 0xFD
#define ABILITY_PASTELVEIL 0xFE

#define ABILITY_EVAPORATE ABILITY_STORMDRAIN //Leech off of Storm Drain
#define ABILITY_DRILLBEAK ABILITY_MERCILESS

#define ABILITIES_COUNT (ABILITY_PASTELVEIL + 1)
