#pragma once

#define EFFECT_HIT 0
#define EFFECT_SLEEP 1
#define EFFECT_POISON_HIT 2
#define EFFECT_ABSORB 3
#define EFFECT_BURN_HIT 4
#define EFFECT_FREEZE_HIT 5
#define EFFECT_PARALYZE_HIT 6
#define EFFECT_EXPLOSION 7
#define EFFECT_DREAM_EATER 8
#define EFFECT_MIRROR_MOVE 9 //+ Copycat
#define EFFECT_ATTACK_UP 10 //+ Hone Claws
#define EFFECT_DEFENSE_UP 11 //+ Flower Shield + Magnetic Flux + Aromatic Mist
#define EFFECT_SPEED_UP 12
#define EFFECT_SPECIAL_ATTACK_UP 13 //+ Growth + Work Up + Rototiller + Gear Up
#define EFFECT_SPECIAL_DEFENSE_UP 14
#define EFFECT_ACCURACY_UP 15
#define EFFECT_EVASION_UP 16 //+ Acupressure
#define EFFECT_ALWAYS_HIT 17
#define EFFECT_ATTACK_DOWN 18 //+ Play Nice + Noble Roar + Tearful Look + Venom Drench
#define EFFECT_DEFENSE_DOWN 19
#define EFFECT_SPEED_DOWN 20 //+ Tar Shot
#define EFFECT_SPECIAL_ATTACK_DOWN 21
#define EFFECT_SPECIAL_DEFENSE_DOWN 22
#define EFFECT_ACCURACY_DOWN 23
#define EFFECT_EVASION_DOWN 24
#define EFFECT_HAZE 25
#define EFFECT_BIDE 26
#define EFFECT_RAMPAGE 27
#define EFFECT_ROAR 28 //+ Dragon Tail + Circle Throw
#define EFFECT_MULTI_HIT 29
#define EFFECT_CONVERSION 30 //+ Reflect Type
#define EFFECT_FLINCH_HIT 31 //+ Thunder Fang + Fire Fang + Ice Fang
#define EFFECT_RESTORE_HP 32 //+ Purify + Life Dew + Jungle Healing + Lunar Blessing
#define EFFECT_TOXIC 33
#define EFFECT_PAY_DAY 34
#define EFFECT_LIGHT_SCREEN 35
#define EFFECT_TRI_ATTACK 36
#define EFFECT_REST 37
#define EFFECT_0HKO 38
#define EFFECT_RAZOR_WIND 39
#define EFFECT_SUPER_FANG 40
#define EFFECT_DRAGON_RAGE 41
#define EFFECT_TRAP 42
#define EFFECT_HIGH_CRITICAL 43
#define EFFECT_DOUBLE_HIT 44
#define EFFECT_RECOIL_IF_MISS 45
#define EFFECT_MIST 46
#define EFFECT_FOCUS_ENERGY 47
#define EFFECT_RECOIL 48
#define EFFECT_CONFUSE 49
#define EFFECT_ATTACK_UP_2 50
#define EFFECT_DEFENSE_UP_2 51 //+ Cotton Guard + Stuff Cheeks
#define EFFECT_SPEED_UP_2 52 //+ Autotomize
#define EFFECT_SPECIAL_ATTACK_UP_2 53 //+ Tail Glow
#define EFFECT_SPECIAL_DEFENSE_UP_2 54
#define EFFECT_ACCURACY_UP_2 55
#define EFFECT_EVASION_UP_2 56
#define EFFECT_TRANSFORM 57
#define EFFECT_ATTACK_DOWN_2 58
#define EFFECT_DEFENSE_DOWN_2 59
#define EFFECT_SPEED_DOWN_2 60
#define EFFECT_SPECIAL_ATTACK_DOWN_2 61 //+ Captivate
#define EFFECT_SPECIAL_DEFENSE_DOWN_2 62
#define EFFECT_ACCURACY_DOWN_2 63
#define EFFECT_EVASION_DOWN_2 64
#define EFFECT_REFLECT 65 //+ Aurora Veil
#define EFFECT_POISON 66
#define EFFECT_PARALYZE 67
#define EFFECT_ATTACK_DOWN_HIT 68
#define EFFECT_DEFENSE_DOWN_HIT 69 //+ Triple Arrows
#define EFFECT_SPEED_DOWN_HIT 70
#define EFFECT_SPECIAL_ATTACK_DOWN_HIT 71
#define EFFECT_SPECIAL_DEFENSE_DOWN_HIT 72
#define EFFECT_ACCURACY_DOWN_HIT 73
#define EFFECT_EVASION_DOWN_HIT 74
#define EFFECT_SKY_ATTACK 75
#define EFFECT_CONFUSE_HIT 76
#define EFFECT_SPECIAL_DEFENSE_DOWN_2_HIT 77
#define EFFECT_BLANK_78 78
#define EFFECT_SUBSTITUTE 79
#define EFFECT_RECHARGE 80
#define EFFECT_RAGE 81
#define EFFECT_MIMIC 82
#define EFFECT_METRONOME 83
#define EFFECT_LEECH_SEED 84
#define EFFECT_SPLASH 85
#define EFFECT_DISABLE 86
#define EFFECT_LEVEL_DAMAGE 87
#define EFFECT_PSYWAVE 88
#define EFFECT_COUNTER 89 //+ Metal Burst
#define EFFECT_ENCORE 90
#define EFFECT_PAIN_SPLIT 91
#define EFFECT_SNORE 92
#define EFFECT_CONVERSION_2 93
#define EFFECT_LOCK_ON 94 //+ Laser Focus
#define EFFECT_SKETCH 95
#define EFFECT_SPEED_UP_1_HIT 96 //Flame Charge
#define EFFECT_SLEEP_TALK 97
#define EFFECT_DESTINY_BOND 98
#define EFFECT_FLAIL 99
#define EFFECT_SPITE 100
#define EFFECT_FALSE_SWIPE 101
#define EFFECT_HEAL_BELL 102
#define EFFECT_QUICK_ATTACK 103
#define EFFECT_TRIPLE_KICK 104
#define EFFECT_THIEF 105
#define EFFECT_MEAN_LOOK 106 //+ Anchor Shot + Spirit Shackle + Thousand Waves + Jaw Lock + Octolock
#define EFFECT_NIGHTMARE 107
#define EFFECT_MINIMIZE 108
#define EFFECT_CURSE 109
#define EFFECT_SPECIAL_ATTACK_UP_HIT 110
#define EFFECT_PROTECT 111
#define EFFECT_SPIKES 112
#define EFFECT_FORESIGHT 113 //+ Miracle Eye
#define EFFECT_PERISH_SONG 114
#define EFFECT_SANDSTORM 115
#define EFFECT_BLANK_116 116
#define EFFECT_ROLLOUT 117
#define EFFECT_SWAGGER 118
#define EFFECT_FURY_CUTTER 119 //+ Round + Echoed Voice
#define EFFECT_ATTRACT 120
#define EFFECT_BLANK_121 121
#define EFFECT_PRESENT 122
#define EFFECT_BLANK_123 123
#define EFFECT_SAFEGUARD 124
#define EFFECT_BURN_UP 125
#define EFFECT_MAGNITUDE 126
#define EFFECT_BATON_PASS 127 //+ U-Turn + Volt-Switch + Parting Shot
#define EFFECT_PURSUIT 128
#define EFFECT_RAPID_SPIN 129 //+ Defog
#define EFFECT_SONICBOOM 130
#define EFFECT_BLANK_83 131
#define EFFECT_MORNING_SUN 132
#define EFFECT_BLANK_133 133
#define EFFECT_BLANK_134 134
#define EFFECT_DEFENSE_UP_2_HIT 135
#define EFFECT_RAIN_DANCE 136
#define EFFECT_SUNNY_DAY 137
#define EFFECT_DEFENSE_UP_HIT 138
#define EFFECT_ATTACK_UP_HIT 139 //+ Fell Stinger
#define EFFECT_ALL_STATS_UP_HIT 140
#define EFFECT_HIGHER_OFFENSES_DEFENSES_UP_HIT 141
#define EFFECT_BELLY_DRUM 142
#define EFFECT_PSYCH_UP 143 //+ Spectral Thief
#define EFFECT_MIRROR_COAT 144
#define EFFECT_SKULL_BASH 145
#define EFFECT_TWISTER 146
#define EFFECT_EARTHQUAKE 147
#define EFFECT_FUTURE_SIGHT 148
#define EFFECT_GUST 149
#define EFFECT_SPLINTER 150
#define EFFECT_SOLARBEAM 151
#define EFFECT_THUNDER 152 //+ Hurricane
#define EFFECT_TELEPORT 153
#define EFFECT_BEAT_UP 154
#define EFFECT_SEMI_INVULNERABLE 155 //+ Shadow Force + Phantom Force
#define EFFECT_DEFENSE_CURL 156
#define EFFECT_SPRINGTIDE_STORM 157
#define EFFECT_FAKE_OUT 158
#define EFFECT_UPROAR 159
#define EFFECT_STOCKPILE 160
#define EFFECT_SPIT_UP 161
#define EFFECT_SWALLOW 162
#define EFFECT_BLANK_A3 163
#define EFFECT_HAIL 164
#define EFFECT_TORMENT 165
#define EFFECT_FLATTER 166
#define EFFECT_WILL_O_WISP 167
#define EFFECT_MEMENTO 168 //+ Healing Wish + Lunar Dance + Final Gambit
#define EFFECT_BLANK_169 169
#define EFFECT_FOCUS_PUNCH 170 //+ Beak Blast + Shell Trap
#define EFFECT_SMELLINGSALT 171
#define EFFECT_FOLLOW_ME 172
#define EFFECT_NATURE_POWER 173
#define EFFECT_CHARGE 174
#define EFFECT_TAUNT 175
#define EFFECT_HELPING_HAND 176
#define EFFECT_TRICK 177 //+ Bestow
#define EFFECT_ROLE_PLAY 178
#define EFFECT_WISH 179
#define EFFECT_ASSIST 180
#define EFFECT_INGRAIN 181 //+ Aqua Ring
#define EFFECT_SUPERPOWER 182 //+ Close Combat + Dragon Ascent + Hammer Arm + Ice Hammer + Clanging Scales + V-Create + Hyperspace Fury
#define EFFECT_MAGIC_COAT 183
#define EFFECT_RECYCLE 184 //+ Belch
#define EFFECT_BLANK_185 185
#define EFFECT_BRICK_BREAK 186
#define EFFECT_YAWN 187
#define EFFECT_KNOCK_OFF 188
#define EFFECT_ENDEAVOR 189
#define EFFECT_BLANK_190 190
#define EFFECT_SKILL_SWAP 191 //+ Worry Seed + Gastro Acid + Entrainment + Simple Beam + Core Enforcer
#define EFFECT_IMPRISON 192
#define EFFECT_REFRESH 193 //+ Psycho Shift
#define EFFECT_GRUDGE 194
#define EFFECT_SNATCH 195
#define EFFECT_BLANK_196 196
#define EFFECT_SECRET_POWER 197
#define EFFECT_ATK_SPATK_UP 198
#define EFFECT_ATK_ACC_UP 199
#define EFFECT_DEF_SPD_UP 200
#define EFFECT_MUD_SPORT 201
#define EFFECT_VENOM_DRENCH 202
#define EFFECT_PLAY_NICE 203
#define EFFECT_OVERHEAT 204
#define EFFECT_TICKLE 205
#define EFFECT_COSMIC_POWER 206
#define EFFECT_EXTREME_EVOBOOST 207 //+ No Retreat + Clangorous Soul
#define EFFECT_BULK_UP 208 //+ Coil
#define EFFECT_BAD_POISON_HIT 209
#define EFFECT_WATER_SPORT 210
#define EFFECT_CALM_MIND 211 //+ Quiver Dance + Geomancy + Take Heart
#define EFFECT_DRAGON_DANCE 212 //+ Shift Gear + Shell Smash

#define EFFECT_STAT_SWAP_SPLIT 213
#define EFFECT_BLANK_214 214
#define EFFECT_BLANK_215 215
#define EFFECT_BLANK_216 216
#define EFFECT_BLANK_217 217
#define EFFECT_ME_FIRST 218
#define EFFECT_EAT_BERRY 219 //+ Incinerate
#define EFFECT_NATURAL_GIFT 220
#define EFFECT_SMACK_DOWN 221
#define EFFECT_REMOVE_TARGET_STAT_CHANGES 222
#define EFFECT_RELIC_SONG 223
#define EFFECT_BLANK_224 224
#define EFFECT_BLANK_225 225
#define EFFECT_SET_TERRAIN 226
#define EFFECT_PLEDGE 227
#define EFFECT_FIELD_EFFECTS 228 //+ Court Change
#define EFFECT_FLING 229
#define EFFECT_FEINT 230 //+ Hyperspace Hole
#define EFFECT_ATTACK_BLOCKERS 231
#define EFFECT_TYPE_CHANGES 232 //+ Magic Powder
#define EFFECT_HEAL_TARGET 233
#define EFFECT_TOPSY_TURVY_ELECTRIFY 234
#define EFFECT_FAIRY_LOCK_HAPPY_HOUR 235
#define EFFECT_INSTRUCT_AFTER_YOU_QUASH 236
#define EFFECT_SUCKER_PUNCH 237
#define EFFECT_IGNORE_REDIRECTION 238
#define EFFECT_TEAM_EFFECTS 239
#define EFFECT_CAMOUFLAGE 240
#define EFFECT_FLAMEBURST 241
#define EFFECT_LAST_RESORT 242
#define EFFECT_DAMAGE_SET_TERRAIN 243
#define EFFECT_TEATIME 244
#define EFFECT_POLTERGEIST 245
#define EFFECT_SKY_DROP 246
#define EFFECT_GLAIVE_RUSH 247
#define EFFECT_SALTCURE 248

#define EFFECT_MAX_MOVE 253
