#pragma once

//#define ITEM_EFFECT_NONE            0
#define ITEM_EFFECT_RESTORE_HP      1
#define ITEM_EFFECT_CURE_PAR        2
#define ITEM_EFFECT_CURE_SLP        3
#define ITEM_EFFECT_CURE_PSN        4
#define ITEM_EFFECT_CURE_BRN        5
#define ITEM_EFFECT_CURE_FRZ        6
#define ITEM_EFFECT_RESTORE_PP      7
#define ITEM_EFFECT_CURE_CONFUSION  8
#define ITEM_EFFECT_CURE_STATUS     9
#define ITEM_EFFECT_CONFUSE_SPICY  10
#define ITEM_EFFECT_CONFUSE_DRY    11
#define ITEM_EFFECT_CONFUSE_SWEET  12
#define ITEM_EFFECT_CONFUSE_BITTER 13
#define ITEM_EFFECT_CONFUSE_SOUR   14
#define ITEM_EFFECT_ATTACK_UP      15
#define ITEM_EFFECT_DEFENSE_UP     16
#define ITEM_EFFECT_SPEED_UP       17
#define ITEM_EFFECT_SP_ATTACK_UP   18
#define ITEM_EFFECT_SP_DEFENSE_UP  19
#define ITEM_EFFECT_CRITICAL_UP    20
#define ITEM_EFFECT_RANDOM_STAT_UP 21
#define ITEM_EFFECT_EVASION_UP     22
#define ITEM_EFFECT_RESTORE_STATS  23
#define ITEM_EFFECT_MACHO_BRACE    24
#define ITEM_EFFECT_EXP_SHARE      25
#define ITEM_EFFECT_QUICK_CLAW     26
#define ITEM_EFFECT_HAPPINESS_UP   27
#define ITEM_EFFECT_CURE_ATTRACT   28
#define ITEM_EFFECT_CHOICE_BAND    29
#define ITEM_EFFECT_FLINCH         30
#define ITEM_EFFECT_BUG_POWER      31
#define ITEM_EFFECT_DOUBLE_PRIZE   32
#define ITEM_EFFECT_REPEL          33
#define ITEM_EFFECT_SOUL_DEW       34
#define ITEM_EFFECT_DEEP_SEA_TOOTH 35
#define ITEM_EFFECT_DEEP_SEA_SCALE 36
#define ITEM_EFFECT_CAN_ALWAYS_RUN 37
#define ITEM_EFFECT_PREVENT_EVOLVE 38
#define ITEM_EFFECT_FOCUS_BAND     39
#define ITEM_EFFECT_LUCKY_EGG      40
#define ITEM_EFFECT_SCOPE_LENS     41
#define ITEM_EFFECT_STEEL_POWER    42
#define ITEM_EFFECT_LEFTOVERS      43
#define ITEM_EFFECT_DRAGON_SCALE   44
#define ITEM_EFFECT_LIGHT_BALL     45
#define ITEM_EFFECT_GROUND_POWER   46
#define ITEM_EFFECT_ROCK_POWER     47
#define ITEM_EFFECT_GRASS_POWER    48
#define ITEM_EFFECT_DARK_POWER     49
#define ITEM_EFFECT_FIGHTING_POWER 50
#define ITEM_EFFECT_ELECTRIC_POWER 51
#define ITEM_EFFECT_WATER_POWER    52
#define ITEM_EFFECT_FLYING_POWER   53
#define ITEM_EFFECT_POISON_POWER   54
#define ITEM_EFFECT_ICE_POWER      55
#define ITEM_EFFECT_GHOST_POWER    56
#define ITEM_EFFECT_PSYCHIC_POWER  57
#define ITEM_EFFECT_FIRE_POWER     58
#define ITEM_EFFECT_DRAGON_POWER   59
#define ITEM_EFFECT_NORMAL_POWER   60
#define ITEM_EFFECT_UP_GRADE       61
#define ITEM_EFFECT_SHELL_BELL     62
#define ITEM_EFFECT_LUCKY_PUNCH    63
#define ITEM_EFFECT_METAL_POWDER   64
#define ITEM_EFFECT_THICK_CLUB     65
#define ITEM_EFFECT_STICK          66

//NEW ITEM EFFECTS
#define ITEM_EFFECT_ROCKY_HELMET 68
#define ITEM_EFFECT_QUICK_POWDER 69
#define ITEM_EFFECT_ASSAULT_VEST 70
#define ITEM_EFFECT_EVIOLITE 71
#define ITEM_EFFECT_PLATE 72 //Quality = Move Type
#define ITEM_EFFECT_MEGA_STONE 73
#define ITEM_EFFECT_LIFE_ORB 74
#define ITEM_EFFECT_TOXIC_ORB 75
#define ITEM_EFFECT_FLAME_ORB 76
#define ITEM_EFFECT_BLACK_SLUDGE 77
#define ITEM_EFFECT_SMOOTH_ROCK 78
#define ITEM_EFFECT_DAMP_ROCK 79
#define ITEM_EFFECT_HEAT_ROCK 80
#define ITEM_EFFECT_ICY_ROCK 81
#define ITEM_EFFECT_LIGHT_CLAY 82
#define ITEM_EFFECT_WIDE_LENS 83 //Quality = % Acc Boost
#define ITEM_EFFECT_SAFETY_GOGGLES 84
#define ITEM_EFFECT_WEAKNESS_POLICY 85
#define ITEM_EFFECT_DRIVE 86 //Quality = Move Type
#define ITEM_EFFECT_MEMORY 87 //Quality = Move Type
#define ITEM_EFFECT_ADAMANT_ORB 88
#define ITEM_EFFECT_LUSTROUS_ORB 89
#define ITEM_EFFECT_GRISEOUS_ORB 90
#define ITEM_EFFECT_DESTINY_KNOT 91
#define ITEM_EFFECT_EXPERT_BELT 92
#define ITEM_EFFECT_PRIMAL_ORB 93 //Red Orb: Quality = 0, Blue Orb: Quality = 1
#define ITEM_EFFECT_GEM 94 //Quality = Move Type
#define ITEM_EFFECT_WEAKNESS_BERRY 95 //Quality = Move Type
#define ITEM_EFFECT_CUSTAP_BERRY 96
#define ITEM_EFFECT_LAGGING_TAIL 97
#define ITEM_EFFECT_IRON_BALL 98
#define ITEM_EFFECT_BINDING_BAND 99

#define ITEM_EFFECT_PROTECTIVE_PADS 101
#define ITEM_EFFECT_ABSORB_BULB 102
#define ITEM_EFFECT_AIR_BALLOON 103
#define ITEM_EFFECT_BIG_ROOT 104
#define ITEM_EFFECT_CELL_BATTERY 105
#define ITEM_EFFECT_EJECT_BUTTON 106
#define ITEM_EFFECT_FLOAT_STONE 107
#define ITEM_EFFECT_GRIP_CLAW 108
#define ITEM_EFFECT_LUMINOUS_MOSS 109

#define ITEM_EFFECT_METRONOME 111
#define ITEM_EFFECT_MUSCLE_BAND 112
#define ITEM_EFFECT_RED_CARD 113
#define ITEM_EFFECT_RING_TARGET 114
#define ITEM_EFFECT_SHED_SHELL 115
#define ITEM_EFFECT_SNOWBALL 116
#define ITEM_EFFECT_STICKY_BARB 117
#define ITEM_EFFECT_TERRAIN_EXTENDER 118
#define ITEM_EFFECT_WISE_GLASSES 119
#define ITEM_EFFECT_SEEDS 120 //Electric Seed: Quality = 1, Grassy Seed: Quality = 2, Misty Seed: Quality = 3, Psychic Seed: Quality = 4
#define ITEM_EFFECT_JABOCA_ROWAP_BERRY 121 //Quality = Move Split (0 = Physical, 1 = Special)
#define ITEM_EFFECT_KEE_BERRY 122
#define ITEM_EFFECT_MARANGA_BERRY 123
#define ITEM_EFFECT_ZOOM_LENS 124 //Quality = % Acc Boost
#define ITEM_EFFECT_ADRENALINE_ORB 125
#define ITEM_EFFECT_POWER_HERB 126
#define ITEM_EFFECT_MICLE_BERRY 127
#define ITEM_EFFECT_ENIGMA_BERRY 128
#define ITEM_EFFECT_TYPE_BOOSTERS 129 //Quality = % Damage Boost
#define ITEM_EFFECT_Z_CRYSTAL 130 //Quality = Move Type
#define ITEM_EFFECT_ABILITY_CAPSULE 131
#define ITEM_EFFECT_EJECT_PACK 132
#define ITEM_EFFECT_ROOM_SERVICE 133
#define ITEM_EFFECT_BLUNDER_POLICY 134
#define ITEM_EFFECT_HEAVY_DUTY_BOOTS 135
#define ITEM_EFFECT_UTILITY_UMBRELLA 136
#define ITEM_EFFECT_THROAT_SPRAY 137
#define ITEM_EFFECT_RUSTED_SWORD 138
#define ITEM_EFFECT_RUSTED_SHIELD 139
#define ITEM_EFFECT_LOADED_DICE 140
#define ITEM_EFFECT_BOOSTER_ENERGY 141
#define ITEM_EFFECT_CLEAR_AMULET 142
#define ITEM_EFFECT_MASKS 143
#define ITEM_EFFECT_PUNCHING_GLOVE 144
#define ITEM_EFFECT_COVERT_CLOAK 145

#define ITEM_EFFECT_COUNT (ITEM_EFFECT_COVERT_CLOAK + 1)

//Focus Sash: Item Effect = ITEM_EFFECT_FOCUS_BAND, Item Quality = 100, Item Mystery 2 = 1
//Power Items: Item Effect = ITEM_EFFECT_MACHO_BRACE Item Quality = See Below

enum ChoiceQualities
{
	QUALITY_CHOICE_BAND,	//0
	QUALITY_CHOICE_SPECS,	//1
	QUALITY_CHOICE_SCARF,	//2
};

enum OrbQualities
{
	QUALITY_RED_ORB,		//0
	QUALITY_BLUE_ORB,		//1
};

enum PowerItemQualities
{
	QUALITY_MACHO_BRACE,	//0
	QUALITY_POWER_WEIGHT,	//1 - HP
	QUALITY_POWER_BRACER,	//2	- Attack
	QUALITY_POWER_BELT,		//3 - Defense
	QUALITY_POWER_ANKLET,	//4 - Speed
	QUALITY_POWER_LENS,		//5 - Sp Attack
	QUALITY_POWER_BAND,		//6 - Sp Defense
};
