#pragma once

#define BGM_EYE_CREEPY 0x11B
#define BGM_EYE_GIRL 0x11C
#define BGM_EYE_BOY 0x11D

#define BGM_VICTORY_TRAINER_BATTLE 0x136
#define BGM_VICTORY_SPECIAL 0x138

#define BGM_BATTLE_RSE_GYM_LEADER 0x109
#define BGM_BATTLE_RSE_TRAINER 0x10A
#define BGM_BATTLE_GYM_LEADER 0x128
#define BGM_BATTLE_TRAINER 0x129
#define BGM_BATTLE_WILD 0x12A
#define BGM_BATTLE_CHAMPION 0x12B
#define BGM_BATTLE_DEOXYS 0x153
#define BGM_BATTLE_LEGENDARY_BIRDS 0x154
#define BGM_BATTLE_MEWTWO 0x155

#define BGM_VICTORY_WILD_POKE 0x137
#define BGM_VICTORY_GYM 0x138

#define BGM_RANDOM_BATTLE_MUSIC 0xFEFE

#define MUS_DUMMY 0
#define SE_STOP 0
#define SE_USE_ITEM 1
#define SE_PC_LOGON 2
#define SE_PC_OFF 3
#define SE_PC_ON 4
#define SE_SELECT 5
#define SE_WIN_OPEN 6
#define SE_WALL_HIT 7
#define SE_DOOR_OPEN 8
#define SE_EXIT_ROOM 9
#define SE_HOP 0xA
#define SE_BIKE_BELL 0xB
#define SE_NOT_VERY_EFFECTIVE 0xC
#define SE_HIT_DAMAGE 0xD
#define SE_SUPER_EFFECTIVE 0xE
#define SE_SWITCH_IN 0xF
#define SE_FAINT 0x10
#define SE_FLEE 0x11
#define SE_SLIDING_DOOR_OPEN 0x12

#define SE_BREAK_DOOR_OPEN 0x14
#define SE_EXCLAIM 0x15
#define SE_FALSE 0x16
#define SE_POKE_CENTRE_LOAD_SINGLE_BALL 0x17
#define SE_CASINO_STOP_SLOT_REEL 0x18
#define SE_CORRECT 0x19
#define SE_ERROR 0x1A
#define SE_EXP 0x1B
#define SE_HOP_ON_BIKE 0x1C
#define SE_LOCK 0x1D
#define SE_UNLOCK 0x1E
#define SE_LAVARIDGE_GYM_DIG 0x21

#define SE_ICE_BREAK 0x23
#define SE_ICE_CRACK 0x24
#define SE_FALL 0x25
#define SE_DOOR_SHUT 0x26
#define SE_WARP_AWAY 0x27
#define SE_WARP_IN 0x28
#define SE_SLIDE 0x29
#define SE_TURN_SWITCH_FLIP 0x2A

#define SE_BT_START 0x61

#define SE_POKENAV_ONE_BEEP 0x65
#define SE_POKENAV_TWO_BEEPS 0x66
#define SE_POKENAV_ON 0x67
#define SE_POKENAV_OFF 0x68
#define SE_POKENAV_SEARCHING 0x69

#define SE_MUD_SLAP 0xA1
#define SE_LEAVES 0xA2

#define SE_RG_W_DOOR 241        // Door
#define SE_RG_CARD1 242         // Trainer Card 1
#define SE_RG_CARD2 243         // Trainer Card 2
#define SE_RG_CARD3 244         // Trainer Card 3
#define SE_RG_BAG1 245          // Bag Scroll
#define SE_RG_BAG2 246          // Bag Pocket Change
#define SE_RG_GETTING 247
#define SE_RG_SHOP 248          // Cash Register
#define SE_RG_KITEKI 249        // S.S. Anne Horn
#define SE_RG_HELP_OP 250       // Help Menu Open
#define SE_RG_HELP_CL 251       // Help Menu Close
#define SE_RG_HELP_NG 252       // Help Menu Error
#define SE_RG_DEOMOV 253        // Deoxys Moves
#define SE_RG_EXCELLENT 254

#ifdef UNBOUND //For Unbound

#define BGM_EYE_NEO_PLASMA 0x146
#define BGM_EYE_HIKER 0x164
#define BGM_EYE_ACE 0x165
#define BGM_EYE_MYSTERIOUS 0x166
#define BGM_EYE_SAILOR 0x167
#define BGM_EYE_BLACK_BELT 0x19B
#define BGM_EYE_GALACTIC 0x1A8
#define BGM_EYE_AROMA_LADY_BEAUTY 0x1B5
#define BGM_EYE_GAMBLER 0x1B6
#define BGM_EYE_ARTIST 0x1B7
#define BGM_EYE_ELITE_4 0x1B8
#define BGM_EYE_CYNTHIA 0x1B9
#define BGM_EYE_TWINS 0x1F1
#define BGM_EYE_BIRD_KEEPER 0x1F2

#define BGM_BATTLE_FRONTIER_BRAIN 0x109
#define BGM_BATTLE_PLASMA_GRUNT 0x10A
#define BGM_BATTLE_RED 0x12B
#define BGM_BATTLE_GALACTIC_BOSS 0x15B
#define BGM_BATTLE_GALACTIC_GRUNT 0x15C
#define BGM_BATTLE_ELITE_4 0x15E
#define BGM_BATTLE_NEO_PLASMA_GRUNT 0x173
#define BGM_BATTLE_SINNOH_GYM_LEADER 0x1FF
#define BGM_BATTLE_KALOS_GYM_LEADER 0x187
#define BGM_BATTLE_RIVAL 0x191
#define BGM_BATTLE_SHADOW_BOSS 0x198
#define BGM_BATTLE_GALACTIC_ADMIN 0x19F
#define BGM_BATTLE_BORRIUS_WILD 0x1A4
#define BGM_BATTLE_BORRIUS_TRAINER 0x1A5
#define BGM_BATTLE_LOR_BOSS 0x1AE
#define BGM_BATTLE_TEAM_ROCKET_GRUNT 0x1EE
#define BGM_BATTLE_MAGMA_GRUNT 0x1EF
#define BGM_BATTLE_MAGMA_BOSS 0x1F0
#define BGM_BATTLE_CYNTHIA 0x1F4
#define BGM_BATTLE_FLARE_GRUNT 0x201
#define BGM_BATTLE_SKULL_GRUNT 0x1FA

#define BGM_BATTLE_RAIKOU 0x179
#define BGM_BATTLE_ENTEI 0x19D
#define BGM_BATTLE_SUICUNE 0x19E
#define BGM_BATTLE_HOOH 0x19C
#define BGM_BATTLE_LUGIA 0x178
#define BGM_BATTLE_REGI_TRIO 0x200
#define BGM_BATTLE_GROUDON_KYOGRE_RAYQUAZA 0x177
#define BGM_BATTLE_LAKE_TRIO 0x1A9
#define BGM_BATTLE_DIALGA_PALKIA 0x15D
#define BGM_BATTLE_GIRATINA 0x1AA
#define BGM_BATTLE_SINNOH_LEGENDARY 0x1AB
#define BGM_BATTLE_ARCEUS 0x1AC
#define BGM_BATTLE_UNOVA_LEGENDARY 0x1F6
#define BGM_BATTLE_RESHIRAM_ZEKROM 0x1F7
#define BGM_BATTLE_KYUREM 0x1F8
#define BGM_BATTLE_KALOS_LEGENDARY 0x188
#define BGM_BATTLE_TAPU 0x1FB
#define BGM_BATTLE_SOLGALEO_LUNALA 0x1FC
#define BGM_BATTLE_UB 0x1FD
#define BGM_BATTLE_NECROZMA 0x1FE

#define BGM_BATTLE_KANTO_TRAINER 0x1EB
#define BGM_BATTLE_JOHTO_TRAINER 0x1EC
#define BGM_BATTLE_HOENN_TRAINER 0x1ED
#define BGM_BATTLE_SINNOH_TRAINER 0x129
#define BGM_BATTLE_UNOVA_TRAINER 0x1F5
#define BGM_BATTLE_KALOS_TRAINER 0x189
#define BGM_BATTLE_ALOLA_TRAINER 0x1F9
#define BGM_BATTLE_GALAR_WILD 0x202

#define BGM_VICTORY_WILD_POKE 0x137
#define BGM_VICTORY_GALACTIC 0x16D
#define BGM_VICTORY_PLASMA 0x1B1
#define BGM_VICTORY_CHAMPION 0x1B2
#define BGM_VICTORY_ELITE_4 0x1B4

#endif
