#pragma once

#define BGM_EYE_CREEPY 0x11B
#define BGM_EYE_GIRL 0x11C
#define BGM_EYE_BOY 0x11D

#define BGM_VICTORY_TRAINER_BATTLE 0x136
#define BGM_VICTORY_SPECIAL 0x138

#define BGM_BATTLE_RSE_GYM_LEADER 0x109
#define BGM_BATTLE_RSE_TRAINER 0x10A
#define BGM_CYCLING 0x11A
#define BGM_BATTLE_GYM_LEADER 0x128
#define BGM_BATTLE_TRAINER 0x129
#define BGM_BATTLE_WILD 0x12A
#define BGM_BATTLE_CHAMPION 0x12B
#define BGM_SURFS_UP 0x131
#define BGM_BATTLE_DEOXYS 0x153
#define BGM_BATTLE_LEGENDARY_BIRDS 0x154
#define BGM_BATTLE_MEWTWO 0x155

#define BGM_VICTORY_WILD_POKE 0x137
#define BGM_VICTORY_GYM 0x138

#define BGM_RANDOM_BATTLE_MUSIC 0xFEFE

#define MUS_DUMMY 0
#define SE_STOP 0
#define SE_USE_ITEM 1
#define SE_PC_LOGON 2
#define SE_PC_OFF 3
#define SE_PC_ON 4
#define SE_SELECT 5
#define SE_WIN_OPEN 6
#define SE_WALL_HIT 7
#define SE_DOOR_OPEN 8
#define SE_EXIT_ROOM 9
#define SE_HOP 0xA
#define SE_BIKE_BELL 0xB
#define SE_NOT_VERY_EFFECTIVE 0xC
#define SE_EFFECTIVE 0xD
#define SE_SUPER_EFFECTIVE 0xE
#define SE_POKE_BALL_OPEN 0xF
#define SE_POKE_BALL_CLOSE 0x10
#define SE_FLEE 0x11
#define SE_SLIDING_DOOR_OPEN 0x12
#define SE_BREAK_DOOR_OPEN 0x14
#define SE_EXCLAIM 0x15
#define SE_FALSE 0x16
#define SE_POKE_BALL_SHAKE 0x17
#define SE_CASINO_STOP_SLOT_REEL 0x18
#define SE_CORRECT 0x19
#define SE_ERROR 0x1A
#define SE_EXP 0x1B
#define SE_HOP_ON_BIKE 0x1C
#define SE_LOCK 0x1D
#define SE_UNLOCK 0x1E
#define SE_LAVARIDGE_GYM_DIG 0x21
#define SE_ICE_BREAK 0x23
#define SE_ICE_CRACK 0x24
#define SE_FALL 0x25
#define SE_DOOR_SHUT 0x26
#define SE_WARP_AWAY 0x27
#define SE_WARP_IN 0x28
#define SE_SLIDE 0x29
#define SE_TURN_SWITCH_FLIP 0x2A
#define SE_POKE_BALL_BOUNCE_1 0x32
#define SE_POKE_BALL_BOUNCE_2 0x32
#define SE_POKE_BALL_BOUNCE_3 0x33
#define SE_POKE_BALL_BOUNCE_4 0x34
#define SE_POKE_BALL_TRADE 0x35
#define SE_THROW_POKE_BALL 0x36
#define SE_NOTE_C 0x37
#define SE_NOTE_D 0x38
#define SE_NOTE_E 0x39
#define SE_NOTE_F 0x3A
#define SE_NOTE_G 0x3B
#define SE_NOTE_A 0x3C
#define SE_NOTE_B 0x3D
#define SE_NOTE_C1 0x3E
#define SE_PUDDLE 0x3F
#define SE_BOARDWALK 0x40
#define SE_SLOTS_CREDITS 0x41
#define SE_DING_DONG 0x42
#define SE_RED_BALLOON 0x43
#define SE_BLUE_BALLOON 0x44
#define SE_YELLOW_BALLOON 0x45
#define SE_BREAKABLE_DOOR 0x46
#define SE_MUD_BALL 0x47
#define SE_BT_START 0x61
#define SE_POKENAV_ONE_BEEP 0x65
#define SE_POKENAV_TWO_BEEPS 0x66
#define SE_POKENAV_ON 0x67
#define SE_POKENAV_OFF 0x68
#define SE_POKENAV_SEARCHING 0x69
#define SE_FLUTE 0x6E
#define SE_CUT 0x79
#define SE_ROCK_SMASH 0x7C
#define SE_CHOMP 0x9A
#define SE_MUD_SLAP 0xA1
#define SE_LEAVES 0xA2
#define SE_GLASS_BREAK 0xBF
#define SE_EARTHQUAKE 0xE3

#define SE_RG_W_DOOR 241        // Door
#define SE_RG_CARD1 242         // Trainer Card 1
#define SE_RG_CARD2 243         // Trainer Card 2
#define SE_RG_CARD3 244         // Trainer Card 3
#define SE_RG_BAG1 245          // Bag Scroll
#define SE_RG_BAG2 246          // Bag Pocket Change
#define SE_RG_GETTING 247
#define SE_MONEY 248
#define SE_SHIP_HORN 249
#define SE_SAND_FOOTSTEP 250
#define SE_GRASS_FOOTSTEP 251
#define SE_RG_HELP_MENU_ERROR 252
#define SE_RG_DEOXYS_MOVE 253
#define SE_RG_EXCELLENT 254

#define SE_CAUGHT_POKEMON 0x13F
#define MUS_FANFA1 0x101
#define MUS_FANFA2 0x10D

#ifdef UNBOUND //For Unbound

#define SE_RELIC_SONG 0x1DF

#define BGM_EYE_NEO_PLASMA 0x146
#define BGM_EYE_HIKER 0x164
#define BGM_EYE_ACE 0x165
#define BGM_EYE_MYSTERIOUS 0x166
#define BGM_EYE_SAILOR 0x167
#define BGM_EYE_SEVEN_SAGES 0x192
#define BGM_EYE_BLACK_BELT 0x19B
#define BGM_EYE_GALACTIC 0x1A8
#define BGM_EYE_AROMA_LADY_BEAUTY 0x1B5
#define BGM_EYE_GAMBLER 0x1B6
#define BGM_EYE_ARTIST 0x1B7
#define BGM_EYE_ELITE_4 0x1B8
#define BGM_EYE_CYNTHIA 0x1B9
#define BGM_EYE_TWINS 0x1F1
#define BGM_EYE_BIRD_KEEPER 0x1F2
#define BGM_EYE_TERROR_GRANBULL 0x20D

#define BGM_BATTLE_BORRIUS_TRAINER 0x1A5
#define BGM_BATTLE_KANTO_TRAINER 0x1EB
#define BGM_BATTLE_JOHTO_TRAINER 0x1EC
#define BGM_BATTLE_HOENN_TRAINER 0x1ED
#define BGM_BATTLE_SINNOH_TRAINER 0x129
#define BGM_BATTLE_UNOVA_TRAINER 0x1F5
#define BGM_BATTLE_KALOS_TRAINER 0x189
#define BGM_BATTLE_ALOLA_TRAINER 0x1F9
#define BGM_BATTLE_RIVAL 0x191
#define BGM_BATTLE_GYM_LEADER_LAST_POKEMON 0x207
#define BGM_BATTLE_SINNOH_GYM_LEADER 0x1FF
#define BGM_BATTLE_SUCCESSOR 0x187
#define BGM_BATTLE_ELITE_4 0x15E
#define BGM_BATTLE_JAX 0x20B
#define BGM_BATTLE_FRONTIER_BRAIN 0x109
#define BGM_BATTLE_CYNTHIA 0x1F4
#define BGM_BATTLE_RED 0x12B
#define BGM_BATTLE_SHADOW_GRUNT 0x10A
#define BGM_BATTLE_SHADOW_ADMIN 0x173
#define BGM_BATTLE_SHADOW_BOSS 0x198
#define BGM_BATTLE_LOR_GRUNT 0x15C
#define BGM_BATTLE_LOR_ADMIN 0x19F
#define BGM_BATTLE_LOR_LEADER 0x1AE
#define BGM_BATTLE_BLACK_EMBOAR_GOON 0x20C
#define BGM_BATTLE_BLACK_EMBOAR_BOSS 0x0
#define BGM_BATTLE_TERROR_GRANBULL_GOON 0x1EE
#define BGM_BATTLE_TERROR_GRANBULL_BOSS 0x0
#define BGM_BATTLE_BLACK_FERROTHORN_GOON 0x1FA
#define BGM_BATTLE_BLACK_FERROTHORN_BOSS 0x1F0
#define BGM_BATTLE_SCIENCE_SOCIETY_GOON 0x201
#define BGM_BATTLE_SCIENCE_SOCIETY_BOSS 0x0
#define BGM_BATTLE_BLACK_HORIZON_GOON 0x1EF
#define BGM_BATTLE_BLACK_HORIZON_ADMIN 0x0
#define BGM_BATTLE_BLACK_HORIZON_BOSS 0x0
#define BGM_BATTLE_GALACTIC_BOSS 0x15B

#define BGM_BATTLE_BORRIUS_WILD 0x1A4
#define BGM_BATTLE_GALAR_WILD 0x202
#define BGM_BATTLE_RAIKOU 0x179
#define BGM_BATTLE_ENTEI 0x19D
#define BGM_BATTLE_SUICUNE 0x19E
#define BGM_BATTLE_HOOH 0x19C
#define BGM_BATTLE_LUGIA 0x178
#define BGM_BATTLE_REGI_TRIO 0x200
#define BGM_BATTLE_GROUDON_KYOGRE_RAYQUAZA 0x177
#define BGM_BATTLE_LAKE_TRIO 0x1A9
#define BGM_BATTLE_DIALGA_PALKIA 0x15D
#define BGM_BATTLE_GIRATINA 0x1AA
#define BGM_BATTLE_SINNOH_LEGENDARY 0x1AB
#define BGM_BATTLE_ARCEUS 0x1AC
#define BGM_BATTLE_UNOVA_LEGENDARY 0x1F6
#define BGM_BATTLE_RESHIRAM_ZEKROM 0x1F7
#define BGM_BATTLE_KYUREM 0x1F8
#define BGM_BATTLE_KALOS_LEGENDARY 0x188
#define BGM_BATTLE_TAPU 0x1FB
#define BGM_BATTLE_SOLGALEO_LUNALA 0x1FC
#define BGM_BATTLE_UB 0x1FD
#define BGM_BATTLE_NECROZMA 0x1FE
#define BGM_BATTLE_RAID_BOSS BGM_BATTLE_GALACTIC_BOSS

#define BGM_VICTORY_WILD_POKE 0x137
#define BGM_VICTORY_GALACTIC 0x16D
#define BGM_VICTORY_PLASMA 0x1B1
#define BGM_VICTORY_CHAMPION 0x1B2
#define BGM_VICTORY_ELITE_4 0x1B4

#define BGM_HOOPAS_THEME 0x183
#define BGM_SEARCH_FOR_THE_RED_GYARADOS 0x1E4
#define BGM_TWINLEAF_TOWN 0x16A
#define BGM_UNDELLA_TOWN_WINTER 0x1E3
#define BGM_ROCKET_HIDEOUT 0x112

#define BGM_FROZEN_HEIGHTS 0x12C
#define BGM_BELLIN_TOWN 0x150
#define BGM_DRESCO_TOWN 0x1A0
#define BGM_CRATER_TOWN 0x1DD
#define BGM_BLIZZARD_CITY 0x168
#define BGM_TEHL_TOWN 0x118
#define BGM_FALLSHORE_CITY 0x174
#define BGM_EPIDIMY_TOWN 0x175
#define BGM_TARMIGAN_TOWN 0x195
#define BGM_DEHARA_CITY 0x1A2
#define BGM_GURUN_TOWN 0x190
#define BGM_VIVILL_TOWN_DARK 0x1A3
#define BGM_VIVILL_TOWN_LIGHT 0x16A
#define BGM_ANTISIS_CITY 0x1A7
#define BGM_SEAPORT_CITY 0x203
#define BGM_POLDER_TOWN 0x205
#define BGM_MAGNOLIA_TOWN 0x1C0
#define BGM_REDWOOD_VILLAGE 0x1C3

#define BGM_SHADOW_BASE 0x112
#define BGM_LOGS_LAB 0x12D
#define BGM_ICICLE_CAVE 0x14B
#define BGM_FLOWER_PARADISE 0x18F
#define BGM_GRIM_WOODS 0x15F
#define BGM_CINDER_VOLCANO 0x169
#define BGM_SES_EXPRESSWAY 0x14D
#define BGM_VALLEY_CAVE 0x17F
#define BGM_FROST_MOUNTAIN 0x181
#define BGM_FROZEN_FOREST 0x1E2
#define BGM_CAVE_OF_BEING 0x1C6
#define BGM_LOST_TUNNEL 0x1EA
#define BGM_UNDERGROUND_PASS 0x121
#define BGM_THUNDERCAP_MT 0x182
#define BGM_TARMIGAN_MANSION 0x18C
#define BGM_NEWMOON_ISLAND 0x186
#define BGM_GAME_CORNER 0x111
#define BGM_RUINS_OF_VOID 0x196
#define BGM_RUINS_OF_VOID_POST 0x18B
#define BGM_TOMB_OF_BORRIUS 0x184
#define BGM_VIVILL_WAREHOUSE 0x1A6
#define BGM_DISTORTION_WORLD 0x16C
#define BGM_ANTISIS_SEWERS 0x18D
#define BGM_BATTLE_FRONTIER 0x204
#define BGM_BATTLE_TOWER 0x1D1
#define BGM_BATTLE_MINE 0x1D4
#define BGM_BATTLE_CIRCUS 0x1D2
#define BGM_CRYSTAL_PEAK 0x180
#define BGM_VICTORY_ROAD 0x17B
#define BGM_POKEMON_LEAGUE 0x1D0

#define BGM_POKEMON_CENTRE 0x12F
#define BGM_POKEMON_CENTRE_NIGHT 0x1E1
#define BGM_POKE_MART 0x16B
#define BGM_GYM 0x113
#define BGM_TRAINER_HOUSE 0x1C8
#define BGM_ROUTE_GATE 0x172

#define BGM_ROUTE_THEME_1 0x123
#define BGM_ROUTE_THEME_2 0x197
#define BGM_ROUTE_THEME_3 0x124
#define BGM_ROUTE_THEME_4 0x160
#define BGM_ROUTE_THEME_5 0x125
#define BGM_ROUTE_THEME_6_7 0x163
#define BGM_ROUTE_THEME_8 0x17E
#define BGM_ROUTE_THEME_9_10 0x162
#define BGM_ROUTE_THEME_11 0x17A
#define BGM_ROUTE_THEME_12 0x193
#define BGM_ROUTE_THEME_13_14_15 0x161
#define BGM_GREAT_DESERT 0x1DC
#define BGM_ROUTE_THEME_16_17 0x1AF
#define BGM_COOTES_BOG 0x0

#endif
