#pragma once

#include "../../src/config.h"

#define SPECIES_NONE 0x0
#define SPECIES_BULBASAUR 0x1
#define SPECIES_IVYSAUR 0x2
#define SPECIES_VENUSAUR 0x3
#define SPECIES_CHARMANDER 0x4
#define SPECIES_CHARMELEON 0x5
#define SPECIES_CHARIZARD 0x6
#define SPECIES_SQUIRTLE 0x7
#define SPECIES_WARTORTLE 0x8
#define SPECIES_BLASTOISE 0x9
#define SPECIES_CATERPIE 0xA
#define SPECIES_METAPOD 0xB
#define SPECIES_BUTTERFREE 0xC
#define SPECIES_WEEDLE 0xD
#define SPECIES_KAKUNA 0xE
#define SPECIES_BEEDRILL 0xF
#define SPECIES_PIDGEY 0x10
#define SPECIES_PIDGEOTTO 0x11
#define SPECIES_PIDGEOT 0x12
#define SPECIES_RATTATA 0x13
#define SPECIES_RATICATE 0x14
#define SPECIES_SPEAROW 0x15
#define SPECIES_FEAROW 0x16
#define SPECIES_EKANS 0x17
#define SPECIES_ARBOK 0x18
#define SPECIES_PIKACHU 0x19
#define SPECIES_RAICHU 0x1A
#define SPECIES_SANDSHREW 0x1B
#define SPECIES_SANDSLASH 0x1C
#define SPECIES_NIDORAN_F 0x1D
#define SPECIES_NIDORINA 0x1E
#define SPECIES_NIDOQUEEN 0x1F
#define SPECIES_NIDORAN_M 0x20
#define SPECIES_NIDORINO 0x21
#define SPECIES_NIDOKING 0x22
#define SPECIES_CLEFAIRY 0x23
#define SPECIES_CLEFABLE 0x24
#define SPECIES_VULPIX 0x25
#define SPECIES_NINETALES 0x26
#define SPECIES_JIGGLYPUFF 0x27
#define SPECIES_WIGGLYTUFF 0x28
#define SPECIES_ZUBAT 0x29
#define SPECIES_GOLBAT 0x2A
#define SPECIES_ODDISH 0x2B
#define SPECIES_GLOOM 0x2C
#define SPECIES_VILEPLUME 0x2D
#define SPECIES_PARAS 0x2E
#define SPECIES_PARASECT 0x2F
#define SPECIES_VENONAT 0x30
#define SPECIES_VENOMOTH 0x31
#define SPECIES_DIGLETT 0x32
#define SPECIES_DUGTRIO 0x33
#define SPECIES_MEOWTH 0x34
#define SPECIES_PERSIAN 0x35
#define SPECIES_PSYDUCK 0x36
#define SPECIES_GOLDUCK 0x37
#define SPECIES_MANKEY 0x38
#define SPECIES_PRIMEAPE 0x39
#define SPECIES_GROWLITHE 0x3A
#define SPECIES_ARCANINE 0x3B
#define SPECIES_POLIWAG 0x3C
#define SPECIES_POLIWHIRL 0x3D
#define SPECIES_POLIWRATH 0x3E
#define SPECIES_ABRA 0x3F
#define SPECIES_KADABRA 0x40
#define SPECIES_ALAKAZAM 0x41
#define SPECIES_MACHOP 0x42
#define SPECIES_MACHOKE 0x43
#define SPECIES_MACHAMP 0x44
#define SPECIES_BELLSPROUT 0x45
#define SPECIES_WEEPINBELL 0x46
#define SPECIES_VICTREEBEL 0x47
#define SPECIES_TENTACOOL 0x48
#define SPECIES_TENTACRUEL 0x49
#define SPECIES_GEODUDE 0x4A
#define SPECIES_GRAVELER 0x4B
#define SPECIES_GOLEM 0x4C
#define SPECIES_PONYTA 0x4D
#define SPECIES_RAPIDASH 0x4E
#define SPECIES_SLOWPOKE 0x4F
#define SPECIES_SLOWBRO 0x50
#define SPECIES_MAGNEMITE 0x51
#define SPECIES_MAGNETON 0x52
#define SPECIES_FARFETCHED 0x53
#define SPECIES_FARFETCHD 0x53
#define SPECIES_DODUO 0x54
#define SPECIES_DODRIO 0x55
#define SPECIES_SEEL 0x56
#define SPECIES_DEWGONG 0x57
#define SPECIES_GRIMER 0x58
#define SPECIES_MUK 0x59
#define SPECIES_SHELLDER 0x5A
#define SPECIES_CLOYSTER 0x5B
#define SPECIES_GASTLY 0x5C
#define SPECIES_HAUNTER 0x5D
#define SPECIES_GENGAR 0x5E
#define SPECIES_ONIX 0x5F
#define SPECIES_DROWZEE 0x60
#define SPECIES_HYPNO 0x61
#define SPECIES_KRABBY 0x62
#define SPECIES_KINGLER 0x63
#define SPECIES_VOLTORB 0x64
#define SPECIES_ELECTRODE 0x65
#define SPECIES_EXEGGCUTE 0x66
#define SPECIES_EXEGGUTOR 0x67
#define SPECIES_CUBONE 0x68
#define SPECIES_MAROWAK 0x69
#define SPECIES_HITMONLEE 0x6A
#define SPECIES_HITMONCHAN 0x6B
#define SPECIES_LICKITUNG 0x6C
#define SPECIES_KOFFING 0x6D
#define SPECIES_WEEZING 0x6E
#define SPECIES_RHYHORN 0x6F
#define SPECIES_RHYDON 0x70
#define SPECIES_CHANSEY 0x71
#define SPECIES_TANGELA 0x72
#define SPECIES_KANGASKHAN 0x73
#define SPECIES_HORSEA 0x74
#define SPECIES_SEADRA 0x75
#define SPECIES_GOLDEEN 0x76
#define SPECIES_SEAKING 0x77
#define SPECIES_STARYU 0x78
#define SPECIES_STARMIE 0x79
#define SPECIES_MR_MIME 0x7A
#define SPECIES_SCYTHER 0x7B
#define SPECIES_JYNX 0x7C
#define SPECIES_ELECTABUZZ 0x7D
#define SPECIES_MAGMAR 0x7E
#define SPECIES_PINSIR 0x7F
#define SPECIES_TAUROS 0x80
#define SPECIES_MAGIKARP 0x81
#define SPECIES_GYARADOS 0x82
#define SPECIES_LAPRAS 0x83
#define SPECIES_DITTO 0x84
#define SPECIES_EEVEE 0x85
#define SPECIES_VAPOREON 0x86
#define SPECIES_JOLTEON 0x87
#define SPECIES_FLAREON 0x88
#define SPECIES_PORYGON 0x89
#define SPECIES_OMANYTE 0x8A
#define SPECIES_OMASTAR 0x8B
#define SPECIES_KABUTO 0x8C
#define SPECIES_KABUTOPS 0x8D
#define SPECIES_AERODACTYL 0x8E
#define SPECIES_SNORLAX 0x8F
#define SPECIES_ARTICUNO 0x90
#define SPECIES_ZAPDOS 0x91
#define SPECIES_MOLTRES 0x92
#define SPECIES_DRATINI 0x93
#define SPECIES_DRAGONAIR 0x94
#define SPECIES_DRAGONITE 0x95
#define SPECIES_MEWTWO 0x96
#define SPECIES_MEW 0x97
#define SPECIES_CHIKORITA 0x98
#define SPECIES_BAYLEEF 0x99
#define SPECIES_MEGANIUM 0x9A
#define SPECIES_CYNDAQUIL 0x9B
#define SPECIES_QUILAVA 0x9C
#define SPECIES_TYPHLOSION 0x9D
#define SPECIES_TOTODILE 0x9E
#define SPECIES_CROCONAW 0x9F
#define SPECIES_FERALIGATR 0xA0
#define SPECIES_SENTRET 0xA1
#define SPECIES_FURRET 0xA2
#define SPECIES_HOOTHOOT 0xA3
#define SPECIES_NOCTOWL 0xA4
#define SPECIES_LEDYBA 0xA5
#define SPECIES_LEDIAN 0xA6
#define SPECIES_SPINARAK 0xA7
#define SPECIES_ARIADOS 0xA8
#define SPECIES_CROBAT 0xA9
#define SPECIES_CHINCHOU 0xAA
#define SPECIES_LANTURN 0xAB
#define SPECIES_PICHU 0xAC
#define SPECIES_CLEFFA 0xAD
#define SPECIES_IGGLYBUFF 0xAE
#define SPECIES_TOGEPI 0xAF
#define SPECIES_TOGETIC 0xB0
#define SPECIES_NATU 0xB1
#define SPECIES_XATU 0xB2
#define SPECIES_MAREEP 0xB3
#define SPECIES_FLAAFFY 0xB4
#define SPECIES_AMPHAROS 0xB5
#define SPECIES_BELLOSSOM 0xB6
#define SPECIES_MARILL 0xB7
#define SPECIES_AZUMARILL 0xB8
#define SPECIES_SUDOWOODO 0xB9
#define SPECIES_POLITOED 0xBA
#define SPECIES_HOPPIP 0xBB
#define SPECIES_SKIPLOOM 0xBC
#define SPECIES_JUMPLUFF 0xBD
#define SPECIES_AIPOM 0xBE
#define SPECIES_SUNKERN 0xBF
#define SPECIES_SUNFLORA 0xC0
#define SPECIES_YANMA 0xC1
#define SPECIES_WOOPER 0xC2
#define SPECIES_QUAGSIRE 0xC3
#define SPECIES_ESPEON 0xC4
#define SPECIES_UMBREON 0xC5
#define SPECIES_MURKROW 0xC6
#define SPECIES_SLOWKING 0xC7
#define SPECIES_MISDREAVUS 0xC8
#define SPECIES_UNOWN 0xC9
#define SPECIES_WOBBUFFET 0xCA
#define SPECIES_GIRAFARIG 0xCB
#define SPECIES_PINECO 0xCC
#define SPECIES_FORRETRESS 0xCD
#define SPECIES_DUNSPARCE 0xCE
#define SPECIES_GLIGAR 0xCF
#define SPECIES_STEELIX 0xD0
#define SPECIES_SNUBBULL 0xD1
#define SPECIES_GRANBULL 0xD2
#define SPECIES_QWILFISH 0xD3
#define SPECIES_SCIZOR 0xD4
#define SPECIES_SHUCKLE 0xD5
#define SPECIES_HERACROSS 0xD6
#define SPECIES_SNEASEL 0xD7
#define SPECIES_TEDDIURSA 0xD8
#define SPECIES_URSARING 0xD9
#define SPECIES_SLUGMA 0xDA
#define SPECIES_MAGCARGO 0xDB
#define SPECIES_SWINUB 0xDC
#define SPECIES_PILOSWINE 0xDD
#define SPECIES_CORSOLA 0xDE
#define SPECIES_REMORAID 0xDF
#define SPECIES_OCTILLERY 0xE0
#define SPECIES_DELIBIRD 0xE1
#define SPECIES_MANTINE 0xE2
#define SPECIES_SKARMORY 0xE3
#define SPECIES_HOUNDOUR 0xE4
#define SPECIES_HOUNDOOM 0xE5
#define SPECIES_KINGDRA 0xE6
#define SPECIES_PHANPY 0xE7
#define SPECIES_DONPHAN 0xE8
#define SPECIES_PORYGON2 0xE9
#define SPECIES_STANTLER 0xEA
#define SPECIES_SMEARGLE 0xEB
#define SPECIES_TYROGUE 0xEC
#define SPECIES_HITMONTOP 0xED
#define SPECIES_SMOOCHUM 0xEE
#define SPECIES_ELEKID 0xEF
#define SPECIES_MAGBY 0xF0
#define SPECIES_MILTANK 0xF1
#define SPECIES_BLISSEY 0xF2
#define SPECIES_RAIKOU 0xF3
#define SPECIES_ENTEI 0xF4
#define SPECIES_SUICUNE 0xF5
#define SPECIES_LARVITAR 0xF6
#define SPECIES_PUPITAR 0xF7
#define SPECIES_TYRANITAR 0xF8
#define SPECIES_LUGIA 0xF9
#define SPECIES_HO_OH 0xFA
#define SPECIES_CELEBI 0xFB

#define SPECIES_TREECKO 0x115
#define SPECIES_GROVYLE 0x116
#define SPECIES_SCEPTILE 0x117
#define SPECIES_TORCHIC 0x118
#define SPECIES_COMBUSKEN 0x119
#define SPECIES_BLAZIKEN 0x11A
#define SPECIES_MUDKIP 0x11B
#define SPECIES_MARSHTOMP 0x11C
#define SPECIES_SWAMPERT 0x11D
#define SPECIES_POOCHYENA 0x11E
#define SPECIES_MIGHTYENA 0x11F
#define SPECIES_ZIGZAGOON 0x120
#define SPECIES_LINOONE 0x121
#define SPECIES_WURMPLE 0x122
#define SPECIES_SILCOON 0x123
#define SPECIES_BEAUTIFLY 0x124
#define SPECIES_CASCOON 0x125
#define SPECIES_DUSTOX 0x126
#define SPECIES_LOTAD 0x127
#define SPECIES_LOMBRE 0x128
#define SPECIES_LUDICOLO 0x129
#define SPECIES_SEEDOT 0x12A
#define SPECIES_NUZLEAF 0x12B
#define SPECIES_SHIFTRY 0x12C
#define SPECIES_NINCADA 0x12D
#define SPECIES_NINJASK 0x12E
#define SPECIES_SHEDINJA 0x12F
#define SPECIES_TAILLOW 0x130
#define SPECIES_SWELLOW 0x131
#define SPECIES_SHROOMISH 0x132
#define SPECIES_BRELOOM 0x133
#define SPECIES_SPINDA 0x134
#define SPECIES_WINGULL 0x135
#define SPECIES_PELIPPER 0x136
#define SPECIES_SURSKIT 0x137
#define SPECIES_MASQUERAIN 0x138
#define SPECIES_WAILMER 0x139
#define SPECIES_WAILORD 0x13A
#define SPECIES_SKITTY 0x13B
#define SPECIES_DELCATTY 0x13C
#define SPECIES_KECLEON 0x13D
#define SPECIES_BALTOY 0x13E
#define SPECIES_CLAYDOL 0x13F
#define SPECIES_NOSEPASS 0x140
#define SPECIES_TORKOAL 0x141
#define SPECIES_SABLEYE 0x142
#define SPECIES_BARBOACH 0x143
#define SPECIES_WHISCASH 0x144
#define SPECIES_LUVDISC 0x145
#define SPECIES_CORPHISH 0x146
#define SPECIES_CRAWDAUNT 0x147
#define SPECIES_FEEBAS 0x148
#define SPECIES_MILOTIC 0x149
#define SPECIES_CARVANHA 0x14A
#define SPECIES_SHARPEDO 0x14B
#define SPECIES_TRAPINCH 0x14C
#define SPECIES_VIBRAVA 0x14D
#define SPECIES_FLYGON 0x14E
#define SPECIES_MAKUHITA 0x14F
#define SPECIES_HARIYAMA 0x150
#define SPECIES_ELECTRIKE 0x151
#define SPECIES_MANECTRIC 0x152
#define SPECIES_NUMEL 0x153
#define SPECIES_CAMERUPT 0x154
#define SPECIES_SPHEAL 0x155
#define SPECIES_SEALEO 0x156
#define SPECIES_WALREIN 0x157
#define SPECIES_CACNEA 0x158
#define SPECIES_CACTURNE 0x159
#define SPECIES_SNORUNT 0x15A
#define SPECIES_GLALIE 0x15B
#define SPECIES_LUNATONE 0x15C
#define SPECIES_SOLROCK 0x15D
#define SPECIES_AZURILL 0x15E
#define SPECIES_SPOINK 0x15F
#define SPECIES_GRUMPIG 0x160
#define SPECIES_PLUSLE 0x161
#define SPECIES_MINUN 0x162
#define SPECIES_MAWILE 0x163
#define SPECIES_MEDITITE 0x164
#define SPECIES_MEDICHAM 0x165
#define SPECIES_SWABLU 0x166
#define SPECIES_ALTARIA 0x167
#define SPECIES_WYNAUT 0x168
#define SPECIES_DUSKULL 0x169
#define SPECIES_DUSCLOPS 0x16A
#define SPECIES_ROSELIA 0x16B
#define SPECIES_SLAKOTH 0x16C
#define SPECIES_VIGOROTH 0x16D
#define SPECIES_SLAKING 0x16E
#define SPECIES_GULPIN 0x16F
#define SPECIES_SWALOT 0x170
#define SPECIES_TROPIUS 0x171
#define SPECIES_WHISMUR 0x172
#define SPECIES_LOUDRED 0x173
#define SPECIES_EXPLOUD 0x174
#define SPECIES_CLAMPERL 0x175
#define SPECIES_HUNTAIL 0x176
#define SPECIES_GOREBYSS 0x177
#define SPECIES_ABSOL 0x178
#define SPECIES_SHUPPET 0x179
#define SPECIES_BANETTE 0x17A
#define SPECIES_SEVIPER 0x17B
#define SPECIES_ZANGOOSE 0x17C
#define SPECIES_RELICANTH 0x17D
#define SPECIES_ARON 0x17E
#define SPECIES_LAIRON 0x17F
#define SPECIES_AGGRON 0x180
#define SPECIES_CASTFORM 0x181
#define SPECIES_VOLBEAT 0x182
#define SPECIES_ILLUMISE 0x183
#define SPECIES_LILEEP 0x184
#define SPECIES_CRADILY 0x185
#define SPECIES_ANORITH 0x186
#define SPECIES_ARMALDO 0x187
#define SPECIES_RALTS 0x188
#define SPECIES_KIRLIA 0x189
#define SPECIES_GARDEVOIR 0x18A
#define SPECIES_BAGON 0x18B
#define SPECIES_SHELGON 0x18C
#define SPECIES_SALAMENCE 0x18D
#define SPECIES_BELDUM 0x18E
#define SPECIES_METANG 0x18F
#define SPECIES_METAGROSS 0x190
#define SPECIES_REGIROCK 0x191
#define SPECIES_REGICE 0x192
#define SPECIES_REGISTEEL 0x193
#define SPECIES_KYOGRE 0x194
#define SPECIES_GROUDON 0x195
#define SPECIES_RAYQUAZA 0x196
#define SPECIES_LATIAS 0x197
#define SPECIES_LATIOS 0x198
#define SPECIES_JIRACHI 0x199
#define SPECIES_DEOXYS 0x19A
#define SPECIES_CHIMECHO 0x19B

#define SPECIES_EGG 0x19C
#define SPECIES_UNOWN_B 0x19D
#define SPECIES_UNOWN_C 0x19E
#define SPECIES_UNOWN_D 0x19F
#define SPECIES_UNOWN_E 0x1A0
#define SPECIES_UNOWN_F 0x1A1
#define SPECIES_UNOWN_G 0x1A2
#define SPECIES_UNOWN_H 0x1A3
#define SPECIES_UNOWN_I 0x1A4
#define SPECIES_UNOWN_J 0x1A5
#define SPECIES_UNOWN_K 0x1A6
#define SPECIES_UNOWN_L 0x1A7
#define SPECIES_UNOWN_M 0x1A8
#define SPECIES_UNOWN_N 0x1A9
#define SPECIES_UNOWN_O 0x1AA
#define SPECIES_UNOWN_P 0x1AB
#define SPECIES_UNOWN_Q 0x1AC
#define SPECIES_UNOWN_R 0x1AD
#define SPECIES_UNOWN_S 0x1AE
#define SPECIES_UNOWN_T 0x1AF
#define SPECIES_UNOWN_U 0x1B0
#define SPECIES_UNOWN_V 0x1B1
#define SPECIES_UNOWN_W 0x1B2
#define SPECIES_UNOWN_X 0x1B3
#define SPECIES_UNOWN_Y 0x1B4
#define SPECIES_UNOWN_Z 0x1B5
#define SPECIES_UNOWN_EXCLAMATION 0x1B6
#define SPECIES_UNOWN_QUESTION 0x1B7
#define SPECIES_TURTWIG 0x1B8
#define SPECIES_GROTLE 0x1B9
#define SPECIES_TORTERRA 0x1BA
#define SPECIES_CHIMCHAR 0x1BB
#define SPECIES_MONFERNO 0x1BC
#define SPECIES_INFERNAPE 0x1BD
#define SPECIES_PIPLUP 0x1BE
#define SPECIES_PRINPLUP 0x1BF
#define SPECIES_EMPOLEON 0x1C0
#define SPECIES_LEAFEON 0x1C1
#define SPECIES_GLACEON 0x1C2
#define SPECIES_SYLVEON 0x1C3
#define SPECIES_CROAGUNK 0x1C4
#define SPECIES_TOXICROAK 0x1C5
#define SPECIES_PHANTUMP 0x1C6
#define SPECIES_TREVENANT 0x1C7
#define SPECIES_PUMPKABOO 0x1C8
#define SPECIES_GOURGEIST 0x1C9
#define SPECIES_BUDEW 0x1CA
#define SPECIES_ROSERADE 0x1CB
#define SPECIES_PORYGON_Z 0x1CC
#define SPECIES_YANMEGA 0x1CD
#define SPECIES_GALLADE 0x1CE
#define SPECIES_TANGROWTH 0x1CF
#define SPECIES_TOGEKISS 0x1D0
#define SPECIES_ELECTIVIRE 0x1D1
#define SPECIES_MAGMORTAR 0x1D2
#define SPECIES_GLISCOR 0x1D3
#define SPECIES_WEAVILE 0x1D4
#define SPECIES_FROSLASS 0x1D5
#define SPECIES_DUSKNOIR 0x1D6
#define SPECIES_MISMAGIUS 0x1D7
#define SPECIES_HONCHKROW 0x1D8
#define SPECIES_MAGNEZONE 0x1D9
#define SPECIES_RHYPERIOR 0x1DA
#define SPECIES_MAMOSWINE 0x1DB
#define SPECIES_CHINGLING 0x1DC
#define SPECIES_BONSLY 0x1DD
#define SPECIES_MIME_JR 0x1DE
#define SPECIES_HAPPINY 0x1DF
#define SPECIES_MUNCHLAX 0x1E0
#define SPECIES_MANTYKE 0x1E1
#define SPECIES_AMBIPOM 0x1E2
#define SPECIES_LICKILICKY 0x1E3
#define SPECIES_PROBOPASS 0x1E4
#define SPECIES_SHINX 0x1E5
#define SPECIES_LUXIO 0x1E6
#define SPECIES_LUXRAY 0x1E7
#define SPECIES_YAMASK 0x1E8
#define SPECIES_COFAGRIGUS 0x1E9
#define SPECIES_SCRAGGY 0x1EA
#define SPECIES_SCRAFTY 0x1EB
#define SPECIES_RUNERIGUS 0x1EC
#define SPECIES_DRILBUR 0x1ED
#define SPECIES_EXCADRILL 0x1EE
#define SPECIES_TIMBURR 0x1EF
#define SPECIES_GURDURR 0x1F0
#define SPECIES_CONKELDURR 0x1F1
#define SPECIES_LARVESTA 0x1F2
#define SPECIES_VOLCARONA 0x1F3
#define SPECIES_SOLOSIS 0x1F4
#define SPECIES_DUOSION 0x1F5
#define SPECIES_REUNICLUS 0x1F6
#define SPECIES_PAWNIARD 0x1F7
#define SPECIES_BISHARP 0x1F8
#define SPECIES_FRILLISH 0x1F9
#define SPECIES_JELLICENT 0x1FA
#define SPECIES_SPIRITOMB 0x1FB
#define SPECIES_SIGILYPH 0x1FC
#define SPECIES_CARBINK 0x1FD
#define SPECIES_KLEFKI 0x1FE
#define SPECIES_HONEDGE 0x1FF
#define SPECIES_DOUBLADE 0x200
#define SPECIES_AEGISLASH 0x201
#define SPECIES_FLABEBE 0x202
#define SPECIES_FLOETTE 0x203
#define SPECIES_FLORGES 0x204
#define SPECIES_ARCHEN 0x205
#define SPECIES_ARCHEOPS 0x206
#define SPECIES_TYRUNT 0x207
#define SPECIES_TYRANTRUM 0x208
#define SPECIES_SNOVER 0x209
#define SPECIES_ABOMASNOW 0x20A
#define SPECIES_MELTAN 0x20B
#define SPECIES_MELMETAL 0x20C
#define SPECIES_TRUBBISH 0x20D
#define SPECIES_GARBODOR 0x20E
#define SPECIES_KLINK 0x20F
#define SPECIES_KLANG 0x210
#define SPECIES_KLINKLANG 0x211
#define SPECIES_RIOLU 0x212
#define SPECIES_LUCARIO 0x213
#define SPECIES_BRONZOR 0x214
#define SPECIES_BRONZONG 0x215
#define SPECIES_GOLETT 0x216
#define SPECIES_GOLURK 0x217
#define SPECIES_GIBLE 0x218
#define SPECIES_GABITE 0x219
#define SPECIES_GARCHOMP 0x21A
#define SPECIES_DEINO 0x21B
#define SPECIES_ZWEILOUS 0x21C
#define SPECIES_HYDREIGON 0x21D
#define SPECIES_ROTOM 0x21E
#define SPECIES_ROCKRUFF 0x21F
#define SPECIES_LYCANROC 0x220
#define SPECIES_TORNADUS 0x221
#define SPECIES_THUNDURUS 0x222
#define SPECIES_LANDORUS 0x223
#define SPECIES_HEATRAN 0x224
#define SPECIES_REGIGIGAS 0x225
#define SPECIES_GENESECT 0x226
#define SPECIES_DAKRAI 0x227
#define SPECIES_SHAYMIN 0x228
#define SPECIES_DIANCIE 0x229
#define SPECIES_DIALGA 0x22A
#define SPECIES_PALKIA 0x22B
#define SPECIES_GIRATINA 0x22C
#define SPECIES_ARCEUS 0x22D
#define SPECIES_ZYGARDE 0x22E
#define SPECIES_NECROZMA 0x22F

//Forms
#define SPECIES_FRILLISH_F 0x230
#define SPECIES_JELLICENT_F 0x231
#define SPECIES_ROTOM_WASH 0x232
#define SPECIES_ROTOM_HEAT 0x233
#define SPECIES_ROTOM_MOW 0x234
#define SPECIES_ROTOM_FROST 0x235
#define SPECIES_ROTOM_FAN 0x236
#define SPECIES_ROTOM_TANK 0x237 // NEW FORM
#define SPECIES_ROTOM_DRONE 0x238 // NEW FORM
#define SPECIES_ROTOM_NEWFORM 0x239 // NEW FORM
#define SPECIES_DEOXYS_NORMAL 0x23A // PLACEHOLDER FOR NORMAL FORM DEOXYS
#define SPECIES_DEOXYS_ATTACK 0x23B
#define SPECIES_DEOXYS_DEFENSE 0x23C
#define SPECIES_DEOXYS_SPEED 0x23D
#define SPECIES_RAIKOU_CRYSTAL 0x23E // NEW FORM
#define SPECIES_ENTEI_CRYSTAL 0x23F // NEW FORM
#define SPECIES_SUICUNE_CRYSTAL 0x240 // NEW FORM
#define SPECIES_PIKACHU_SURFING 0x241 // NEW FORM, BUT THERE WAS AN ENTRY??
#define SPECIES_PIKACHU_FLYING 0x242 // NEW FORM, BUT THERE WAS AN ENTRY??
#define SPECIES_PIKACHU_NARCIS 0x243 // NEW FORM FOR ROSE 2
#define SPECIES_PIKACHU_NARCIS_SURF 0x244 // NEW FORM FOR ROSE 2
#define SPECIES_PIKACHU_NARCIS_FLY 0x245 // NEW FORM FOR ROSE 2
#define SPECIES_ONIX_CRYSTAL 0x246 // NEW FORM
#define SPECIES_STEELIX_CARBYNE 0x247 // NEW FORM
#define SPECIES_PORYGON_GLITCH 0x248 // NEW FORM
#define SPECIES_PORYGON2_GLITCH 0x249 // NEW FORM
#define SPECIES_PORYGON_Z_GLITCH 0x24A // NEW FORM
#define SPECIES_MAGNEZONE_SPACESHIP 0x24B // NEW FORM
#define SPECIES_GIRATINA_ORIGIN 0x24C
#define SPECIES_SHAYMIN_SKY 0x24D
#define SPECIES_TORNADUS_THERIAN 0x24E
#define SPECIES_THUNDURUS_THERIAN 0x24F
#define SPECIES_LANDORUS_THERIAN 0x250
#define SPECIES_AEGISLASH_BLADE 0x251
#define SPECIES_DIANCIE_SOLSTICE 0x252 // NEW FORM FOR ROSE 2
#define SPECIES_SABLEYE_SOLSTICE 0x253 // NEW FORM FOR ROSE 2
#define SPECIES_SPIRITOMB_SOLSTICE 0x254 // NEW FORM FOR ROSE 2
#define SPECIES_LUGIATWO 0x255 // PLACEHOLDER
#define SPECIES_EXEGGUTOR_A 0x256
#define SPECIES_VULPIX_A 0x257
#define SPECIES_NINETALES_A 0x258
#define SPECIES_ROCKRUFF_OWNTEMPO 0x259 // NEW FORM FOR DUSK LYCANROC EVOLUTION
#define SPECIES_LYCANROC_N 0x25A
#define SPECIES_LYCANROC_DUSK 0x25B
#define SPECIES_YAMASK_G 0x25C
#define SPECIES_WEEZING_G 0x25D
#define SPECIES_SNORUNT_VOLCANO 0x25E // NEW FORM
#define SPECIES_GLALIE_VOLCANO 0x25F // NEW FORM
#define SPECIES_FROSLASS_VOLCANO 0x260 // NEW FORM
#define SPECIES_ZYGARDE_10 0x261
#define SPECIES_ZYGARDE_COMPLETE 0x262
#define SPECIES_BANETTE_CLEFAIRYDOLL 0x263 // NEW FORM
#define SPECIES_BANETTE_LCDOLL 0x264 // NEW FORM
#define SPECIES_BANETTE_DJDOLL 0x265 // NEW FORM
#define SPECIES_MURKROW_GSBETA 0x266 // NEW FORM
#define SPECIES_PORYGON_PIKACHUCONVERSION 0x267 // NEW FORM
#define SPECIES_EXEGGUTOR_RAINBOW 0x268 // NEW FORM PLACEHOLDER
#define SPECIES_DRATINI_ROSE 0x269 // NEW FORM PLACEHOLDER
#define SPECIES_DRAGONAIR_ROSE 0x26A // NEW FORM PLACEHOLDER
#define SPECIES_DRAGONITE_ROSE 0x26B // NEW FORM PLACEHOLDER
#define SPECIES_ROSELIA_ROSE 0x26C // NEW FORM PLACEHOLDER
#define SPECIES_ROSERADE_ROSE 0x26D // NEW FORM PLACEHOLDER
#define SPECIES_ARCANINE_ROSE 0x26E // NEW FORM PLACEHOLDER
#define SPECIES_LEDIAN_ROSE 0x26F // NEW FORM PLACEHOLDER
#define SPECIES_NEWFORM1_ROSE 0x270 // NEW FORM PLACEHOLDER
#define SPECIES_NEWFORM2_ROSE 0x271 // NEW FORM PLACEHOLDER
#define SPECIES_FLABEBE_ROSE 0x272 // NEW FORM PLACEHOLDER
#define SPECIES_FLOETTE_ROSE 0x273 // NEW FORM PLACEHOLDER
#define SPECIES_FLORGES_ROSE 0x274 // NEW FORM PLACEHOLDER
#define SPECIES_TOGEPI_ROSE 0x275 // NEW FORM PLACEHOLDER
#define SPECIES_TOGETIC_ROSE 0x276 // NEW FORM PLACEHOLDER
#define SPECIES_TOGEKISS_ROSE 0x277 // NEW FORM PLACEHOLDER
#define SPECIES_DEOXYS_EMERALD 0x278 // FINAL BOSS
#define SPECIES_RAYQUAZA_EMERALD 0x279 // FOR ROSE 2
#define SPECIES_ARTICUNO_EMERALD 0x27A // FOR ROSE 2
#define SPECIES_ZAPDOS_EMERALD 0x27B // FOR ROSE 2
#define SPECIES_MOLTRES_EMERALD 0x27C // FOR ROSE 2
#define SPECIES_RAIKOU_EMERALD 0x27D // FOR ROSE 2
#define SPECIES_ENTEI_EMERALD 0x27E // FOR ROSE 2
#define SPECIES_SUICUNE_EMERALD 0x27F // FOR ROSE 2
#define SPECIES_LUGIA_EMERALD 0x280 // FOR ROSE 2
#define SPECIES_HO_OH_EMERALD 0x281 // FOR ROSE 2
#define SPECIES_ARCEUS_FIGHT 0x282
#define SPECIES_ARCEUS_FLYING 0x283
#define SPECIES_ARCEUS_POISON 0x284
#define SPECIES_ARCEUS_GROUND 0x285
#define SPECIES_ARCEUS_ROCK 0x286
#define SPECIES_ARCEUS_BUG 0x287
#define SPECIES_ARCEUS_GHOST 0x288
#define SPECIES_ARCEUS_STEEL 0x289
#define SPECIES_ARCEUS_FIRE 0x28A
#define SPECIES_ARCEUS_WATER 0x28B
#define SPECIES_ARCEUS_GRASS 0x28C
#define SPECIES_ARCEUS_ELECTRIC 0x28D
#define SPECIES_ARCEUS_PSYCHIC 0x28E
#define SPECIES_ARCEUS_ICE 0x28F
#define SPECIES_ARCEUS_DRAGON 0x290
#define SPECIES_ARCEUS_DARK 0x291
#define SPECIES_ARCEUS_FAIRY 0x292
#define SPECIES_ARCEUS_MYSTERY 0x293 // NEW FORM
#define SPECIES_GENESECT_DOUSE 0x294
#define SPECIES_GENESECT_SHOCK 0x295
#define SPECIES_GENESECT_BURN 0x296
#define SPECIES_GENESECT_CHILL 0x297
#define SPECIES_GENESECT_LEAFY 0x298 // NEW FORM
#define SPECIES_GENESECT_FABLE 0x299 // NEW FORM
#define SPECIES_GENESECT_SHADY 0x29A // NEW FORM
#define SPECIES_GENESECT_STONE 0x29B // NEW FORM
#define SPECIES_DITTO_BULBASAUR 0x29C // NEW FORM
#define SPECIES_DITTO_CHARMANDER 0x29D // NEW FORM
#define SPECIES_DITTO_SQUIRTLE 0x29E // NEW FORM
#define SPECIES_DITTO_CHIKORITA 0x29F // NEW FORM
#define SPECIES_DITTO_CYNDAQUIL 0x2A0 // NEW FORM
#define SPECIES_DITTO_TOTODILE 0x2A1 // NEW FORM
#define SPECIES_DITTO_TREECKO 0x2A2 // NEW FORM
#define SPECIES_DITTO_TORCHIC 0x2A3 // NEW FORM
#define SPECIES_DITTO_MUDKIP 0x2A4 // NEW FORM
#define SPECIES_DITTO_TURTWIG 0x2A5 // NEW FORM
#define SPECIES_DITTO_CHIMCHAR 0x2A6 // NEW FORM
#define SPECIES_DITTO_PIPLUP 0x2A7 // NEW FORM
#define SPECIES_DITTO_PIKACHU 0x2A8 // NEW FORM
#define SPECIES_DITTO_MEOWTH 0x2A9 // NEW FORM
#define SPECIES_DITTO_SNEASEL 0x2AA // NEW FORM
#define SPECIES_DITTO_SABLEYE 0x2AB // NEW FORM
#define SPECIES_DITTO_KOFFING 0x2AC // NEW FORM
#define SPECIES_DITTO_CLEFAIRY 0x2AD // NEW FORM
#define SPECIES_DITTO_WOBBUFFET 0x2AE // NEW FORM
#define SPECIES_DITTO_GENGAR 0x2AF // NEW FORM
#define SPECIES_DITTO_SCIZOR 0x2B0 // NEW FORM
#define SPECIES_DITTO_LUCARIO 0x2B1 // NEW FORM
#define SPECIES_DITTO_ABSOL 0x2B2 // NEW FORM
#define SPECIES_DITTO_EXEGGUTOR 0x2B3 // NEW FORM
#define SPECIES_DITTO_DEOXYS 0x2B4 // NEW FORM
#define SPECIES_PARASECT_ICE 0x2B5 // NEW FORM
#define SPECIES_GARBODOR_SCRAP 0x2B6 // NEW FORM
#define SPECIES_PIDGEY_RED 0x2B7 // NEW FORM
#define SPECIES_PIDGEOTTO_RED 0x2B8 // NEW FORM
#define SPECIES_PIDGEOT_RED 0x2B9 // NEW FORM
#define SPECIES_DUSKULL_SOLSTICE 0x2BA // NEW FORM
#define SPECIES_DUSCLOPS_SOLSTICE 0x2BB // NEW FORM
#define SPECIES_DUSKNOIR_SOLSTICE 0x2BC // NEW FORM
#define SPECIES_RSM_RADIO 0x2BD // ROCKET'S SECRET MACHINE
#define SPECIES_RSM_TICKLE 0x2BE // ROCKET'S SECRET MACHINE
#define SPECIES_RSM_SLEEP 0x2BF // ROCKET'S SECRET MACHINE
#define SPECIES_RSM_DIGGER 0x2C0 // ROCKET'S SECRET MACHINE
#define SPECIES_RSM_ERROR 0x2C1 // ROCKET'S SECRET MACHINE
#define SPECIES_PONYTA_G 0x2C2
#define SPECIES_RAPIDASH_G 0x2C3
#define SPECIES_COSMOG 0x2C4
#define SPECIES_COSMOEM 0x2C5
#define SPECIES_SOLGALEO 0x2C6
#define SPECIES_LUNALA 0x2C7
#define SPECIES_MIMIKYU 0x2C8
#define SPECIES_MIMIKYU_BUSTED 0x2C9
#define SPECIES_MAROWAK_A 0x2CA
#define SPECIES_REGIELEKI 0x2CB
#define SPECIES_REGIDRAGO 0x2CC
#define SPECIES_ZYGARDE_CELL 0x2CD
#define SPECIES_ZYGARDE_CORE 0x2CE
#define SPECIES_FLOETTE_ETERNAL 0x2CF
#define SPECIES_NEW_SLOT_15 0x2D0 // EMPTY SLOT
#define SPECIES_NEW_SLOT_16 0x2D1 // EMPTY SLOT
#define SPECIES_NEW_SLOT_17 0x2D2 // EMPTY SLOT
#define SPECIES_NEW_SLOT_18 0x2D3 // EMPTY SLOT
#define SPECIES_NEW_SLOT_19 0x2D4 // EMPTY SLOT
#define SPECIES_NEW_SLOT_20 0x2D5 // EMPTY SLOT
#define SPECIES_NEW_SLOT_21 0x2D6 // EMPTY SLOT
#define SPECIES_NEW_SLOT_22 0x2D7 // EMPTY SLOT
#define SPECIES_NEW_SLOT_23 0x2D8 // EMPTY SLOT
#define SPECIES_NEW_SLOT_24 0x2D9 // EMPTY SLOT
#define SPECIES_NEW_SLOT_25 0x2DA // EMPTY SLOT
#define SPECIES_NEW_SLOT_26 0x2DB // EMPTY SLOT
#define SPECIES_NEW_SLOT_27 0x2DC // EMPTY SLOT
#define SPECIES_NEW_SLOT_28 0x2DD // EMPTY SLOT
#define SPECIES_NEW_SLOT_29 0x2DE // EMPTY SLOT
#define SPECIES_NEW_SLOT_30 0x2DF // EMPTY SLOT
#define SPECIES_NEW_SLOT_31 0x2E0 // EMPTY SLOT
#define SPECIES_NEW_SLOT_32 0x2E1 // EMPTY SLOT
#define SPECIES_NEW_SLOT_33 0x2E2 // EMPTY SLOT
#define SPECIES_NEW_SLOT_34 0x2E3 // EMPTY SLOT
#define SPECIES_NEW_SLOT_35 0x2E4 // EMPTY SLOT
#define SPECIES_NEW_SLOT_36 0x2E5 // EMPTY SLOT
#define SPECIES_NEW_SLOT_37 0x2E6 // EMPTY SLOT
#define SPECIES_NEW_SLOT_38 0x2E7 // EMPTY SLOT
#define SPECIES_NEW_SLOT_39 0x2E8 // EMPTY SLOT
#define SPECIES_NEW_SLOT_40 0x2E9 // EMPTY SLOT
#define SPECIES_NEW_SLOT_41 0x2EA // EMPTY SLOT
#define SPECIES_NEW_SLOT_42 0x2EB // EMPTY SLOT
#define SPECIES_NEW_SLOT_43 0x2EC // EMPTY SLOT
#define SPECIES_NEW_SLOT_44 0x2ED // EMPTY SLOT
#define SPECIES_NEW_SLOT_45 0x2EE // EMPTY SLOT
#define SPECIES_NEW_SLOT_46 0x2EF // EMPTY SLOT
#define SPECIES_NEW_SLOT_47 0x2F0 // EMPTY SLOT
#define SPECIES_NEW_SLOT_48 0x2F1 // EMPTY SLOT
#define SPECIES_NEW_SLOT_49 0x2F2 // EMPTY SLOT
#define SPECIES_NEW_SLOT_50 0x2F3 // EMPTY SLOT
#define SPECIES_NEW_SLOT_51 0x2F4 // EMPTY SLOT
#define SPECIES_NEW_SLOT_52 0x2F5 // EMPTY SLOT
#define SPECIES_NEW_SLOT_53 0x2F6 // EMPTY SLOT
#define SPECIES_NEW_SLOT_54 0x2F7 // EMPTY SLOT
#define SPECIES_NEW_SLOT_55 0x2F8 // EMPTY SLOT
#define SPECIES_NEW_SLOT_56 0x2F9 // EMPTY SLOT
#define SPECIES_NEW_SLOT_57 0x2FA // EMPTY SLOT
#define SPECIES_NEW_SLOT_58 0x2FB // EMPTY SLOT
#define SPECIES_NEW_SLOT_59 0x2FC // EMPTY SLOT
#define SPECIES_NEW_SLOT_60 0x2FD // EMPTY SLOT
#define SPECIES_NEW_SLOT_61 0x2FE // EMPTY SLOT
#define SPECIES_NEW_SLOT_62 0x2FF // EMPTY SLOT
#define SPECIES_NEW_SLOT_63 0x300 // EMPTY SLOT
#define SPECIES_NEW_SLOT_64 0x301 // EMPTY SLOT
#define SPECIES_NEW_SLOT_65 0x302 // EMPTY SLOT
#define SPECIES_NEW_SLOT_66 0x303 // EMPTY SLOT
#define SPECIES_NEW_SLOT_67 0x304 // EMPTY SLOT
#define SPECIES_NEW_SLOT_68 0x305 // EMPTY SLOT
#define SPECIES_NEW_SLOT_69 0x306 // EMPTY SLOT
#define SPECIES_NEW_SLOT_70 0x307 // EMPTY SLOT
#define SPECIES_NIHILEGO 0x308
#define SPECIES_BUZZWOLE 0x309
#define SPECIES_PHEROMOSA 0x30A
#define SPECIES_XURKITREE 0x30B
#define SPECIES_KARTANA 0x30C
#define SPECIES_CELESTEELA 0x30D
#define SPECIES_GUZZLORD 0x30E
#define SPECIES_BLACEPHALON 0x30F
#define SPECIES_STAKATAKA 0x310
#define SPECIES_POIPOLE 0x311
#define SPECIES_NAGANADEL 0x312
#define SPECIES_NECROZMA_PLACEHOLDER 0x313 // PLACEHOLDER SLOT
#define SPECIES_NECROZMA_DUSK_MANE 0x314
#define SPECIES_NECROZMA_DAWN_WINGS 0x315
#define SPECIES_NECROZMA_ULTRA 0x316
#define SPECIES_KYUREM 0x317
#define SPECIES_KYUREM_BLACK 0x318
#define SPECIES_KYUREM_WHITE 0x319
#define SPECIES_KYUREM_ORIGINAL 0x31A // NEW FORM
#define SPECIES_ETERNATUS 0x31B
#define SPECIES_ETERNATUS_ETERNAMAX 0x31C
#define SPECIES_RAYQUAZA_MEGA 0x31D
#define SPECIES_MEWTWO_ARMOR 0x31E // NEW FORM
#define SPECIES_LUGIA_SHADOW 0x31F // NEW FORM
#define SPECIES_ARCEUS_FINAL 0x320 // NEW FORM
//End of slots


//These are all to be nulled
//Gen 4 nulled
#define SPECIES_STARLY 0xFFFE 
#define SPECIES_STARAVIA 0xFFFE 
#define SPECIES_STARAPTOR 0xFFFE 
#define SPECIES_BIDOOF 0xFFFE 
#define SPECIES_BIBAREL 0xFFFE 
#define SPECIES_KRICKETOT 0xFFFE 
#define SPECIES_KRICKETUNE 0xFFFE 
#define SPECIES_CRANIDOS 0xFFFE 
#define SPECIES_RAMPARDOS 0xFFFE 
#define SPECIES_SHIELDON 0xFFFE 
#define SPECIES_BASTIODON 0xFFFE 
#define SPECIES_BURMY 0xFFFE 
#define SPECIES_WORMADAM 0xFFFE 
#define SPECIES_MOTHIM 0xFFFE 
#define SPECIES_COMBEE 0xFFFE 
#define SPECIES_VESPIQUEN 0xFFFE 
#define SPECIES_PACHIRISU 0xFFFE 
#define SPECIES_BUIZEL 0xFFFE 
#define SPECIES_FLOATZEL 0xFFFE 
#define SPECIES_CHERUBI 0xFFFE 
#define SPECIES_CHERRIM 0xFFFE 
#define SPECIES_SHELLOS 0xFFFE 
#define SPECIES_GASTRODON 0xFFFE 
#define SPECIES_DRIFLOON 0xFFFE 
#define SPECIES_DRIFBLIM 0xFFFE 
#define SPECIES_BUNEARY 0xFFFE 
#define SPECIES_LOPUNNY 0xFFFE 
#define SPECIES_GLAMEOW 0xFFFE 
#define SPECIES_PURUGLY 0xFFFE 
#define SPECIES_STUNKY 0xFFFE 
#define SPECIES_SKUNTANK 0xFFFE 
#define SPECIES_CHATOT 0xFFFE 
#define SPECIES_HIPPOPOTAS 0xFFFE 
#define SPECIES_HIPPOWDON 0xFFFE 
#define SPECIES_SKORUPI 0xFFFE 
#define SPECIES_DRAPION 0xFFFE 
#define SPECIES_CARNIVINE 0xFFFE 
#define SPECIES_FINNEON 0xFFFE 
#define SPECIES_LUMINEON 0xFFFE 
#define SPECIES_UXIE 0xFFFE 
#define SPECIES_MESPRIT 0xFFFE 
#define SPECIES_AZELF 0xFFFE 
#define SPECIES_PHIONE 0xFFFE 
#define SPECIES_MANAPHY 0xFFFE 
#define SPECIES_VICTINI 0xFFFE 
   
//Gen 5  nulled
#define SPECIES_SNIVY 0xFFFE 
#define SPECIES_SERVINE 0xFFFE 
#define SPECIES_SERPERIOR 0xFFFE 
#define SPECIES_TEPIG 0xFFFE 
#define SPECIES_PIGNITE 0xFFFE 
#define SPECIES_EMBOAR 0xFFFE 
#define SPECIES_OSHAWOTT 0xFFFE 
#define SPECIES_DEWOTT 0xFFFE 
#define SPECIES_SAMUROTT 0xFFFE 
#define SPECIES_PATRAT 0xFFFE 
#define SPECIES_WATCHOG 0xFFFE 
#define SPECIES_LILLIPUP 0xFFFE 
#define SPECIES_HERDIER 0xFFFE 
#define SPECIES_STOUTLAND 0xFFFE 
#define SPECIES_PURRLOIN 0xFFFE 
#define SPECIES_LIEPARD 0xFFFE 
#define SPECIES_PANSAGE 0xFFFE 
#define SPECIES_SIMISAGE 0xFFFE 
#define SPECIES_PANSEAR 0xFFFE 
#define SPECIES_SIMISEAR 0xFFFE 
#define SPECIES_PANPOUR 0xFFFE 
#define SPECIES_SIMIPOUR 0xFFFE 
#define SPECIES_MUNNA 0xFFFE 
#define SPECIES_MUSHARNA 0xFFFE 
#define SPECIES_PIDOVE 0xFFFE 
#define SPECIES_TRANQUILL 0xFFFE 
#define SPECIES_UNFEZANT 0xFFFE 
#define SPECIES_BLITZLE 0xFFFE 
#define SPECIES_ZEBSTRIKA 0xFFFE 
#define SPECIES_ROGGENROLA 0xFFFE 
#define SPECIES_BOLDORE 0xFFFE 
#define SPECIES_GIGALITH 0xFFFE 
#define SPECIES_WOOBAT 0xFFFE 
#define SPECIES_SWOOBAT 0xFFFE 
#define SPECIES_AUDINO 0xFFFE 
#define SPECIES_TIMBURR 0xFFFE 
#define SPECIES_GURDURR 0xFFFE 
#define SPECIES_CONKELDURR 0xFFFE 
#define SPECIES_TYMPOLE 0xFFFE 
#define SPECIES_PALPITOAD 0xFFFE 
#define SPECIES_SEISMITOAD 0xFFFE 
#define SPECIES_THROH 0xFFFE 
#define SPECIES_SAWK 0xFFFE 
#define SPECIES_SEWADDLE 0xFFFE 
#define SPECIES_SWADLOON 0xFFFE 
#define SPECIES_LEAVANNY 0xFFFE 
#define SPECIES_VENIPEDE 0xFFFE 
#define SPECIES_WHIRLIPEDE 0xFFFE 
#define SPECIES_SCOLIPEDE 0xFFFE 
#define SPECIES_COTTONEE 0xFFFE 
#define SPECIES_WHIMSICOTT 0xFFFE 
#define SPECIES_PETILIL 0xFFFE 
#define SPECIES_LILLIGANT 0xFFFE 
#define SPECIES_BASCULIN_RED 0xFFFE 
#define SPECIES_SANDILE 0xFFFE 
#define SPECIES_KROKOROK 0xFFFE 
#define SPECIES_KROOKODILE 0xFFFE 
#define SPECIES_DARUMAKA 0xFFFE 
#define SPECIES_DARMANITAN 0xFFFE 
#define SPECIES_MARACTUS 0xFFFE 
#define SPECIES_DWEBBLE 0xFFFE 
#define SPECIES_CRUSTLE 0xFFFE 
#define SPECIES_TIRTOUGA 0xFFFE 
#define SPECIES_CARRACOSTA 0xFFFE 
#define SPECIES_ZORUA 0xFFFE 
#define SPECIES_ZOROARK 0xFFFE 
#define SPECIES_MINCCINO 0xFFFE 
#define SPECIES_CINCCINO 0xFFFE 
#define SPECIES_GOTHITA 0xFFFE 
#define SPECIES_GOTHORITA 0xFFFE 
#define SPECIES_GOTHITELLE 0xFFFE 
#define SPECIES_DUCKLETT 0xFFFE 
#define SPECIES_SWANNA 0xFFFE 
#define SPECIES_VANILLITE 0xFFFE 
#define SPECIES_VANILLISH 0xFFFE 
#define SPECIES_VANILLUXE 0xFFFE 
#define SPECIES_DEERLING 0xFFFE 
#define SPECIES_SAWSBUCK 0xFFFE 
#define SPECIES_EMOLGA 0xFFFE 
#define SPECIES_KARRABLAST 0xFFFE 
#define SPECIES_ESCAVALIER 0xFFFE 
#define SPECIES_FOONGUS 0xFFFE 
#define SPECIES_AMOONGUSS 0xFFFE 
#define SPECIES_ALOMOMOLA 0xFFFE 
#define SPECIES_JOLTIK 0xFFFE 
#define SPECIES_GALVANTULA 0xFFFE 
#define SPECIES_FERROSEED 0xFFFE 
#define SPECIES_FERROTHORN 0xFFFE 
   
#define SPECIES_TYNAMO 0xFFFE 
#define SPECIES_EELEKTRIK 0xFFFE 
#define SPECIES_EELEKTROSS 0xFFFE 
#define SPECIES_ELGYEM 0xFFFE 
#define SPECIES_BEHEEYEM 0xFFFE 
#define SPECIES_LITWICK 0xFFFE 
#define SPECIES_LAMPENT 0xFFFE 
#define SPECIES_CHANDELURE 0xFFFE 
#define SPECIES_AXEW 0xFFFE 
#define SPECIES_FRAXURE 0xFFFE 
#define SPECIES_HAXORUS 0xFFFE 
#define SPECIES_CUBCHOO 0xFFFE 
#define SPECIES_BEARTIC 0xFFFE 
#define SPECIES_CRYOGONAL 0xFFFE 
#define SPECIES_SHELMET 0xFFFE 
#define SPECIES_ACCELGOR 0xFFFE 
#define SPECIES_STUNFISK 0xFFFE 
#define SPECIES_MIENFOO 0xFFFE 
#define SPECIES_MIENSHAO 0xFFFE 
#define SPECIES_DRUDDIGON 0xFFFE 
   
#define SPECIES_BOUFFALANT 0xFFFE 
#define SPECIES_RUFFLET 0xFFFE 
#define SPECIES_BRAVIARY 0xFFFE 
#define SPECIES_VULLABY 0xFFFE 
#define SPECIES_MANDIBUZZ 0xFFFE 
#define SPECIES_HEATMOR 0xFFFE 
#define SPECIES_DURANT 0xFFFE 
   
#define SPECIES_COBALION 0xFFFE 
#define SPECIES_TERRAKION 0xFFFE 
#define SPECIES_VIRIZION 0xFFFE 
   
#define SPECIES_RESHIRAM 0xFFFE 
#define SPECIES_ZEKROM 0xFFFE 
   
#define SPECIES_KELDEO 0xFFFE 
#define SPECIES_MELOETTA 0xFFFE 
#define SPECIES_UNFEZANT_F 0xFFFE 
   
#define SPECIES_SHADOW_WARRIOR 0xFFFE 
#define SPECIES_BURMY_SANDY 0xFFFE 
#define SPECIES_BURMY_TRASH 0xFFFE 
#define SPECIES_WORMADAM_SANDY 0xFFFE 
#define SPECIES_WORMADAM_TRASH 0xFFFE 
#define SPECIES_SHELLOS_EAST 0xFFFE 
#define SPECIES_GASTRODON_EAST 0xFFFE 
   
#define SPECIES_BASCULIN_BLUE 0xFFFE 
#define SPECIES_DARMANITANZEN 0xFFFE 
#define SPECIES_DEERLING_SUMMER 0xFFFE 
#define SPECIES_DEERLING_AUTUMN 0xFFFE 
#define SPECIES_DEERLING_WINTER 0xFFFE 
#define SPECIES_SAWSBUCK_SUMMER 0xFFFE 
#define SPECIES_SAWSBUCK_AUTUMN 0xFFFE 
#define SPECIES_SAWSBUCK_WINTER 0xFFFE 
#define SPECIES_HIPPOPOTAS_F 0xFFFE 
#define SPECIES_HIPPOWDON_F 0xFFFE 
#define SPECIES_MELOETTA_PIROUETTE 0xFFFE 
#define SPECIES_CHERRIM_SUN 0xFFFE 
#define SPECIES_KELDEO_RESOLUTE 0xFFFE 
   
//Gen 6  nulled
#define SPECIES_CHESPIN 0xFFFE 
#define SPECIES_QUILLADIN 0xFFFE 
#define SPECIES_CHESNAUGHT 0xFFFE 
#define SPECIES_FENNEKIN 0xFFFE 
#define SPECIES_BRAIXEN 0xFFFE 
#define SPECIES_DELPHOX 0xFFFE 
#define SPECIES_FROAKIE 0xFFFE 
#define SPECIES_FROGADIER 0xFFFE 
#define SPECIES_GRENINJA 0xFFFE 
#define SPECIES_BUNNELBY 0xFFFE 
#define SPECIES_DIGGERSBY 0xFFFE 
#define SPECIES_FLETCHLING 0xFFFE 
#define SPECIES_FLETCHINDER 0xFFFE 
#define SPECIES_TALONFLAME 0xFFFE 
#define SPECIES_SCATTERBUG 0xFFFE 
#define SPECIES_SPEWPA 0xFFFE 
#define SPECIES_VIVILLON 0xFFFE 
#define SPECIES_LITLEO 0xFFFE 
#define SPECIES_PYROAR 0xFFFE 
#define SPECIES_SKIDDO 0xFFFE 
#define SPECIES_GOGOAT 0xFFFE 
#define SPECIES_PANCHAM 0xFFFE 
#define SPECIES_PANGORO 0xFFFE 
#define SPECIES_FURFROU 0xFFFE 
#define SPECIES_ESPURR 0xFFFE 
#define SPECIES_MEOWSTIC 0xFFFE 
#define SPECIES_SPRITZEE 0xFFFE 
#define SPECIES_AROMATISSE 0xFFFE 
#define SPECIES_SWIRLIX 0xFFFE 
#define SPECIES_SLURPUFF 0xFFFE 
#define SPECIES_INKAY 0xFFFE 
#define SPECIES_MALAMAR 0xFFFE 
#define SPECIES_BINACLE 0xFFFE 
#define SPECIES_BARBARACLE 0xFFFE 
#define SPECIES_SKRELP 0xFFFE 
#define SPECIES_DRAGALGE 0xFFFE 
#define SPECIES_CLAUNCHER 0xFFFE 
#define SPECIES_CLAWITZER 0xFFFE 
#define SPECIES_HELIOPTILE 0xFFFE 
#define SPECIES_HELIOLISK 0xFFFE 
#define SPECIES_AMAURA 0xFFFE 
#define SPECIES_AURORUS 0xFFFE 
#define SPECIES_HAWLUCHA 0xFFFE 
#define SPECIES_DEDENNE 0xFFFE 
#define SPECIES_CARBINK 0xFFFE 
#define SPECIES_GOOMY 0xFFFE 
#define SPECIES_SLIGGOO 0xFFFE 
#define SPECIES_GOODRA 0xFFFE 
#define SPECIES_BERGMITE 0xFFFE 
#define SPECIES_AVALUGG 0xFFFE 
#define SPECIES_NOIBAT 0xFFFE 
#define SPECIES_NOIVERN 0xFFFE 
#define SPECIES_XERNEAS 0xFFFE 
#define SPECIES_YVELTAL 0xFFFE 
#define SPECIES_HOOPA 0xFFFE 
#define SPECIES_HOOPA_UNBOUND 0xFFFE 
#define SPECIES_VOLCANION 0xFFFE 
#define SPECIES_PYROAR_FEMALE 0xFFFE 
#define SPECIES_MEOWSTIC_FEMALE 0xFFFE 
   
#define SPECIES_ASHGRENINJA 0xFFFE 
#define SPECIES_FLABEBE_BLUE 0xFFFE 
#define SPECIES_FLABEBE_ORANGE 0xFFFE 
#define SPECIES_FLABEBE_YELLOW 0xFFFE 
#define SPECIES_FLABEBE_WHITE 0xFFFE 
#define SPECIES_FLOETTE_BLUE 0xFFFE 
#define SPECIES_FLOETTE_ORANGE 0xFFFE 
#define SPECIES_FLOETTE_YELLOW 0xFFFE 
#define SPECIES_FLOETTE_WHITE 0xFFFE 
#define SPECIES_FLORGES_BLUE 0xFFFE 
#define SPECIES_FLORGES_ORANGE 0xFFFE 
#define SPECIES_FLORGES_YELLOW 0xFFFE 
#define SPECIES_FLORGES_WHITE 0xFFFE 
#define SPECIES_PUMPKABOO_XL 0xFFFE 
#define SPECIES_PUMPKABOO_L 0xFFFE 
#define SPECIES_PUMPKABOO_M 0xFFFE 
#define SPECIES_GOURGEIST_XL 0xFFFE 
#define SPECIES_GOURGEIST_L 0xFFFE 
#define SPECIES_GOURGEIST_M 0xFFFE 
   
#define SPECIES_FURFROU_HEART 0xFFFE 
#define SPECIES_FURFROU_DIAMOND 0xFFFE 
#define SPECIES_FURFROU_STAR 0xFFFE 
#define SPECIES_FURFROU_PHAROAH 0xFFFE 
#define SPECIES_FURFROU_KABUKI 0xFFFE 
#define SPECIES_FURFROU_LA_REINE 0xFFFE 
#define SPECIES_FURFROU_MATRON 0xFFFE 
#define SPECIES_FURFROU_DANDY 0xFFFE 
#define SPECIES_FURFROU_DEBUTANTE 0xFFFE 
#define SPECIES_VIVILLON_FANCY 0xFFFE 
#define SPECIES_VENUSAUR_MEGA 0xFFFE 
#define SPECIES_CHARIZARD_MEGA_X 0xFFFE 
#define SPECIES_CHARIZARD_MEGA_Y 0xFFFE 
#define SPECIES_BLASTOISE_MEGA 0xFFFE 
#define SPECIES_BEEDRILL_MEGA 0xFFFE 
#define SPECIES_PIDGEOT_MEGA 0xFFFE 
#define SPECIES_ALAKAZAM_MEGA 0xFFFE 
#define SPECIES_SLOWBRO_MEGA 0xFFFE 
#define SPECIES_GENGAR_MEGA 0xFFFE 
#define SPECIES_KANGASKHAN_MEGA 0xFFFE 
#define SPECIES_PINSIR_MEGA 0xFFFE 
#define SPECIES_GYARADOS_MEGA 0xFFFE 
#define SPECIES_AERODACTYL_MEGA 0xFFFE 
#define SPECIES_MEWTWO_MEGA_X 0xFFFE 
#define SPECIES_MEWTWO_MEGA_Y 0xFFFE 
#define SPECIES_AMPHAROS_MEGA 0xFFFE 
#define SPECIES_STEELIX_MEGA 0xFFFE 
#define SPECIES_SCIZOR_MEGA 0xFFFE 
#define SPECIES_HERACROSS_MEGA 0xFFFE 
#define SPECIES_HOUNDOOM_MEGA 0xFFFE 
#define SPECIES_TYRANITAR_MEGA 0xFFFE 
#define SPECIES_SCEPTILE_MEGA 0xFFFE 
#define SPECIES_BLAZIKEN_MEGA 0xFFFE 
#define SPECIES_SWAMPERT_MEGA 0xFFFE 
#define SPECIES_GARDEVOIR_MEGA 0xFFFE 
#define SPECIES_SABLEYE_MEGA 0xFFFE 
#define SPECIES_MAWILE_MEGA 0xFFFE 
#define SPECIES_AGGRON_MEGA 0xFFFE 
#define SPECIES_MEDICHAM_MEGA 0xFFFE 
#define SPECIES_MANECTRIC_MEGA 0xFFFE 
#define SPECIES_SHARPEDO_MEGA 0xFFFE 
#define SPECIES_CAMERUPT_MEGA 0xFFFE 
#define SPECIES_ALTARIA_MEGA 0xFFFE 
#define SPECIES_BANETTE_MEGA 0xFFFE 
#define SPECIES_ABSOL_MEGA 0xFFFE 
#define SPECIES_GLALIE_MEGA 0xFFFE 
#define SPECIES_SALAMENCE_MEGA 0xFFFE 
#define SPECIES_METAGROSS_MEGA 0xFFFE 
#define SPECIES_LATIAS_MEGA 0xFFFE 
#define SPECIES_LATIOS_MEGA 0xFFFE 
#define SPECIES_GROUDON_PRIMAL 0xFFFE 
#define SPECIES_KYOGRE_PRIMAL 0xFFFE 
   
#define SPECIES_LOPUNNY_MEGA 0xFFFE 
#define SPECIES_GARCHOMP_MEGA 0xFFFE 
#define SPECIES_LUCARIO_MEGA 0xFFFE 
#define SPECIES_ABOMASNOW_MEGA 0xFFFE 
#define SPECIES_GALLADE_MEGA 0xFFFE 
#define SPECIES_AUDINO_MEGA 0xFFFE 
#define SPECIES_DIANCIE_MEGA 0xFFFE 
#define SPECIES_DIALGA_PRIMAL 0xFFFE 
#define SPECIES_PALKIA_PRIMAL 0xFFFE 
#define SPECIES_VIVILLON_ARCHIPELAGO 0xFFFE 
#define SPECIES_VIVILLON_CONTINENTAL 0xFFFE 
#define SPECIES_VIVILLON_ELEGANT 0xFFFE 
#define SPECIES_VIVILLON_GARDEN 0xFFFE 
#define SPECIES_VIVILLON_HIGH_PLAINS 0xFFFE 
#define SPECIES_VIVILLON_ICY_SNOW 0xFFFE 
#define SPECIES_VIVILLON_JUNGLE 0xFFFE 
#define SPECIES_VIVILLON_MARINE 0xFFFE 
#define SPECIES_VIVILLON_MODERN 0xFFFE 
#define SPECIES_VIVILLON_MONSOON 0xFFFE 
#define SPECIES_VIVILLON_OCEAN 0xFFFE 
#define SPECIES_VIVILLON_POKEBALL 0xFFFE 
#define SPECIES_VIVILLON_POLAR 0xFFFE 
#define SPECIES_VIVILLON_RIVER 0xFFFE 
#define SPECIES_VIVILLON_SANDSTORM 0xFFFE 
#define SPECIES_VIVILLON_SAVANNA 0xFFFE 
#define SPECIES_VIVILLON_SUN 0xFFFE 
#define SPECIES_VIVILLON_TUNDRA 0xFFFE 
   
//Gen 7  nulled
#define SPECIES_ROWLET 0xFFFE 
#define SPECIES_DARTRIX 0xFFFE 
#define SPECIES_DECIDUEYE 0xFFFE 
#define SPECIES_LITTEN 0xFFFE 
#define SPECIES_TORRACAT 0xFFFE 
#define SPECIES_INCINEROAR 0xFFFE 
#define SPECIES_POPPLIO 0xFFFE 
#define SPECIES_BRIONNE 0xFFFE 
#define SPECIES_PRIMARINA 0xFFFE 
#define SPECIES_PIKIPEK 0xFFFE 
#define SPECIES_TRUMBEAK 0xFFFE 
#define SPECIES_TOUCANNON 0xFFFE 
#define SPECIES_YUNGOOS 0xFFFE 
#define SPECIES_GUMSHOOS 0xFFFE 
#define SPECIES_GRUBBIN 0xFFFE 
#define SPECIES_CHARJABUG 0xFFFE 
#define SPECIES_VIKAVOLT 0xFFFE 
#define SPECIES_CRABRAWLER 0xFFFE 
#define SPECIES_CRABOMINABLE 0xFFFE 
#define SPECIES_ORICORIO 0xFFFE 
#define SPECIES_CUTIEFLY 0xFFFE 
#define SPECIES_RIBOMBEE 0xFFFE 
   
#define SPECIES_WISHIWASHI 0xFFFE 
#define SPECIES_MAREANIE 0xFFFE 
#define SPECIES_TOXAPEX 0xFFFE 
#define SPECIES_MUDBRAY 0xFFFE 
#define SPECIES_MUDSDALE 0xFFFE 
#define SPECIES_DEWPIDER 0xFFFE 
#define SPECIES_ARAQUANID 0xFFFE 
#define SPECIES_FOMANTIS 0xFFFE 
#define SPECIES_LURANTIS 0xFFFE 
#define SPECIES_MORELULL 0xFFFE 
#define SPECIES_SHIINOTIC 0xFFFE 
#define SPECIES_SALANDIT 0xFFFE 
#define SPECIES_SALAZZLE 0xFFFE 
#define SPECIES_STUFFUL 0xFFFE 
#define SPECIES_BEWEAR 0xFFFE 
#define SPECIES_BOUNSWEET 0xFFFE 
#define SPECIES_STEENEE 0xFFFE 
#define SPECIES_TSAREENA 0xFFFE 
#define SPECIES_COMFEY 0xFFFE 
#define SPECIES_ORANGURU 0xFFFE 
#define SPECIES_PASSIMIAN 0xFFFE 
#define SPECIES_WIMPOD 0xFFFE 
#define SPECIES_GOLISOPOD 0xFFFE 
#define SPECIES_SANDYGAST 0xFFFE 
#define SPECIES_PALOSSAND 0xFFFE 
#define SPECIES_PYUKUMUKU 0xFFFE 
#define SPECIES_TYPE_NULL 0xFFFE 
#define SPECIES_SILVALLY 0xFFFE 
#define SPECIES_MINIOR_SHIELD 0xFFFE 
#define SPECIES_KOMALA 0xFFFE 
#define SPECIES_TURTONATOR 0xFFFE 
#define SPECIES_TOGEDEMARU 0xFFFE 
   
#define SPECIES_BRUXISH 0xFFFE 
#define SPECIES_DRAMPA 0xFFFE 
#define SPECIES_DHELMISE 0xFFFE 
#define SPECIES_JANGMO_O 0xFFFE 
#define SPECIES_HAKAMO_O 0xFFFE 
#define SPECIES_KOMMO_O 0xFFFE 
#define SPECIES_TAPU_KOKO 0xFFFE 
#define SPECIES_TAPU_LELE 0xFFFE 
#define SPECIES_TAPU_BULU 0xFFFE 
#define SPECIES_TAPU_FINI 0xFFFE 
   
#define SPECIES_MAGEARNA 0xFFFE 
#define SPECIES_MARSHADOW 0xFFFE 
#define SPECIES_RATTATA_A 0xFFFE 
#define SPECIES_RATICATE_A 0xFFFE 
#define SPECIES_RAICHU_A 0xFFFE 
#define SPECIES_SANDSHREW_A 0xFFFE 
#define SPECIES_SANDSLASH_A 0xFFFE 
   
#define SPECIES_DIGLETT_A 0xFFFE 
#define SPECIES_DUGTRIO_A 0xFFFE 
#define SPECIES_MEOWTH_A 0xFFFE 
#define SPECIES_PERSIAN_A 0xFFFE 
#define SPECIES_GEODUDE_A 0xFFFE 
#define SPECIES_GRAVELER_A 0xFFFE 
#define SPECIES_GOLEM_A 0xFFFE 
#define SPECIES_GRIMER_A 0xFFFE 
#define SPECIES_MUK_A 0xFFFE 
#define SPECIES_EXEGGCUTE_A 0xFFFE 
   
#define SPECIES_CUBONE_A 0xFFFE 
   
#define SPECIES_ORICORIO_Y 0xFFFE 
#define SPECIES_ORICORIO_P 0xFFFE 
#define SPECIES_ORICORIO_S 0xFFFE 
   
#define SPECIES_WISHIWASHI_S 0xFFFE 
#define SPECIES_SILVALLY_FIGHT 0xFFFE 
#define SPECIES_SILVALLY_FLYING 0xFFFE 
#define SPECIES_SILVALLY_POISON 0xFFFE 
#define SPECIES_SILVALLY_GROUND 0xFFFE 
#define SPECIES_SILVALLY_ROCK 0xFFFE 
#define SPECIES_SILVALLY_BUG 0xFFFE 
#define SPECIES_SILVALLY_GHOST 0xFFFE 
#define SPECIES_SILVALLY_STEEL 0xFFFE 
#define SPECIES_SILVALLY_FIRE 0xFFFE 
#define SPECIES_SILVALLY_WATER 0xFFFE 
#define SPECIES_SILVALLY_GRASS 0xFFFE 
#define SPECIES_SILVALLY_ELECTRIC 0xFFFE 
#define SPECIES_SILVALLY_PSYCHIC 0xFFFE 
#define SPECIES_SILVALLY_ICE 0xFFFE 
#define SPECIES_SILVALLY_DRAGON 0xFFFE 
#define SPECIES_SILVALLY_DARK 0xFFFE 
#define SPECIES_SILVALLY_FAIRY 0xFFFE 
#define SPECIES_MINIOR_RED 0xFFFE 
#define SPECIES_MINIOR_BLUE 0xFFFE 
#define SPECIES_MINIOR_ORANGE 0xFFFE 
#define SPECIES_MINIOR_YELLOW 0xFFFE 
#define SPECIES_MINIOR_INDIGO 0xFFFE 
#define SPECIES_MINIOR_GREEN 0xFFFE 
#define SPECIES_MINIOR_VIOLET 0xFFFE 
   
#define SPECIES_MAGEARNA_P 0xFFFE 
#define SPECIES_ZERAORA 0xFFFE 
   
#define SPECIES_PIKACHU_COSPLAY 0xFFFE 
#define SPECIES_PIKACHU_LIBRE 0xFFFE 
#define SPECIES_PIKACHU_POP_STAR 0xFFFE 
#define SPECIES_PIKACHU_ROCK_STAR 0xFFFE 
#define SPECIES_PIKACHU_BELLE 0xFFFE 
#define SPECIES_PIKACHU_PHD 0xFFFE 
   
#define SPECIES_PIKACHU_CAP_ORIGINAL 0xFFFE 
#define SPECIES_PIKACHU_CAP_HOENN 0xFFFE 
#define SPECIES_PIKACHU_CAP_SINNOH 0xFFFE 
#define SPECIES_PIKACHU_CAP_UNOVA 0xFFFE 
#define SPECIES_PIKACHU_CAP_KALOS 0xFFFE 
#define SPECIES_PIKACHU_CAP_ALOLA 0xFFFE 
#define SPECIES_PIKACHU_CAP_PARTNER 0xFFFE 
   
#define SPECIES_PICHU_SPIKY 0xFFFE 
#define SPECIES_XERNEAS_NATURAL 0xFFFE 
   
//Gen 8  nulled
#define SPECIES_GROOKEY 0xFFFE 
#define SPECIES_THWACKEY 0xFFFE 
#define SPECIES_RILLABOOM 0xFFFE 
#define SPECIES_SCORBUNNY 0xFFFE 
#define SPECIES_RABOOT 0xFFFE 
#define SPECIES_CINDERACE 0xFFFE 
#define SPECIES_SOBBLE 0xFFFE 
#define SPECIES_DRIZZILE 0xFFFE 
#define SPECIES_INTELEON 0xFFFE 
#define SPECIES_SKWOVET 0xFFFE 
#define SPECIES_GREEDENT 0xFFFE 
#define SPECIES_ROOKIDEE 0xFFFE 
#define SPECIES_CORVISQUIRE 0xFFFE 
#define SPECIES_CORVIKNIGHT 0xFFFE 
#define SPECIES_BLIPBUG 0xFFFE 
#define SPECIES_DOTTLER 0xFFFE 
#define SPECIES_ORBEETLE 0xFFFE 
#define SPECIES_NICKIT 0xFFFE 
#define SPECIES_THIEVUL 0xFFFE 
#define SPECIES_GOSSIFLEUR 0xFFFE 
#define SPECIES_ELDEGOSS 0xFFFE 
#define SPECIES_WOOLOO 0xFFFE 
#define SPECIES_DUBWOOL 0xFFFE 
#define SPECIES_CHEWTLE 0xFFFE 
#define SPECIES_DREDNAW 0xFFFE 
#define SPECIES_YAMPER 0xFFFE 
#define SPECIES_BOLTUND 0xFFFE 
#define SPECIES_ROLYCOLY 0xFFFE 
#define SPECIES_CARKOL 0xFFFE 
#define SPECIES_COALOSSAL 0xFFFE 
#define SPECIES_APPLIN 0xFFFE 
#define SPECIES_FLAPPLE 0xFFFE 
#define SPECIES_APPLETUN 0xFFFE 
#define SPECIES_SILICOBRA 0xFFFE 
#define SPECIES_SANDACONDA 0xFFFE 
#define SPECIES_CRAMORANT 0xFFFE 
#define SPECIES_ARROKUDA 0xFFFE 
#define SPECIES_BARRASKEWDA 0xFFFE 
#define SPECIES_TOXEL 0xFFFE 
#define SPECIES_TOXTRICITY 0xFFFE 
#define SPECIES_SIZZLIPEDE 0xFFFE 
#define SPECIES_CENTISKORCH 0xFFFE 
#define SPECIES_CLOBBOPUS 0xFFFE 
#define SPECIES_GRAPPLOCT 0xFFFE 
#define SPECIES_SINISTEA 0xFFFE 
#define SPECIES_POLTEAGEIST 0xFFFE 
#define SPECIES_HATENNA 0xFFFE 
#define SPECIES_HATTREM 0xFFFE 
#define SPECIES_HATTERENE 0xFFFE 
#define SPECIES_IMPIDIMP 0xFFFE 
#define SPECIES_MORGREM 0xFFFE 
#define SPECIES_GRIMMSNARL 0xFFFE 
#define SPECIES_OBSTAGOON 0xFFFE 
#define SPECIES_PERRSERKER 0xFFFE 
#define SPECIES_CURSOLA 0xFFFE 
#define SPECIES_SIRFETCHD 0xFFFE 
#define SPECIES_MR_RIME 0xFFFE 
   
#define SPECIES_MILCERY 0xFFFE 
#define SPECIES_ALCREMIE_STRAWBERRY 0xFFFE 
#define SPECIES_FALINKS 0xFFFE 
#define SPECIES_PINCURCHIN 0xFFFE 
#define SPECIES_SNOM 0xFFFE 
#define SPECIES_FROSMOTH 0xFFFE 
#define SPECIES_STONJOURNER 0xFFFE 
#define SPECIES_EISCUE 0xFFFE 
#define SPECIES_INDEEDEE 0xFFFE 
#define SPECIES_MORPEKO 0xFFFE 
#define SPECIES_CUFANT 0xFFFE 
#define SPECIES_COPPERAJAH 0xFFFE 
#define SPECIES_DRACOZOLT 0xFFFE 
#define SPECIES_ARCTOZOLT 0xFFFE 
#define SPECIES_DRACOVISH 0xFFFE 
#define SPECIES_ARCTOVISH 0xFFFE 
#define SPECIES_DURALUDON 0xFFFE 
#define SPECIES_DREEPY 0xFFFE 
#define SPECIES_DRAKLOAK 0xFFFE 
#define SPECIES_DRAGAPULT 0xFFFE 
#define SPECIES_ZACIAN 0xFFFE 
#define SPECIES_ZAMAZENTA 0xFFFE 
   
#define SPECIES_KUBFU 0xFFFE 
#define SPECIES_URSHIFU_SINGLE 0xFFFE 
#define SPECIES_ZARUDE 0xFFFE 
#define SPECIES_UNKNOWN_MYTHICAL 0xFFFE 
#define SPECIES_CALYREX 0xFFFE 
   
#define SPECIES_CRAMORANT_GULPING 0xFFFE 
#define SPECIES_CRAMORANT_GORGING 0xFFFE 
#define SPECIES_TOXTRICITY_LOW_KEY 0xFFFE 
#define SPECIES_SINISTEA_CHIPPED 0xFFFE 
#define SPECIES_POLTEAGEIST_CHIPPED 0xFFFE 
#define SPECIES_ALCREMIE_BERRY 0xFFFE 
#define SPECIES_ALCREMIE_CLOVER 0xFFFE 
#define SPECIES_ALCREMIE_FLOWER 0xFFFE 
#define SPECIES_ALCREMIE_LOVE 0xFFFE 
#define SPECIES_ALCREMIE_RIBBON 0xFFFE 
#define SPECIES_ALCREMIE_STAR 0xFFFE 
#define SPECIES_EISCUE_NOICE 0xFFFE 
#define SPECIES_INDEEDEE_FEMALE 0xFFFE 
#define SPECIES_MORPEKO_HANGRY 0xFFFE 
#define SPECIES_ZACIAN_CROWNED 0xFFFE 
#define SPECIES_ZAMAZENTA_CROWNED 0xFFFE 
#define SPECIES_URSHIFU_RAPID 0xFFFE 
   
#define SPECIES_MEOWTH_G 0xFFFE 
   
#define SPECIES_SLOWPOKE_G 0xFFFE 
#define SPECIES_SLOWBRO_G 0xFFFE 
#define SPECIES_FARFETCHD_G 0xFFFE 
#define SPECIES_KOFFING_G 0xFFFE 
   
#define SPECIES_MR_MIME_G 0xFFFE 
#define SPECIES_ARTICUNO_G 0xFFFE 
#define SPECIES_ZAPDOS_G 0xFFFE 
#define SPECIES_MOLTRES_G 0xFFFE 
#define SPECIES_SLOWKING_G 0xFFFE 
#define SPECIES_CORSOLA_G 0xFFFE 
#define SPECIES_ZIGZAGOON_G 0xFFFE 
#define SPECIES_LINOONE_G 0xFFFE 
#define SPECIES_MIME_JR_G 0xFFFE 
#define SPECIES_DARUMAKA_G 0xFFFE 
#define SPECIES_DARMANITAN_G 0xFFFE 
#define SPECIES_DARMANITAN_G_ZEN 0xFFFE 
#define SPECIES_STUNFISK_G 0xFFFE 
   
#define SPECIES_VENUSAUR_GIGA 0xFFFE 
#define SPECIES_CHARIZARD_GIGA 0xFFFE 
#define SPECIES_BLASTOISE_GIGA 0xFFFE 
#define SPECIES_BUTTERFREE_GIGA 0xFFFE 
#define SPECIES_PIKACHU_GIGA 0xFFFE 
#define SPECIES_MEOWTH_GIGA 0xFFFE 
#define SPECIES_MACHAMP_GIGA 0xFFFE 
#define SPECIES_GENGAR_GIGA 0xFFFE 
#define SPECIES_KINGLER_GIGA 0xFFFE 
#define SPECIES_LAPRAS_GIGA 0xFFFE 
#define SPECIES_EEVEE_GIGA 0xFFFE 
#define SPECIES_SNORLAX_GIGA 0xFFFE 
#define SPECIES_GARBODOR_GIGA 0xFFFE 
#define SPECIES_MELMETAL_GIGA 0xFFFE 
#define SPECIES_RILLABOOM_GIGA 0xFFFE 
#define SPECIES_CINDERACE_GIGA 0xFFFE 
#define SPECIES_INTELEON_GIGA 0xFFFE 
#define SPECIES_CORVIKNIGHT_GIGA 0xFFFE 
#define SPECIES_ORBEETLE_GIGA 0xFFFE 
#define SPECIES_DREDNAW_GIGA 0xFFFE 
#define SPECIES_COALOSSAL_GIGA 0xFFFE 
#define SPECIES_FLAPPLE_GIGA 0xFFFE 
#define SPECIES_APPLETUN_GIGA 0xFFFE 
#define SPECIES_SANDACONDA_GIGA 0xFFFE 
#define SPECIES_TOXTRICITY_GIGA 0xFFFE 
#define SPECIES_TOXTRICITY_LOW_KEY_GIGA 0xFFFE 
#define SPECIES_CENTISKORCH_GIGA 0xFFFE 
#define SPECIES_HATTERENE_GIGA 0xFFFE 
#define SPECIES_GRIMMSNARL_GIGA 0xFFFE 
#define SPECIES_ALCREMIE_GIGA 0xFFFE 
#define SPECIES_COPPERAJAH_GIGA 0xFFFE 
#define SPECIES_DURALUDON_GIGA 0xFFFE 
#define SPECIES_URSHIFU_SINGLE_GIGA 0xFFFE 
#define SPECIES_URSHIFU_RAPID_GIGA 0xFFFE 
//end null entries

#define NUM_SPECIES (ARCEUS_FINAL + 1)
