#pragma once

enum MoveTutors
{
	TUTOR00_FIRE_PUNCH,
	TUTOR01_ICE_PUNCH,
	TUTOR02_THUNDER_PUNCH,
	TUTOR03_SNORE,
	TUTOR04_HEAL_BELL,
	TUTOR05_ELECTROWEB,
	TUTOR06_LOW_KICK,
	TUTOR07_UPROAR,
	TUTOR08_BIND,
	TUTOR09_HELPING_HAND,
	TUTOR10_BLOCK,
	TUTOR11_WORRY_SEED,
	TUTOR12_COVET,
	TUTOR13_BUG_BITE,
	TUTOR14_SNATCH,
	TUTOR15_SPITE,
	TUTOR16_AFTER_YOU,
	TUTOR17_SYNTHESIS,
	TUTOR18_SIGNAL_BEAM,
	TUTOR19_GRAVITY,
	TUTOR20_IRON_DEFENSE,
	TUTOR21_TELEKINESIS,
	TUTOR22_MAGNET_RISE,
	TUTOR23_BOUNCE,
	TUTOR24_ROLE_PLAY,
	TUTOR25_IRON_HEAD,
	TUTOR26_AQUA_TAIL,
	TUTOR27_PAIN_SPLIT,
	TUTOR28_TAILWIND,
	TUTOR29_ENDEAVOR,
	TUTOR30_ICY_WIND,
	TUTOR31_ZEN_HEADBUTT,
	TUTOR32_SEED_BOMB,
	TUTOR33_LASER_FOCUS,
	TUTOR34_TRICK,
	TUTOR35_DRILL_RUN,
	TUTOR36_MAGIC_COAT,
	TUTOR37_MAGIC_ROOM,
	TUTOR38_WONDER_ROOM,
	TUTOR39_LIQUIDATION,
	TUTOR40_GASTRO_ACID,
	TUTOR41_FOUL_PLAY,
	TUTOR42_SUPER_FANG,
	TUTOR43_OUTRAGE,
	TUTOR44_SKY_ATTACK,
	TUTOR45_THROAT_CHOP,
	TUTOR46_STOMPING_TANTRUM,
	TUTOR47_EARTH_POWER,
	TUTOR48_GUNK_SHOT,
	TUTOR49_DUAL_CHOP,
	TUTOR50_HEAT_WAVE,
	TUTOR51_HYPER_VOICE,
	TUTOR52_SUPERPOWER,
	TUTOR53_KNOCK_OFF,
	TUTOR54_PSYCH_UP,
	TUTOR55_VACUUM_WAVE,
	TUTOR56_LAST_RESORT,
	TUTOR57_CONFIDE,
	TUTOR58_GRASS_PLEDGE,
	TUTOR59_FIRE_PLEDGE,
	TUTOR60_WATER_PLEDGE,
	TUTOR61_FRENZY_PLANT,
	TUTOR62_BLAST_BURN,
	TUTOR63_HYDRO_CANNON,
};

//Special Move Tutors - Not in Table
//Numbers in comments are ideal numbers (if NUM_MOVE_TUTORS is 64)
enum SpecialMoveTutors
{
	TUTOR_SPECIAL_DRACO_METEOR = NUM_MOVE_TUTORS,	//64
	TUTOR_SPECIAL_SECRET_SWORD,						//65 - Keldeo only
	TUTOR_SPECIAL_RELIC_SONG,						//66 - Meloetta only
	TUTOR_SPECIAL_VOLT_TACKLE,						//67 - Pikachu only
	TUTOR_SPECIAL_DRAGON_ASCENT,					//68 - Rayquaza only
	TUTOR_SPECIAL_THOUSAND_ARROWS,					//69 - Zygarde only
	TUTOR_SPECIAL_THOUSAND_WAVES,					//70 - Zygarde only
	TUTOR_SPECIAL_CORE_ENFORCER,					//71 - Zygarde only
};
