#include "../config.h"
#include "../../include/global.h"
#include "../../include/new/catching.h"
#include "../../include/new/frontier.h"
#include "../../include/constants/moves.h"
#include "../../include/constants/species.h"
#include "../../include/constants/items.h"
#include "../../include/constants/trainer_classes.h"

#ifdef UNBOUND
const struct BattleTowerSpread gSpecialTowerSpread_Palmer1[] =
{
	{
		.species = SPECIES_MILOTIC,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Competitive
		.item = ITEM_SHELL_BELL,
		.moves =
		{
			MOVE_SURF,
			MOVE_ICEBEAM,
			MOVE_HYPNOSIS,
			MOVE_ATTRACT,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_MILOTIC,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //Marvel Scale
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_SURF,
			MOVE_TOXIC,
			MOVE_AQUARING,
			MOVE_RECOVER,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_RHYPERIOR,
		.nature = NATURE_BRAVE,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 0,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 252,
		.defEv = 4,
		.ability = FRONTIER_ABILITY_2, //Solid Rock
		.item = ITEM_FOCUS_SASH,
		.moves =
		{
			MOVE_REVERSAL,
			MOVE_PAYBACK,
			MOVE_METALBURST,
			MOVE_HORNDRILL,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_RHYPERIOR,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_2, //Solid Rock
		.item = ITEM_ROCKIUM_Z,
		.moves =
		{
			MOVE_EARTHQUAKE,
			MOVE_STONEEDGE,
			MOVE_DRAGONRUSH,
			MOVE_POISONJAB,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_DRAGONITE,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Multiscale
		.item = ITEM_DRAGONIUM_Z,
		.moves =
		{
			MOVE_DRAGONRUSH,
			MOVE_EARTHQUAKE,
			MOVE_IRONTAIL,
			MOVE_DRAGONDANCE,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_DRAGONITE,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Multiscale
		.item = ITEM_SALAC_BERRY,
		.moves =
		{
			MOVE_DRAGONPULSE,
			MOVE_THUNDER,
			MOVE_ICEBEAM,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_STARAPTOR,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Reckless
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_BRAVEBIRD,
			MOVE_CLOSECOMBAT,
			MOVE_PURSUIT,
			MOVE_FINALGAMBIT,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_STARAPTOR,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Reckless
		.item = ITEM_FLYINIUM_Z,
		.moves =
		{
			MOVE_BRAVEBIRD,
			MOVE_DOUBLEEDGE,
			MOVE_FEATHERDANCE,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_VESPIQUEN,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Unnerve
		.item = ITEM_QUICK_CLAW,
		.moves =
		{
			MOVE_TOXIC,
			MOVE_DEFENDORDER,
			MOVE_HEALORDER,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_VESPIQUEN,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //Pressure
		.item = ITEM_NORMALIUM_Z,
		.moves =
		{
			MOVE_ATTACKORDER,
			MOVE_POWERGEM,
			MOVE_CONFUSERAY,
			MOVE_CAPTIVATE,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_BRONZONG,
		.nature = NATURE_SASSY,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 0,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_2, //Heatproof
		.item = ITEM_FLAME_ORB,
		.moves =
		{
			MOVE_PSYSHOCK,
			MOVE_HEALBLOCK,
			MOVE_TRICK,
			MOVE_STEALTHROCK,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_BRONZONG,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN, //Heavy Metal
		.item = ITEM_LIGHT_CLAY,
		.moves =
		{
			MOVE_HEAVYSLAM,
			MOVE_HYPNOSIS,
			MOVE_REFLECT,
			MOVE_LIGHTSCREEN,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
};

const struct BattleTowerSpread gSpecialTowerSpread_Palmer2[] =
{
	{
		.species = SPECIES_REGIGIGAS,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //Slow Start
		.item = ITEM_BRIGHT_POWDER,
		.moves =
		{
			MOVE_CRUSHGRIP,
			MOVE_DRAINPUNCH,
			MOVE_ENDURE,
			MOVE_THUNDERWAVE,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_REGIGIGAS,
		.nature = NATURE_CAREFUL,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //Slow Start
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_DRAINPUNCH,
			MOVE_TOXIC,
			MOVE_SWAGGER,
			MOVE_GRAVITY,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_HEATRAN,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //Flash Fire
		.item = ITEM_FIRIUM_Z,
		.moves =
		{
			MOVE_MAGMASTORM,
			MOVE_FLASHCANNON,
			MOVE_EARTHPOWER,
			MOVE_DARKPULSE,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_HEATRAN,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.spAtkEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //Flash Fire
		.item = ITEM_AIR_BALLOON,
		.moves =
		{
			MOVE_LAVAPLUME,
			MOVE_FLASHCANNON,
			MOVE_METALSOUND,
			MOVE_STEALTHROCK,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_CRESSELIA,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //Levitate
		.item = ITEM_LIGHT_CLAY,
		.moves =
		{
			MOVE_MOONBLAST,
			MOVE_MOONLIGHT,
			MOVE_REFLECT,
			MOVE_LIGHTSCREEN,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_CRESSELIA,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 4,
		.defEv = 252,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_1, //Levitate
		.item = ITEM_PSYCHIUM_Z,
		.moves =
		{
			MOVE_PSYSHOCK,
			MOVE_MOONBLAST,
			MOVE_CALMMIND,
			MOVE_MOONLIGHT,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_TYRANITAR,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN, //Unnerve
		.item = ITEM_CHOPLE_BERRY,
		.moves =
		{
			MOVE_STONEEDGE,
			MOVE_CRUNCH,
			MOVE_EARTHQUAKE,
			MOVE_DRAGONDANCE,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_TYRANITAR,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //Sand Stream
		.item = ITEM_TYRANITARITE,
		.moves =
		{
			MOVE_STONEEDGE,
			MOVE_PAYBACK,
			MOVE_EARTHQUAKE,
			MOVE_ICEFANG,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_ABOMASNOW,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //Snow Warning
		.item = ITEM_BIG_ROOT,
		.moves =
		{
			MOVE_FROSTBREATH,
			MOVE_LEECHSEED,
			MOVE_INGRAIN,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_ABOMASNOW,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_1, //Snow Warning
		.item = ITEM_ABOMASITE,
		.moves =
		{
			MOVE_BLIZZARD,
			MOVE_GIGADRAIN,
			MOVE_FOCUSBLAST,
			MOVE_ICESHARD,
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_CELESTEELA,
		.nature = NATURE_BRAVE,
		.hpIv = 30,
		.atkIv = 31,
		.defIv = 30,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 252,
		.spdEv = 4,
		.ability = FRONTIER_ABILITY_1, //Beast Boost
		.item = ITEM_ASSAULT_VEST,
		.moves =
		{
			MOVE_HEAVYSLAM,
			MOVE_EARTHQUAKE,
			MOVE_FLAMETHROWER,
			MOVE_HIDDENPOWER, //Ice
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
	{
		.species = SPECIES_CELESTEELA,
		.nature = NATURE_MODEST,
		.hpIv = 30,
		.atkIv = 31,
		.defIv = 30,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spdEv = 4,
		.ability = FRONTIER_ABILITY_1, //Beast Boost
		.item = ITEM_FLYINIUM_Z,
		.moves =
		{
			MOVE_FLASHCANNON,
			MOVE_AIRSLASH,
			MOVE_FLAMETHROWER,
			MOVE_HIDDENPOWER, //Ice
		},
		.ball = BALL_TYPE_PREMIER_BALL,
	},
};
	
const struct BattleTowerSpread gSpecialTowerSpread_Cynthia[] =
{
	{
		.species = SPECIES_MILOTIC,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_2, //Competitive
		.item = ITEM_WIDE_LENS,
		.moves =
		{
			MOVE_HYDROPUMP,
			MOVE_BLIZZARD,
			MOVE_MIRRORCOAT,
			MOVE_RECOVER,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_MILOTIC,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //Marvel Scale
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_SURF,
			MOVE_ICEBEAM,
			MOVE_SLEEPTALK,
			MOVE_REST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_GARCHOMP,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.defEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Rough Skin
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_EARTHQUAKE,
			MOVE_CRUNCH,
			MOVE_FIREFANG,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_GARCHOMP,
		.nature = NATURE_CAREFUL,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 4,
		.defEv = 252,
		.ability = FRONTIER_ABILITY_1, //Sand Veil
		.item = ITEM_GARCHOMPITE,
		.moves =
		{
			MOVE_DRAGONCLAW,
			MOVE_EARTHQUAKE,
			MOVE_STONEEDGE,
			MOVE_SANDSTORM,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_TOGEKISS,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 4,
		.defEv = 128,
		.spAtkEv = 252,
		.spdEv = 128,
		.ability = FRONTIER_ABILITY_2, //Serene Grace
		.item = ITEM_KINGS_ROCK,
		.moves =
		{
			MOVE_AIRSLASH,
			MOVE_SHADOWBALL,
			MOVE_GRASSKNOT,
			MOVE_THUNDERWAVE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_TOGEKISS,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_2, //Serene Grace
		.item = ITEM_EXPERT_BELT,
		.moves =
		{
			MOVE_DAZZLINGGLEAM,
			MOVE_AIRSLASH,
			MOVE_AURASPHERE,
			MOVE_GRASSKNOT,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_SPIRITOMB,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN, //Infiltrator
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_SHADOWSNEAK,
			MOVE_WILLOWISP,
			MOVE_SWAGGER,
			MOVE_PSYCHUP,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_SPIRITOMB,
		.nature = NATURE_CAREFUL,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Infiltrator
		.item = ITEM_CUSTAP_BERRY,
		.moves =
		{
			MOVE_SUCKERPUNCH,
			MOVE_PAINSPLIT,
			MOVE_WILLOWISP,
			MOVE_SUBSTITUTE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_LUCARIO,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Justified
		.item = ITEM_LUCARIONITE,
		.moves =
		{
			MOVE_CLOSECOMBAT,
			MOVE_BULLETPUNCH,
			MOVE_BLAZEKICK,
			MOVE_ROCKSLIDE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_LUCARIO,
		.nature = NATURE_NAIVE,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 56,
		.spAtkEv = 200,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_2, //Inner Focus
		.item = ITEM_WEAKNESS_POLICY,
		.moves =
		{
			MOVE_AURASPHERE,
			MOVE_DRAGONPULSE,
			MOVE_STONEEDGE,
			MOVE_EXTREMESPEED,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_EELEKTROSS,
		.nature = NATURE_BRAVE,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 252,
		.defEv = 200,
		.spAtkEv = 56,
		.ability = FRONTIER_ABILITY_1, //Levitate
		.item = ITEM_ROCKY_HELMET,
		.moves =
		{
			MOVE_WILDCHARGE,
			MOVE_DRAGONCLAW,
			MOVE_CRUNCH,
			MOVE_FLAMETHROWER,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_ROSERADE,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //Natural Cure
		.item = ITEM_WHITE_HERB,
		.moves =
		{
			MOVE_LEAFSTORM,
			MOVE_SLUDGEBOMB,
			MOVE_SHADOWBALL,
			MOVE_SLEEPPOWDER,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
};

const struct BattleTowerSpread gMiddleCupTowerSpread_Cynthia[] =
{
	{
		.species = SPECIES_GABITE,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Rough Skin
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_EARTHQUAKE,
			MOVE_STONEEDGE,
			MOVE_FIREFANG,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_TOGETIC,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Super Luck
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_DAZZLINGGLEAM,
			MOVE_YAWN,
			MOVE_WISH,
			MOVE_HEALBELL,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_EELEKTRIK,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //Levitate
		.item = ITEM_BINDING_BAND,
		.moves =
		{
			MOVE_ACIDSPRAY,
			MOVE_BIND,
			MOVE_REST,
			MOVE_TOXIC,	
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_ROSELIA,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 248,
		.spDefEv = 236,
		.spdEv = 24,
		.ability = FRONTIER_ABILITY_1, //Natural Cure
		.item = ITEM_QUICK_CLAW,
		.moves =
		{
			MOVE_GIGADRAIN,
			MOVE_SLUDGEBOMB,
			MOVE_SYNTHESIS,
			MOVE_SPIKES,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_LUXIO,
		.nature = NATURE_RELAXED,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 156,
		.atkEv = 76,
		.defEv = 244,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //Intimidate
		.item = ITEM_SITRUS_BERRY,
		.moves =
		{
			MOVE_WILDCHARGE,
			MOVE_VOLTSWITCH,
			MOVE_THUNDERWAVE,
			MOVE_EERIEIMPULSE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_DUSCLOPS,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 124,
		.spAtkEv = 132,
		.ability = FRONTIER_ABILITY_1, //Pressure
		.item = ITEM_EVIOLITE,
		.moves =
		{
			MOVE_DARKPULSE,
			MOVE_WILLOWISP,
			MOVE_CALMMIND,
			MOVE_REST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
};

const struct BattleTowerSpread gLittleCupTowerSpread_Cynthia[] =
{
	{
		.species = SPECIES_FEEBAS,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.defEv = 40,
		.spdEv = 196,
		.spAtkEv = 196,
		.spDefEv = 76,
		.ability = FRONTIER_ABILITY_HIDDEN, //Adaptability
		.item = ITEM_BRIGHT_POWDER,
		.moves =
		{
			MOVE_BRINE,
			MOVE_DRAGONPULSE,
			MOVE_MIRRORCOAT,
			MOVE_CONFUSERAY,
		},
	},
	{
		.species = SPECIES_FEEBAS,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 236,
		.spdEv = 196,
		.spDefEv = 76,
		.ability = FRONTIER_ABILITY_HIDDEN, //Adaptability
		.item = ITEM_CHESTO_BERRY,
		.moves =
		{
			MOVE_WATERFALL,
			MOVE_DOUBLEEDGE,
			MOVE_TOXIC,
			MOVE_REST,
		},
	},
	{
		.species = SPECIES_GIBLE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 196,
		.defEv = 076,
		.spDefEv = 236,
		.ability = FRONTIER_ABILITY_HIDDEN, //Rough Skin
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_DRAGONCLAW,
			MOVE_EARTHQUAKE,
			MOVE_SLASH,
			MOVE_PROTECT,
		},
	},
	{
		.species = SPECIES_GIBLE,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Rough Skin
		.item = ITEM_ROCKY_HELMET,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_BODYSLAM,
			MOVE_IRONHEAD,
			MOVE_STEALTHROCK,
		},
	},
	{
		.species = SPECIES_TOGEPI,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.defEv = 236,
		.spAtkEv = 036,
		.spDefEv = 236,
		.ability = FRONTIER_ABILITY_2, //Serene Grace
		.item = ITEM_IAPAPA_BERRY,
		.moves =
		{
			MOVE_ANCIENTPOWER,
			MOVE_STOREDPOWER,
			MOVE_MORNINGSUN,
			MOVE_PROTECT,
		},
	},
	{
		.species = SPECIES_TOGEPI,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 252,
		.spdEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN, //Super Luck
		.item = ITEM_ASSAULT_VEST,
		.moves =
		{
			MOVE_RETURN,
			MOVE_ZENHEADBUTT,
			MOVE_ROLLOUT,
			MOVE_PECK,
		},
	},
	{
		.species = SPECIES_EEVEE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.spdEv = 20,
		.spDefEv = 236,
		.ability = FRONTIER_ABILITY_2,
		.item = ITEM_NORMALIUM_Z,
		.moves =
		{
			MOVE_DOUBLEEDGE,
			MOVE_QUICKATTACK,
			MOVE_REFLECT,
			MOVE_WISH,
		},
	},
	{
		.species = SPECIES_EEVEE,
		.nature = NATURE_LONELY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 236,
		.spdEv = 36,
		.spDefEv = 236,
		.ability = FRONTIER_ABILITY_2,
		.item = ITEM_TOXIC_ORB,
		.moves =
		{
			MOVE_FACADE,
			MOVE_QUICKATTACK,
			MOVE_SHADOWBALL,
			MOVE_YAWN,
		},
	},
	{
		.species = SPECIES_RIOLU,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.spdEv = 60,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_HIDDEN, //Prankster
		.item = ITEM_WIKI_BERRY,
		.moves =
		{
			MOVE_BRICKBREAK,
			MOVE_BLAZEKICK,
			MOVE_BULLETPUNCH,
			MOVE_TOXIC,
		},
	},
	{
		.species = SPECIES_RIOLU,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 30,
		.defIv = 31,
		.spdIv = 30,
		.spAtkIv = 30,
		.spDefIv = 31,
		.hpEv = 36,
		.defEv = 36,
		.spAtkEv = 240,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_HIDDEN, //Prankster
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_AURASPHERE,
			MOVE_HIDDENPOWER, //Fire
			MOVE_VACUUMWAVE,
			MOVE_DOUBLETEAM,
		},
	},
	{
		.species = SPECIES_TYNAMO,
		.nature = NATURE_LONELY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 236,
		.spAtkEv = 76,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_1, //Levitate
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_CHARGEBEAM,
			MOVE_TACKLE,
			MOVE_SPARK,
			MOVE_THUNDERWAVE,
		},
	},
};

const struct BattleTowerSpread gSpecialTowerSpread_Skeli[] =
{
	{
		.species = SPECIES_MAGMORTAR,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Vital Spirit
		.item = ITEM_NORMALIUM_Z,
		.moves =
		{
			MOVE_FLAREBLITZ,
			MOVE_EARTHQUAKE,
			MOVE_MACHPUNCH,
			MOVE_BELLYDRUM,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_MAGMORTAR,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.defEv = 252,
		.spAtkEv = 252,
		.spdEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN, //Vital Spirit
		.item = ITEM_FIRIUM_Z,
		.moves =
		{
			MOVE_FIREBLAST,
			MOVE_THUNDERBOLT,
			MOVE_FOCUSBLAST,
			MOVE_PSYCHIC,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_BRELOOM,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Technician
		.item = ITEM_FOCUS_SASH,
		.moves =
		{
			MOVE_BULLETSEED,
			MOVE_MACHPUNCH,
			MOVE_ROCKTOMB,
			MOVE_SPORE,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_BRELOOM,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 4,
		.defEv = 252,
		.ability = FRONTIER_ABILITY_2, //Poison Heal
		.item = ITEM_TOXIC_ORB,
		.moves =
		{
			MOVE_DRAINPUNCH,
			MOVE_LEECHSEED,
			MOVE_SPORE,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_CINCCINO,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.defEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Skill Link
		.item = ITEM_KINGS_ROCK,
		.moves =
		{
			MOVE_TAILSLAP,
			MOVE_ROCKBLAST,
			MOVE_BULLETSEED,
			MOVE_AQUATAIL,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_CINCCINO,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.defEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Skill Link
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_TAILSLAP,
			MOVE_ROCKBLAST,
			MOVE_KNOCKOFF,
			MOVE_UTURN,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_SWALOT,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_2, //Sticky Hold
		.item = ITEM_BLACK_SLUDGE,
		.moves =
		{
			MOVE_ICEBEAM,
			MOVE_INFESTATION,
			MOVE_YAWN,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_SWALOT,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_2, //Sticky Hold
		.item = ITEM_BINDING_BAND,
		.moves =
		{
			MOVE_ICEBEAM,
			MOVE_INFESTATION,
			MOVE_TOXIC,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_CLAYDOL,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //Levitate
		.item = ITEM_LIGHT_CLAY,
		.moves =
		{
			MOVE_ICEBEAM,
			MOVE_STEALTHROCK,
			MOVE_REFLECT,
			MOVE_LIGHTSCREEN,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_CLAYDOL,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //Levitate
		.item = ITEM_COLBUR_BERRY,
		.moves =
		{
			MOVE_PSYCHIC,
			MOVE_RAPIDSPIN,
			MOVE_STEALTHROCK,
			MOVE_REFLECT,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_SWAMPERT,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //Torrent
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_WATERFALL,
			MOVE_EARTHQUAKE,
			MOVE_AVALANCHE,
			MOVE_SUBSTITUTE,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_SWAMPERT,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Damp
		.item = ITEM_SWAMPERTITE,
		.moves =
		{
			MOVE_WATERFALL,
			MOVE_EARTHQUAKE,
			MOVE_ICEPUNCH,
			MOVE_RAINDANCE,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_BEEDRILL,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //Swarm
		.item = ITEM_BEEDRILLITE,
		.moves =
		{
			MOVE_POISONJAB,
			MOVE_XSCISSOR,
			MOVE_DRILLRUN,
			MOVE_SWORDSDANCE,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_BEEDRILL,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.spDefEv = 252,
		.spdEv = 4,
		.ability = FRONTIER_ABILITY_1, //Swarm
		.item = ITEM_BEEDRILLITE,
		.moves =
		{
			MOVE_POISONJAB,
			MOVE_UTURN,
			MOVE_BRICKBREAK,
			MOVE_TAILWIND,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_HOOPA_UNBOUND,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.defEv = 252,
		.spdEv = 4,
		.ability = FRONTIER_ABILITY_1, //Magician
		.item = ITEM_DARKINIUM_Z,
		.moves =
		{
			MOVE_HYPERSPACEFURY,
			MOVE_ZENHEADBUTT,
			MOVE_DRAINPUNCH,
			MOVE_THUNDERWAVE,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_HOOPA_UNBOUND,
		.nature = NATURE_JOLLY,
		.hpIv = 30,
		.atkIv = 31,
		.defIv = 30,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.defEv = 4,
		.spAtkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //Magician
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_HYPERSPACEHOLE,
			MOVE_DARKPULSE,
			MOVE_ENERGYBALL,
			MOVE_HIDDENPOWER, //Ice
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
};

const struct BattleTowerSpread gMiddleCupTowerSpread_Skeli[] =
{
	{
		.species = SPECIES_MAGMAR,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Vital Spirit
		.item = ITEM_NORMALIUM_Z,
		.moves =
		{
			MOVE_FLAREBLITZ,
			MOVE_THUNDERPUNCH,
			MOVE_MACHPUNCH,
			MOVE_BELLYDRUM,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_MAGMAR,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 30,
		.spDefIv = 31,
		.defEv = 252,
		.spAtkEv = 252,
		.spdEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN, //Vital Spirit
		.item = ITEM_FIRIUM_Z,
		.moves =
		{
			MOVE_FIREBLAST,
			MOVE_FOCUSBLAST,
			MOVE_PSYCHIC,
			MOVE_HIDDENPOWER, //Electric
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_MARSHTOMP,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //Torrent
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_WATERFALL,
			MOVE_EARTHQUAKE,
			MOVE_AVALANCHE,
			MOVE_SUBSTITUTE,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_MARSHTOMP,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN, //Damp
		.item = ITEM_BRIGHT_POWDER,
		.moves =
		{
			MOVE_WHIRLPOOL,
			MOVE_ANCIENTPOWER,
			MOVE_YAWN,
			MOVE_STEALTHROCK,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_KAKUNA,
		.nature = NATURE_RELAXED,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //Shed Skin
		.item = ITEM_SITRUS_BERRY,
		.moves =
		{
			MOVE_BUGBITE,
			MOVE_ELECTROWEB,
			MOVE_STRINGSHOT,
			MOVE_IRONDEFENSE,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_FLOETTE_BLUE,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1, //Flower Veil
		.item = ITEM_QUICK_CLAW,
		.moves =
		{
			MOVE_MOONBLAST,
			MOVE_TOXIC,
			MOVE_WISH,
			MOVE_PROTECT,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_FLOETTE_YELLOW,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //Flower Veil
		.item = ITEM_EVIOLITE,
		.moves =
		{
			MOVE_MOONBLAST,
			MOVE_WISH,
			MOVE_MISTYTERRAIN,
			MOVE_LUCKYCHANT,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_MAGNETON,
		.nature = NATURE_QUIET,
		.hpIv = 31,
		.atkIv = 30,
		.defIv = 31,
		.spdIv = 0,
		.spAtkIv = 31,
		.spDefIv = 30,
		.hpEv = 252,
		.defEv = 4,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Analytic
		.item = ITEM_ASSAULT_VEST,
		.moves =
		{
			MOVE_THUNDERBOLT,
			MOVE_FLASHCANNON,
			MOVE_TRIATTACK,
			MOVE_HIDDENPOWER, //Fire
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_MAGNETON,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_2, //Sturdy
		.item = ITEM_LIGHT_CLAY,
		.moves =
		{
			MOVE_DISCHARGE,
			MOVE_THUNDERWAVE,
			MOVE_REFLECT,
			MOVE_LIGHTSCREEN,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_SHELGON,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.defEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Overcoat
		.item = ITEM_EXPERT_BELT,
		.moves =
		{
			MOVE_DRAGONCLAW,
			MOVE_ZENHEADBUTT,
			MOVE_ROCKSLIDE,
			MOVE_SHADOWCLAW,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
	{
		.species = SPECIES_SHELGON,
		.nature = NATURE_CAREFUL,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Overcoat
		.item = ITEM_EVIOLITE,
		.moves =
		{
			MOVE_DRAGONRAGE,
			MOVE_TOXIC,
			MOVE_IRONDEFENSE,
			MOVE_REST,
		},
		.ball = BALL_TYPE_CHERISH_BALL,
	},
};

const struct BattleTowerSpread gLittleCupTowerSpread_Skeli[] =
{
	{
		.species = SPECIES_MAGBY,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 20,
		.atkEv = 236,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //Flame Body
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_FIREPUNCH,
			MOVE_THUNDERPUNCH,
			MOVE_POWERUPPUNCH,
			MOVE_BODYSLAM,
		},
	},
	{
		.species = SPECIES_MAGBY,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 60,
		.spdEv = 252,
		.spAtkEv = 196,
		.ability = FRONTIER_ABILITY_HIDDEN, //Vital Spirit
		.item = ITEM_FIRIUM_Z,
		.moves =
		{
			MOVE_FIREBLAST,
			MOVE_PSYCHIC,
			MOVE_SUBSTITUTE,
			MOVE_REST,
		},
	},
	{
		.species = SPECIES_SHROOMISH,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 196,
		.defEv = 116,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_2, //Poison Heal
		.item = ITEM_TOXIC_ORB,
		.moves =
		{
			MOVE_BULLETSEED,
			MOVE_DRAINPUNCH,
			MOVE_SWORDSDANCE,
			MOVE_SPORE,
		},
	},
	{
		.species = SPECIES_SHROOMISH,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 116,
		.atkEv = 196,
		.spDefEv = 36,
		.spdEv = 156,
		.ability = FRONTIER_ABILITY_HIDDEN, //Quick Feet
		.item = ITEM_TOXIC_ORB,
		.moves =
		{
			MOVE_SEEDBOMB,
			MOVE_DOUBLEEDGE,
			MOVE_RETURN,
			MOVE_SUBSTITUTE,
		},
	},
	{
		.species = SPECIES_MINCCINO,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 196,
		.defEv = 036,
		.spdEv = 236,
		.spDefEv = 036,
		.ability = FRONTIER_ABILITY_HIDDEN, //Skill Link
		.item = ITEM_KINGS_ROCK,
		.moves =
		{
			MOVE_TAILSLAP,
			MOVE_AQUATAIL,
			MOVE_KNOCKOFF,
			MOVE_THUNDERWAVE,
		},
	},
	{
		.species = SPECIES_MINCCINO,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 196,
		.defEv = 036,
		.spdEv = 236,
		.spDefEv = 036,
		.ability = FRONTIER_ABILITY_1, //Cute Charm
		.item = ITEM_ROCKY_HELMET,
		.moves =
		{
			MOVE_RETURN,
			MOVE_GUNKSHOT,
			MOVE_UTURN,
			MOVE_TOXIC,
		},
	},
	{
		.species = SPECIES_GULPIN,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 196,
		.defEv = 12,
		.spAtkEv = 12,
		.spDefEv = 252,
		.spdEv = 36,
		.ability = FRONTIER_ABILITY_2, //Sticky Hold
		.item = ITEM_BLACK_SLUDGE,
		.moves =
		{
			MOVE_VENOSHOCK,
			MOVE_PAINSPLIT,
			MOVE_TOXIC,
			MOVE_AMNESIA,
		},
	},
	{
		.species = SPECIES_GULPIN,
		.nature = NATURE_SASSY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 196,
		.atkEv = 12,
		.defEv = 12,
		.spDefEv = 252,
		.spdEv = 36,
		.ability = FRONTIER_ABILITY_HIDDEN, //Gluttony
		.item = ITEM_BINDING_BAND,
		.moves =
		{
			MOVE_GUNKSHOT,
			MOVE_INFESTATION,
			MOVE_REST,
			MOVE_PROTECT,
		},
	},
	{
		.species = SPECIES_BALTOY,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 36,
		.atkEv = 36,
		.defEv = 236,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_1, //Levitate
		.item = ITEM_LIGHT_CLAY,
		.moves =
		{
			MOVE_EARTHQUAKE,
			MOVE_STEALTHROCK,
			MOVE_REFLECT,
			MOVE_LIGHTSCREEN,
		},
	},
	{
		.species = SPECIES_BALTOY,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 36,
		.spAtkEv = 196,
		.spDefEv = 036,
		.spdEv = 236,
		.ability = FRONTIER_ABILITY_1, //Levitate
		.item = ITEM_PSYCHIUM_Z,
		.moves =
		{
			MOVE_EARTHPOWER,
			MOVE_PSYCHIC,
			MOVE_SHADOWBALL,
			MOVE_ROCKPOLISH,
		},
	},
	{
		.species = SPECIES_MUDKIP,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 196,
		.defEv = 196,
		.spDefEv = 116,
		.ability = FRONTIER_ABILITY_1, //Torrent
		.item = ITEM_WATER_GEM,
		.moves =
		{
			MOVE_AQUATAIL,
			MOVE_AVALANCHE,
			MOVE_RETURN,
			MOVE_TOXIC,
		},
	},
	{
		.species = SPECIES_MUDKIP,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 196,
		.spAtkEv = 116,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_1, //Torent
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_SCALD,
			MOVE_TOXIC,
			MOVE_ATTRACT,
			MOVE_SUBSTITUTE,
		},
	},
};

const struct BattleTowerSpread gSpecialTowerSpread_Golche[] =
{
	{
		.species = SPECIES_GALVANTULA,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //Compoundeyes
		.item = ITEM_FOCUS_SASH,
		.moves =
		{
			MOVE_THUNDER,
			MOVE_BUGBUZZ,
			MOVE_THUNDERWAVE,
			MOVE_STICKYWEB,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_GALVANTULA,
		.nature = NATURE_TIMID,
		.hpIv = 30,
		.atkIv = 30,
		.defIv = 30,
		.spdIv = 31,
		.spAtkIv = 30,
		.spDefIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //Compoundeyes
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_THUNDER,
			MOVE_BUGBUZZ,
			MOVE_GIGADRAIN,
			MOVE_HIDDENPOWER, //Water
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_FERALIGATR,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.spdEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN, //Sheer Force
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_WATERFALL,
			MOVE_ICEPUNCH,
			MOVE_EARTHQUAKE,
			MOVE_DRAGONDANCE,
		},
		.ball = BALL_TYPE_POKE_BALL,
	},
	{
		.species = SPECIES_FERALIGATR,
		.nature = NATURE_BRAVE,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 244,
		.atkEv = 114,
		.defEv = 148,
		.ability = FRONTIER_ABILITY_HIDDEN, //Sheer Force
		.item = ITEM_LUM_BERRY,
		.moves =
		{
			MOVE_WATERFALL,
			MOVE_AVALANCHE,
			MOVE_SLEEPTALK,
			MOVE_REST,
		},
		.ball = BALL_TYPE_POKE_BALL,
	},
	{
		.species = SPECIES_GENGAR,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //Levitate
		.item = ITEM_FOCUS_SASH,
		.moves =
		{
			MOVE_SHADOWBALL,
			MOVE_SLUDGEBOMB,
			MOVE_DISABLE,
			MOVE_DESTINYBOND,
		},
		.ball = BALL_TYPE_DUSK_BALL,
	},
	{
		.species = SPECIES_GENGAR,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //Levitate
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_SHADOWBALL,
			MOVE_SLUDGEBOMB,
			MOVE_THUNDERBOLT,
			MOVE_DAZZLINGGLEAM,
		},
		.ball = BALL_TYPE_DUSK_BALL,
	},
	{
		.species = SPECIES_HYDREIGON,
		.nature = NATURE_HASTY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 252,
		.spAtkEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //Levitate
		.item = ITEM_DRAGONIUM_Z,
		.moves =
		{
			MOVE_DRACOMETEOR,
			MOVE_CRUNCH,
			MOVE_DRAGONTAIL,
			MOVE_HEADSMASH,
		},
		.ball = BALL_TYPE_DUSK_BALL,
	},
	{
		.species = SPECIES_HYDREIGON,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //Levitate
		.item = ITEM_EXPERT_BELT,
		.moves =
		{
			MOVE_DRAGONPULSE,
			MOVE_DARKPULSE,
			MOVE_FLASHCANNON,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_DUSK_BALL,
	},
	{
		.species = SPECIES_METAGROSS,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.defEv = 160,
		.spdEv = 96,
		.ability = FRONTIER_ABILITY_1, //Clear Body
		.item = ITEM_AIR_BALLOON,
		.moves =
		{
			MOVE_METEORMASH,
			MOVE_ZENHEADBUTT,
			MOVE_ICEPUNCH,
			MOVE_AGILITY,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_METAGROSS,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.defEv = 160,
		.spdEv = 96,
		.ability = FRONTIER_ABILITY_1, //Clear Body
		.item = ITEM_METAGROSSITE,
		.moves =
		{
			MOVE_METEORMASH,
			MOVE_ZENHEADBUTT,
			MOVE_ICEPUNCH,
			MOVE_AGILITY,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_METAGROSS,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //Clear Body
		.item = ITEM_METAGROSSITE,
		.moves =
		{
			MOVE_METEORMASH,
			MOVE_EARTHQUAKE,
			MOVE_BULLETPUNCH,
			MOVE_POWERUPPUNCH,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_CROBAT,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Infiltrator
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_CROSSPOISON,
			MOVE_BRAVEBIRD,
			MOVE_DOUBLEEDGE,
			MOVE_LEECHFANG,
		},
		.ball = BALL_TYPE_DUSK_BALL,
	},
	{
		.species = SPECIES_CROBAT,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //Inner Focus
		.item = ITEM_SCOPE_LENS,
		.moves =
		{
			MOVE_CROSSPOISON,
			MOVE_LEECHFANG,
			MOVE_ZENHEADBUTT,
			MOVE_TOXIC,
		},
		.ball = BALL_TYPE_DUSK_BALL,
	},
};

const struct BattleTowerSpread gMiddleCupTowerSpread_Golche[] =
{
	{
		.species = SPECIES_PIKACHU,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Lightningrod
		.item = ITEM_LIGHT_BALL,
		.moves =
		{
			MOVE_THUNDERBOLT,
			MOVE_SURF,
			MOVE_SIGNALBEAM,
			MOVE_THUNDERWAVE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_PIKACHU,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //Static
		.item = ITEM_PIKANIUM_Z,
		.moves =
		{
			MOVE_VOLTTACKLE,
			MOVE_BRICKBREAK,
			MOVE_KNOCKOFF,
			MOVE_EXTREMESPEED,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_MACHOKE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_2, //No Guard
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_DYNAMICPUNCH,
			MOVE_ROCKSLIDE,
			MOVE_THUNDERPUNCH,
			MOVE_BODYSLAM,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_MACHOKE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1, //Guts
		.item = ITEM_FLAME_ORB,
		.moves =
		{
			MOVE_CROSSCHOP,
			MOVE_EARTHQUAKE,
			MOVE_FACADE,
			MOVE_BULKUP,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_DRAGONAIR,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Marvel Scale
		.item = ITEM_FLAME_ORB,
		.moves =
		{
			MOVE_DRAGONPULSE,
			MOVE_FLAMETHROWER,
			MOVE_THUNDERBOLT,
			MOVE_AGILITY,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_DRAGONAIR,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1, //Shed Skin
		.item = ITEM_DRAGONIUM_Z,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_AQUATAIL,
			MOVE_EXTREMESPEED,
			MOVE_DRAGONDANCE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_CROCONAW,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN, //Sheer Force
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_WATERFALL,
			MOVE_ICEPUNCH,
			MOVE_CRUNCH,
			MOVE_ROCKSLIDE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_CROCONAW,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Sheer Force
		.item = ITEM_EVIOLITE,
		.moves =
		{
			MOVE_WATERFALL,
			MOVE_ICEPUNCH,
			MOVE_CRUNCH,
			MOVE_DRAGONDANCE,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_TOGETIC,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spAtkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_2, //Serene Grace
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_TRIATTACK,
			MOVE_PSYSHOCK,
			MOVE_SIGNALBEAM,
			MOVE_ANCIENTPOWER,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_TOGETIC,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN, //Super Luck
		.item = ITEM_SCOPE_LENS,
		.moves =
		{
			MOVE_DAZZLINGGLEAM,
			MOVE_AIRCUTTER,
			MOVE_HYPERVOICE,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_FLETCHINDER,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Gale Wings
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_FLAMECHARGE,
			MOVE_AERIALACE,
			MOVE_DEFOG,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_FLETCHINDER,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 252,
		.spDefEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN, //Gale Wings
		.item = ITEM_FLYING_GEM,
		.moves =
		{
			MOVE_FLAMECHARGE,
			MOVE_ACROBATICS,
			MOVE_RETURN,
			MOVE_UTURN,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
};

const struct BattleTowerSpread gLittleCupTowerSpread_Golche[] =
{
	{
		.species = SPECIES_AZURILL,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 196,
		.defEv = 116,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_2, //Huge Power
		.item = ITEM_POWER_HERB,
		.moves =
		{
			MOVE_RETURN,
			MOVE_WATERFALL,
			MOVE_BOUNCE,
			MOVE_KNOCKOFF,
		},
		.ball = BALL_TYPE_FRIEND_BALL,
	},
	{
		.species = SPECIES_ARON,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 196,
		.spDefEv = 116,
		.spdEv = 196,
		.ability = FRONTIER_ABILITY_2, //Rock Head
		.item = ITEM_STEELIUM_Z,
		.moves =
		{			
			MOVE_HEADSMASH,
			MOVE_IRONHEAD,
			MOVE_EARTHQUAKE,
			MOVE_ROCKPOLISH,
		},
		.ball = BALL_TYPE_HEAVY_BALL,
	},
	{
		.species = SPECIES_ANORITH,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 236,
		.spDefEv = 36,
		.spdEv = 236,
		.ability = FRONTIER_ABILITY_1, //Battle Armor
		.item = ITEM_BERRY_JUICE,
		.moves =
		{
			MOVE_ROCKSLIDE,
			MOVE_XSCISSOR,
			MOVE_SWORDSDANCE,
			MOVE_ROCKPOLISH,
		},
		.ball = BALL_TYPE_DIVE_BALL,
	},
	{
		.species = SPECIES_BRONZOR,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.defEv = 228,
		.spAtkEv = 4,
		.spDefEv = 228,
		.ability = FRONTIER_ABILITY_1, //Levitate
		.item = ITEM_LIGHT_CLAY,
		.moves =
		{
			MOVE_PSYCHIC,
			MOVE_STEALTHROCK,
			MOVE_REFLECT,
			MOVE_LIGHTSCREEN,
		},
		.ball = BALL_TYPE_HEAVY_BALL,
	},
	{
		.species = SPECIES_CARVANHA,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 196,
		.spDefEv = 36,
		.spdEv = 236,
		.ability = FRONTIER_ABILITY_HIDDEN, //Speed Boost
		.item = ITEM_WATERIUM_Z,
		.moves =
		{
			MOVE_WATERFALL,
			MOVE_CRUNCH,
			MOVE_ZENHEADBUTT,
			MOVE_ICEFANG,
		},
		.ball = BALL_TYPE_NET_BALL,
	},
	{
		.species = SPECIES_CRANIDOS,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 236,
		.spDefEv = 36,
		.spdEv = 212,
		.ability = FRONTIER_ABILITY_1, //Mold Breaker
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_HEADSMASH,
			MOVE_EARTHQUAKE,
			MOVE_THUNDERPUNCH,
			MOVE_FIREPUNCH,
		},
		.ball = BALL_TYPE_DUSK_BALL,
	},
	{
		.species = SPECIES_DRATINI,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 244,
		.spDefEv = 36,
		.spdEv = 196,
		.ability = FRONTIER_ABILITY_1, //Shed Skin
		.item = ITEM_ORAN_BERRY,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_WATERFALL,
			MOVE_EXTREMESPEED,
			MOVE_DRAGONDANCE,
		},
		.ball = BALL_TYPE_DIVE_BALL,
	},
	{
		.species = SPECIES_DRATINI,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 244,
		.spDefEv = 196,
		.spdEv = 36,
		.ability = FRONTIER_ABILITY_1, //Shed Skin
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_WATERFALL,
			MOVE_IRONTAIL,
			MOVE_EXTREMESPEED,
		},
		.ball = BALL_TYPE_DIVE_BALL,
	},
	{
		.species = SPECIES_GLIGAR,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 236,
		.spDefEv = 36,
		.spdEv = 236,
		.ability = FRONTIER_ABILITY_HIDDEN, //Immunity
		.item = ITEM_EVIOLITE,
		.moves =
		{
			MOVE_EARTHQUAKE,
			MOVE_ROCKPOLISH,
			MOVE_SWORDSDANCE,
			MOVE_ROOST,
		},
		.ball = BALL_TYPE_DUSK_BALL,
	},
	{
		.species = SPECIES_PHANPY,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 196,
		.defEv = 116,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_HIDDEN, //Sand Veil
		.item = ITEM_BERRY_JUICE,
		.moves =
		{
			MOVE_EARTHQUAKE,
			MOVE_ROCKSLIDE,
			MOVE_ICESHARD,
			MOVE_STEALTHROCK,
		},
		.ball = BALL_TYPE_GREAT_BALL,
	},
	{
		.species = SPECIES_PORYGON,
		.nature = NATURE_QUIET,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 0,
		.spAtkIv = 31,
		.spDefIv = 31,
		.defEv = 36,
		.spAtkEv = 236,
		.spDefEv = 236,
		.ability = FRONTIER_ABILITY_HIDDEN, //Analytic
		.item = ITEM_ASSAULT_VEST,
		.moves =
		{
			MOVE_TRIATTACK,
			MOVE_THUNDERBOLT,
			MOVE_PSYSHOCK,
			MOVE_SHADOWBALL,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
	{
		.species = SPECIES_PORYGON,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.defEv = 36,
		.spAtkEv = 236,
		.spDefEv = 236,
		.ability = FRONTIER_ABILITY_2, //Download
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_TRIATTACK,
			MOVE_THUNDERBOLT,
			MOVE_PSYSHOCK,
			MOVE_ICEBEAM,
		},
		.ball = BALL_TYPE_ULTRA_BALL,
	},
};

const struct BattleTowerSpread gSpecialTowerSpread_Gail[] =
{
	{
		.species = SPECIES_ARCANINE,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 252,
		.spdEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_FIRIUM_Z,
		.moves =
		{
			MOVE_FLAREBLITZ,
			MOVE_CLOSECOMBAT,
			MOVE_EXTREMESPEED,
			MOVE_OUTRAGE,
		},
	},
	{
		.species = SPECIES_ARCANINE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 252,
		.spdEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_EXPERT_BELT,
		.moves =
		{
			MOVE_FLAMECHARGE,
			MOVE_CRUNCH,
			MOVE_IRONHEAD,
			MOVE_WILDCHARGE,
		},
	},
	{
		.species = SPECIES_ZOROARK,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_DARKPULSE,
			MOVE_EXTRASENSORY,
			MOVE_FLAMETHROWER,
			MOVE_NONE,
		},
	},
	{
		.species = SPECIES_ZOROARK,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_NIGHTDAZE,
			MOVE_SLUDGEBOMB,
			MOVE_SHADOWBALL,
			MOVE_HYPERBEAM,
		},
	},
	{
		.species = SPECIES_HAXORUS,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 252,
		.spdEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_2,
		.item = ITEM_FOCUS_SASH,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_AQUATAIL,
			MOVE_EARTHQUAKE,
			MOVE_SHADOWCLAW,
		},
	},
	{
		.species = SPECIES_HAXORUS,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 252,
		.spdEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_DRAGONIUM_Z,
		.moves =
		{
			MOVE_DRAGONCLAW,
			MOVE_ROCKSLIDE,
			MOVE_XSCISSOR,
			MOVE_DRAGONDANCE,
		},
	},
	{
		.species = SPECIES_DELPHOX,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_NONE,
		.moves =
		{
			MOVE_FIREBLAST,
			MOVE_DAZZLINGGLEAM,
			MOVE_SHADOWBALL,
			MOVE_WILLOWISP,
		},
	},
	{
		.species = SPECIES_DELPHOX,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_PSYCHIC_GEM,
		.moves =
		{
			MOVE_FLAMETHROWER,
			MOVE_PSYSHOCK,
			MOVE_SIGNALBEAM,
			MOVE_SHOCKWAVE,
		},
	},
	{
		.species = SPECIES_AURORUS,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.spAtkEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_ANCIENTPOWER,
			MOVE_FROSTBREATH,
			MOVE_TOXIC,
			MOVE_STEALTHROCK,
		},
	},
	{
		.species = SPECIES_AURORUS,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spAtkEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_RED_CARD,
		.moves =
		{
			MOVE_DISCHARGE,
			MOVE_TOXIC,
			MOVE_CALMMIND,
			MOVE_SUBSTITUTE,
		},
	},
	{
		.species = SPECIES_BLASTOISE,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_DAMP_ROCK,
		.moves =
		{
			MOVE_HYDROPUMP,
			MOVE_AURASPHERE,
			MOVE_RAINDANCE,
			MOVE_SUBSTITUTE,
		},
	},
	{
		.species = SPECIES_BLASTOISE,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_BLASTOISINITE,
		.moves =
		{
			MOVE_SURF,
			MOVE_AURASPHERE,
			MOVE_DARKPULSE,
			MOVE_FLASHCANNON,
		},
	},
	{
		.species = SPECIES_BLASTOISE,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_BLASTOISINITE,
		.moves =
		{
			MOVE_SCALD,
			MOVE_TOXIC,
			MOVE_IRONDEFENSE,
			MOVE_REST,
		},
	},
};

const struct BattleTowerSpread gMiddleCupTowerSpread_Gail[] =
{
	{
		.species = SPECIES_FRAXURE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 248,
		.atkEv = 252,
		.spDefEv = 8,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_ASSAULT_VEST,
		.moves =
		{
			MOVE_DRAGONCLAW,
			MOVE_NIGHTSLASH,
			MOVE_PAYBACK,
			MOVE_STOMPINGTANTRUM,
		},
	},
	{
		.species = SPECIES_FRAXURE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 248,
		.atkEv = 252,
		.spDefEv = 8,
		.ability = FRONTIER_ABILITY_2,
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_RETURN,
			MOVE_XSCISSOR,
			MOVE_SWORDSDANCE,
		},
	},
	{
		.species = SPECIES_BRAIXEN,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.spdEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_NONE,
		.moves =
		{
			MOVE_FIREBLAST,
			MOVE_PSYCHIC,
			MOVE_INCINERATE,
			MOVE_SHOCKWAVE,
		},
	},
	{
		.species = SPECIES_BRAIXEN,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.spAtkEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_FIRE_GEM,
		.moves =
		{
			MOVE_FLAMETHROWER,
			MOVE_PSYCHIC,
			MOVE_WILLOWISP,
			MOVE_SWAGGER,
		},
	},
	{
		.species = SPECIES_WARTORTLE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_IRON_BALL,
		.moves =
		{
			MOVE_AQUAJET,
			MOVE_DOUBLEEDGE,
			MOVE_FLING,
			MOVE_SUBSTITUTE,
		},
	},
	{
		.species = SPECIES_WARTORTLE,
		.nature = NATURE_CAREFUL,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_EVIOLITE,
		.moves =
		{
			MOVE_AQUATAIL,
			MOVE_TOXIC,
			MOVE_IRONDEFENSE,
			MOVE_AQUARING,
		},
	},
	{
		.species = SPECIES_METANG,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_STEELIUM_Z,
		.moves =
		{
			MOVE_METEORMASH,
			MOVE_ZENHEADBUTT,
			MOVE_BULLETPUNCH,
			MOVE_THUNDERPUNCH,
		},
	},
	{
		.species = SPECIES_METANG,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 4,
		.defEv = 252,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_EVIOLITE,
		.moves =
		{
			MOVE_BODYSLAM,
			MOVE_TOXIC,
			MOVE_STEALTHROCK,
			MOVE_REST,
		},
	},
	{
		.species = SPECIES_SLIGGOO,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_DRAGONPULSE,
			MOVE_ICEBEAM,
			MOVE_SLUDGEBOMB,
			MOVE_THUNDERBOLT,
		},
	},
	{
		.species = SPECIES_SLIGGOO,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.spAtkEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_STARF_BERRY,
		.moves =
		{
			MOVE_DRACOMETEOR,
			MOVE_ATTRACT,
			MOVE_TOXIC,
			MOVE_PROTECT,
		},
	},
	{
		.species = SPECIES_DOUBLADE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_WEAKNESS_POLICY,
		.moves =
		{
			MOVE_IRONHEAD,
			MOVE_SHADOWSNEAK,
			MOVE_ROCKSLIDE,
			MOVE_SACREDSWORD,
		},
	},
	{
		.species = SPECIES_DOUBLADE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.atkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_EXPERT_BELT,
		.moves =
		{
			MOVE_IRONHEAD,
			MOVE_SHADOWCLAW,
			MOVE_NIGHTSLASH,
			MOVE_AERIALACE,
		},
	},
};

const struct BattleTowerSpread gLittleCupTowerSpread_Gail[] =
{
	{
		.species = SPECIES_GROWLITHE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_EXPERT_BELT,
		.moves =
		{
			MOVE_FLAREBLITZ,
			MOVE_CLOSECOMBAT,
			MOVE_OUTRAGE,
			MOVE_WILDCHARGE,
		},
	},
	{
		.species = SPECIES_GROWLITHE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_ASSAULT_VEST,
		.moves =
		{
			MOVE_FLAREBLITZ,
			MOVE_CRUNCH,
			MOVE_RETURN,
			MOVE_DOUBLEKICK,
		},
	},
	{
		.species = SPECIES_ZORUA,
		.nature = NATURE_SERIOUS,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 4,
		.spdEv = 252,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_DARKPULSE,
			MOVE_EXTRASENSORY,
			MOVE_SHADOWBALL,
			MOVE_HYPERVOICE,
		},
	},
	{
		.species = SPECIES_ZORUA,
		.nature = NATURE_MODEST,
		.hpIv = 30,
		.atkIv = 31,
		.defIv = 30,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 68,
		.defEv = 040,
		.spAtkEv = 200,
		.spDefEv = 200,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_SNARL,
			MOVE_HIDDENPOWER,
			MOVE_UPROAR,
			MOVE_EXTRASENSORY,
		},
	},
	{
		.species = SPECIES_AXEW,
		.nature = NATURE_SERIOUS,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 0,
		.spDefIv = 31,
		.atkEv = 252,
		.defEv = 060,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_2,
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_DRAGONCLAW,
			MOVE_AQUATAIL,
			MOVE_POISONJAB,
			MOVE_XSCISSOR,
		},
	},
	{
		.species = SPECIES_AXEW,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 4,
		.atkEv = 252,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_DRAGON_GEM,
		.moves =
		{
			MOVE_OUTRAGE,
			MOVE_AERIALACE,
			MOVE_GIGAIMPACT,
			MOVE_IRONTAIL,
		},
	},
	{
		.species = SPECIES_FENNEKIN,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 036,
		.spdEv = 036,
		.spAtkEv = 020,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_NONE,
		.moves =
		{
			MOVE_FLAMETHROWER,
			MOVE_PSYSHOCK,
			MOVE_TOXIC,
			MOVE_WISH,
		},
	},
	{
		.species = SPECIES_FENNEKIN,
		.nature = NATURE_MODEST,
		.hpIv = 30,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 30,
		.spDefIv = 31,
		.hpEv = 036,
		.spdEv = 036,
		.spAtkEv = 240,
		.spDefEv = 196,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_WEAKNESS_POLICY,
		.moves =
		{
			MOVE_FLAMETHROWER,
			MOVE_HIDDENPOWER,
			MOVE_WILLOWISP,
			MOVE_ATTRACT,
		},
	},
	{
		.species = SPECIES_AMAURA,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.defEv = 036,
		.spAtkEv = 220,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_SHUCA_BERRY,
		.moves =
		{
			MOVE_ANCIENTPOWER,
			MOVE_ICEBEAM,
			MOVE_HYPERBEAM,
			MOVE_SUBSTITUTE,
		},
	},
	{
		.species = SPECIES_AMAURA,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 4,
		.spDefEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_ICY_ROCK,
		.moves =
		{
			MOVE_ICYWIND,
			MOVE_HAZE,
			MOVE_THUNDERWAVE,
			MOVE_STEALTHROCK,
		},
	},
	{
		.species = SPECIES_SQUIRTLE,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 30,
		.defIv = 31,
		.spdIv = 30,
		.spAtkIv = 30,
		.spDefIv = 31,
		.hpEv = 48,
		.spdEv = 016,
		.spAtkEv = 200,
		.spDefEv = 244,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_DAMP_ROCK,
		.moves =
		{
			MOVE_HYDROPUMP,
			MOVE_AURASPHERE,
			MOVE_HIDDENPOWER,
			MOVE_RAINDANCE,
		},
	},
	{
		.species = SPECIES_SQUIRTLE,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 016,
		.defEv = 236,
		.spdEv = 012,
		.spDefEv = 244,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_SCALD,
			MOVE_TOXIC,
			MOVE_YAWN,
			MOVE_REFLECT,
		},
	},
};

const struct BattleTowerSpread gSpecialTowerSpread_Lixdel[] =
{
	{
		.species = SPECIES_LANDORUS_THERIAN,
		.nature = NATURE_IMPISH,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 30,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 112,
		.spdEv = 144,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_ROCKY_HELMET,
		.moves =
		{
			MOVE_EARTHQUAKE,
			MOVE_UTURN,
			MOVE_HIDDENPOWER,
			MOVE_STEALTHROCK,
		},
	},
	{
		.species = SPECIES_LANDORUS,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 00,
		.spDefIv = 31,
		.atkEv = 252,
		.defEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_SMOOTH_ROCK,
		.moves =
		{
			MOVE_EARTHQUAKE,
			MOVE_STONEEDGE,
			MOVE_SANDSTORM,
			MOVE_STEALTHROCK,
		},
	},
	{
		.species = SPECIES_PINSIR,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 00,
		.spDefIv = 31,
		.atkEv = 252,
		.spdEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_PINSIRITE,
		.moves =
		{
			MOVE_RETURN,
			MOVE_CLOSECOMBAT,
			MOVE_QUICKATTACK,
			MOVE_SWORDSDANCE,
		},
	},
	{
		.species = SPECIES_PINSIR,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 00,
		.spDefIv = 31,
		.atkEv = 252,
		.spdEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_NORMALIUM_Z,
		.moves =
		{
			MOVE_XSCISSOR,
			MOVE_EARTHQUAKE,
			MOVE_STONEEDGE,
			MOVE_MEFIRST,
		},
	},
	{
		.species = SPECIES_GRENINJA,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.defEv = 4,
		.spdEv = 252,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_2,
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_SURF,
			MOVE_DARKPULSE,
			MOVE_UTURN,
			MOVE_WATERSHURIKEN,
		},
	},
	{
		.species = SPECIES_GRENINJA,
		.nature = NATURE_HASTY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.atkEv = 4,
		.spdEv = 252,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_HYDROPUMP,
			MOVE_DARKPULSE,
			MOVE_ICEBEAM,
			MOVE_GUNKSHOT,
		},
	},
	{
		.species = SPECIES_TAPU_FINI,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 248,
		.defEv = 248,
		.spdEv = 4,
		.spDefEv = 8,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_MOONBLAST,
			MOVE_TAUNT,
			MOVE_DEFOG,
			MOVE_NONE,
		},
	},
	{
		.species = SPECIES_TAPU_FINI,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 248,
		.defEv = 016,
		.spdEv = 192,
		.spAtkEv = 012,
		.spDefEv = 040,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_SCALD,
			MOVE_TAUNT,
			MOVE_DEFOG,
			MOVE_NONE,
		},
	},
	{
		.species = SPECIES_CLEFABLE,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_2,
		.item = ITEM_CHERI_BERRY,
		.moves =
		{
			MOVE_MOONBLAST,
			MOVE_THUNDERWAVE,
			MOVE_CALMMIND,
			MOVE_SOFTBOILED,
		},
	},
	{
		.species = SPECIES_CLEFABLE,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_2,
		.item = ITEM_ROCKY_HELMET,
		.moves =
		{
			MOVE_MOONBLAST,
			MOVE_ICEBEAM,
			MOVE_CALMMIND,
			MOVE_SOFTBOILED,
		},
	},
	{
		.species = SPECIES_AMOONGUSS,
		.nature = NATURE_CALM,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 30,
		.spAtkIv = 30,
		.spDefIv = 31,
		.hpEv = 248,
		.defEv = 044,
		.spDefEv = 216,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_OCCA_BERRY,
		.moves =
		{
			MOVE_GIGADRAIN,
			MOVE_CLEARSMOG,
			MOVE_HIDDENPOWER,
			MOVE_SPORE,
		},
	},
	{
		.species = SPECIES_AMOONGUSS,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 30,
		.spAtkIv = 30,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 176,
		.spDefEv = 80,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_BLACK_SLUDGE,
		.moves =
		{
			MOVE_GIGADRAIN,
			MOVE_SLUDGEBOMB,
			MOVE_HIDDENPOWER,
			MOVE_SPORE,
		},
	},
};

const struct BattleTowerSpread gMiddleCupTowerSpread_Lixdel[] =
{
	{
		.species = SPECIES_PORYGON2,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 4,
		.spdEv = 192,
		.spAtkEv = 252,
		.spDefEv = 060,
		.ability = FRONTIER_ABILITY_2,
		.item = ITEM_EVIOLITE,
		.moves =
		{
			MOVE_TRIATTACK,
			MOVE_ICEBEAM,
			MOVE_SHADOWBALL,
			MOVE_RECOVER,
		},
	},
	{
		.species = SPECIES_PORYGON2,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 4,
		.spdEv = 192,
		.spAtkEv = 252,
		.spDefEv = 060,
		.ability = FRONTIER_ABILITY_2,
		.item = ITEM_EVIOLITE,
		.moves =
		{
			MOVE_TRIATTACK,
			MOVE_ICEBEAM,
			MOVE_SHADOWBALL,
			MOVE_AGILITY,
		},
	},
	{
		.species = SPECIES_DOUBLADE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 00,
		.spDefIv = 31,
		.hpEv = 240,
		.atkEv = 252,
		.spDefEv = 016,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_LUM_BERRY,
		.moves =
		{
			MOVE_SHADOWSNEAK,
			MOVE_IRONHEAD,
			MOVE_SACREDSWORD,
			MOVE_SWORDSDANCE,
		},
	},
	{
		.species = SPECIES_DOUBLADE,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 00,
		.spDefIv = 31,
		.hpEv = 240,
		.atkEv = 252,
		.spDefEv = 016,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_LUM_BERRY,
		.moves =
		{
			MOVE_SHADOWSNEAK,
			MOVE_SACREDSWORD,
			MOVE_SWORDSDANCE,
			MOVE_SUBSTITUTE,
		},
	},
	{
		.species = SPECIES_MARSHTOMP,
		.nature = NATURE_RELAXED,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_SCALD,
			MOVE_EARTHQUAKE,
			MOVE_TOXIC,
			MOVE_STEALTHROCK,
		},
	},
	{
		.species = SPECIES_MARSHTOMP,
		.nature = NATURE_RELAXED,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 252,
		.defEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_SCALD,
			MOVE_EARTHQUAKE,
			MOVE_ICEPUNCH,
			MOVE_STEALTHROCK,
		},
	},
	{
		.species = SPECIES_MAGNETON,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 30,
		.spAtkIv = 30,
		.spDefIv = 31,
		.defEv = 4,
		.spdEv = 252,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_THUNDERBOLT,
			MOVE_FLASHCANNON,
			MOVE_HIDDENPOWER, //Fire
			MOVE_VOLTSWITCH,
		},
	},
	{
		.species = SPECIES_MAGNETON,
		.nature = NATURE_MODEST,
		.hpIv = 31,
		.atkIv = 0,
		.defIv = 31,
		.spdIv = 30,
		.spAtkIv = 30,
		.spDefIv = 31,
		.defEv = 4,
		.spdEv = 252,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_CHOICE_SPECS,
		.moves =
		{
			MOVE_THUNDERBOLT,
			MOVE_FLASHCANNON,
			MOVE_HIDDENPOWER, //Fire
			MOVE_VOLTSWITCH,
		},
	},
	{
		.species = SPECIES_STARAVIA,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 00,
		.spDefIv = 31,
		.atkEv = 252,
		.defEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_DOUBLEEDGE,
			MOVE_BRAVEBIRD,
			MOVE_UTURN,
			MOVE_FINALGAMBIT,
		},
	},
	{
		.species = SPECIES_STARAVIA,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 00,
		.spDefIv = 31,
		.atkEv = 252,
		.defEv = 4,
		.spdEv = 252,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_DOUBLEEDGE,
			MOVE_BRAVEBIRD,
			MOVE_UTURN,
			MOVE_QUICKATTACK,
		},
	},
	{
		.species = SPECIES_FROGADIER,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.defEv = 4,
		.spdEv = 252,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_HYDROPUMP,
			MOVE_DARKPULSE,
			MOVE_ICEBEAM,
			MOVE_UTURN,
		},
	},
	{
		.species = SPECIES_FROGADIER,
		.nature = NATURE_TIMID,
		.hpIv = 30,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 30,
		.spDefIv = 31,
		.defEv = 4,
		.spdEv = 252,
		.spAtkEv = 252,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_HYDROPUMP,
			MOVE_ICEBEAM,
			MOVE_HIDDENPOWER,
			MOVE_UTURN,
		},
	},
};


const struct BattleTowerSpread gLittleCupTowerSpread_Lixdel[] =
{
	{
		.species = SPECIES_TIMBURR,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 00,
		.spDefIv = 31,
		.hpEv = 80,
		.atkEv = 196,
		.defEv = 076,
		.spDefEv = 156,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_ASSAULT_VEST,
		.moves =
		{
			MOVE_DRAINPUNCH,
			MOVE_KNOCKOFF,
			MOVE_THUNDERPUNCH,
			MOVE_MACHPUNCH,
		},
	},
	{
		.species = SPECIES_TIMBURR,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 00,
		.spDefIv = 31,
		.hpEv = 80,
		.atkEv = 196,
		.defEv = 076,
		.spDefEv = 156,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_ASSAULT_VEST,
		.moves =
		{
			MOVE_DRAINPUNCH,
			MOVE_KNOCKOFF,
			MOVE_POISONJAB,
			MOVE_MACHPUNCH,
		},
	},
	{
		.species = SPECIES_ABRA,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 01,
		.defIv = 30,
		.spdIv = 30,
		.spAtkIv = 30,
		.spDefIv = 30,
		.spdEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_PSYCHIC,
			MOVE_ENERGYBALL,
			MOVE_DAZZLINGGLEAM,
			MOVE_HIDDENPOWER,
		},
	},
	{
		.species = SPECIES_ABRA,
		.nature = NATURE_TIMID,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 30,
		.spDefIv = 30,
		.spdEv = 252,
		.spAtkEv = 252,
		.spDefEv = 4,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_LIFE_ORB,
		.moves =
		{
			MOVE_PSYCHIC,
			MOVE_ENERGYBALL,
			MOVE_DAZZLINGGLEAM,
			MOVE_HIDDENPOWER,
		},
	},
	{
		.species = SPECIES_VULLABY,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 00,
		.spDefIv = 31,
		.atkEv = 236,
		.defEv = 076,
		.spdEv = 196,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_BERRY_JUICE,
		.moves =
		{
			MOVE_BRAVEBIRD,
			MOVE_KNOCKOFF,
			MOVE_UTURN,
			MOVE_DEFOG,
		},
	},
	{
		.species = SPECIES_VULLABY,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 036,
		.atkEv = 240,
		.spdEv = 116,
		.spAtkEv = 116,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_BERRY_JUICE,
		.moves =
		{
			MOVE_BRAVEBIRD,
			MOVE_KNOCKOFF,
			MOVE_UTURN,
			MOVE_HEATWAVE,
		},
	},
	{
		.species = SPECIES_FOONGUS,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 00,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 31,
		.spDefIv = 31,
		.hpEv = 188,
		.defEv = 160,
		.spDefEv = 160,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_EVIOLITE,
		.moves =
		{
			MOVE_GIGADRAIN,
			MOVE_SLUDGEBOMB,
			MOVE_SPORE,
			MOVE_SYNTHESIS,
		},
	},
	{
		.species = SPECIES_FOONGUS,
		.nature = NATURE_BOLD,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 30,
		.spdIv = 30,
		.spAtkIv = 30,
		.spDefIv = 30,
		.hpEv = 188,
		.defEv = 160,
		.spDefEv = 160,
		.ability = FRONTIER_ABILITY_HIDDEN,
		.item = ITEM_EVIOLITE,
		.moves =
		{
			MOVE_GIGADRAIN,
			MOVE_SLUDGEBOMB,
			MOVE_HIDDENPOWER,
			MOVE_SPORE,
		},
	},
	{
		.species = SPECIES_PAWNIARD,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 00,
		.spDefIv = 31,
		.atkEv = 156,
		.defEv = 036,
		.spdEv = 200,
		.spDefEv = 116,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_CHOICE_BAND,
		.moves =
		{
			MOVE_SUCKERPUNCH,
			MOVE_IRONHEAD,
			MOVE_KNOCKOFF,
			MOVE_PURSUIT,
		},
	},
	{
		.species = SPECIES_PAWNIARD,
		.nature = NATURE_JOLLY,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 00,
		.spDefIv = 31,
		.atkEv = 236,
		.defEv = 036,
		.spdEv = 200,
		.spDefEv = 036,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_CHOICE_SCARF,
		.moves =
		{
			MOVE_SUCKERPUNCH,
			MOVE_IRONHEAD,
			MOVE_KNOCKOFF,
			MOVE_PURSUIT,
		},
	},
	{
		.species = SPECIES_MUDBRAY,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 00,
		.spDefIv = 31,
		.hpEv = 116,
		.atkEv = 196,
		.defEv = 036,
		.spdEv = 160,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_EARTHQUAKE,
			MOVE_ROCKSLIDE,
			MOVE_HEAVYSLAM,
			MOVE_STEALTHROCK,
		},
	},
	{
		.species = SPECIES_MUDBRAY,
		.nature = NATURE_ADAMANT,
		.hpIv = 31,
		.atkIv = 31,
		.defIv = 31,
		.spdIv = 31,
		.spAtkIv = 00,
		.spDefIv = 31,
		.hpEv = 116,
		.atkEv = 196,
		.defEv = 036,
		.spdEv = 160,
		.ability = FRONTIER_ABILITY_1,
		.item = ITEM_LEFTOVERS,
		.moves =
		{
			MOVE_EARTHQUAKE,
			MOVE_CLOSECOMBAT,
			MOVE_HEAVYSLAM,
			MOVE_STEALTHROCK,
		},
	},
};

#endif