#include "..\\defines.h"

//Finish Wild Songs for Unbound

#ifndef UNBOUND

//Modify These
const u16 gClassBasedBattleBGM[NUM_TRAINER_CLASSES] =
{
	[CLASS_CHAMPION] = BGM_BATTLE_CHAMPION,
	[CLASS_LEADER] = BGM_BATTLE_GYM_LEADER,
	[CLASS_ELITE_4] = BGM_BATTLE_GYM_LEADER,
};

const u16 gWildSpeciesBasedBattleBGM[MAX_NUM_POKEMON] =
{
	[PKMN_ARTICUNO] = BGM_BATTLE_LEGENDARY_BIRDS,
	[PKMN_ZAPDOS] = BGM_BATTLE_LEGENDARY_BIRDS,
	[PKMN_MOLTRES] = BGM_BATTLE_LEGENDARY_BIRDS,
	[PKMN_MEWTWO] = BGM_BATTLE_MEWTWO,
	[PKMN_MEW] = BGM_BATTLE_MEWTWO,
	[PKMN_ENTEI] = BGM_BATTLE_LEGENDARY_BIRDS,
	[PKMN_RAIKOU] = BGM_BATTLE_LEGENDARY_BIRDS,
	[PKMN_SUICUNE] = BGM_BATTLE_LEGENDARY_BIRDS,
	[PKMN_HOOH] = BGM_BATTLE_MEWTWO,
	[PKMN_LUGIA] = BGM_BATTLE_MEWTWO,
	[PKMN_CELEBI] = BGM_BATTLE_MEWTWO,
	[PKMN_LATIOS] = BGM_BATTLE_RSE_GYM_LEADER,
	[PKMN_LATIAS] = BGM_BATTLE_RSE_GYM_LEADER,
	[PKMN_GROUDON] = BGM_BATTLE_RSE_GYM_LEADER,
	[PKMN_KYOGRE] = BGM_BATTLE_RSE_GYM_LEADER,
	[PKMN_RAYQUAZA] = BGM_BATTLE_RSE_GYM_LEADER,
	[PKMN_JIRACHI] = BGM_BATTLE_RSE_GYM_LEADER,
	[PKMN_DEOXYS] = BGM_BATTLE_DEOXYS,

};

#else

const u16 gClassBasedBattleBGM[NUM_TRAINER_CLASSES] =
{
	[CLASS_RIVAL] = BGM_BATTLE_RIVAL,
	[CLASS_CHAMPION] = BGM_BATTLE_CHAMPION,
	[CLASS_LEADER] = BGM_BATTLE_GYM_LEADER,
	[CLASS_ELITE_4] = BGM_BATTLE_ELITE_4,
	//[CLASS_SHADOW] = BGM_BATTLE_PLASMA_GRUNT,
	[CLASS_SHADOW_ADMIN] = BGM_BATTLE_NEO_PLASMA_GRUNT,
	[CLASS_BOSS] = BGM_BATTLE_SHADOW_BOSS,
	[CLASS_LOR] = BGM_BATTLE_GALACTIC_GRUNT,
	[CLASS_LOR_ADMIN] = BGM_BATTLE_GALACTIC_ADMIN,
	[CLASS_LOR_LEADER] = BGM_BATTLE_LOR_BOSS,
	[CLASS_SUCCESSOR] = BGM_BATTLE_KALOS_GYM_LEADER,
	[CLASS_TERROR_GRANBULL] = BGM_BATTLE_TEAM_ROCKET_GRUNT,
	[CLASS_BLACK_FERROTHORN] = BGM_BATTLE_TEAM_ROCKET_GRUNT,
};

const u16 gWildSpeciesBasedBattleBGM[MAX_NUM_POKEMON] =
{
	[PKMN_ARTICUNO] = BGM_BATTLE_LEGENDARY_BIRDS,
	[PKMN_ZAPDOS] = BGM_BATTLE_LEGENDARY_BIRDS,
	[PKMN_MOLTRES] = BGM_BATTLE_LEGENDARY_BIRDS,
	[PKMN_MEWTWO] = BGM_BATTLE_MEWTWO,
	[PKMN_MEW] = BGM_BATTLE_MEWTWO,
	[PKMN_ENTEI] = BGM_BATTLE_ENTEI,
	[PKMN_RAIKOU] = BGM_BATTLE_RAIKOU,
	[PKMN_SUICUNE] = BGM_BATTLE_SUICUNE,
	[PKMN_HOOH] = BGM_BATTLE_HOOH,
	[PKMN_LUGIA] = BGM_BATTLE_LUGIA,
	[PKMN_CELEBI] = BGM_BATTLE_MEWTWO,
	[PKMN_LATIOS] = BGM_BATTLE_RSE_GYM_LEADER,
	[PKMN_LATIAS] = BGM_BATTLE_RSE_GYM_LEADER,
	[PKMN_GROUDON] = BGM_BATTLE_GROUDON_KYOGRE_RAYQUAZA,
	[PKMN_KYOGRE] = BGM_BATTLE_GROUDON_KYOGRE_RAYQUAZA,
	[PKMN_RAYQUAZA] = BGM_BATTLE_GROUDON_KYOGRE_RAYQUAZA,
	[PKMN_JIRACHI] = BGM_BATTLE_RSE_GYM_LEADER,
	[PKMN_DEOXYS] = BGM_BATTLE_DEOXYS,
	//TODO
};

#endif