#include "../defines_battle.h"
#include "../../include/pokedex.h"
#include "../../include/constants/species.h"
#include "../../include/constants/items.h"
/*
pokemon_tables.c
	set up tables for pokemon species including:
		-alternate species
		-ban lists
		-move tables by species
		-etc...

tables to edit:
	gAlternateSpeciesSizeTable
	gTelekinesisBanList
	gSkyBattleBannedSpeciesList
	gUltraBeastList
	gDeerlingForms
	gSawsbuckForms
	gVivillonForms
	gFlabebeForms
	gFloetteForms
	gFlorgesForms
	gFurfrouForms
	gPikachuCapForms
	gSetPerfectXIvList
	gRandomizerBanList
	gRandomizerAbilityBanList

	gBattleTowerStandardSpeciesBanList
	gGSCup_LegendarySpeciesList
	gSmogonOU_SpeciesBanList
	gSmogonOUDoubles_SpeciesBanList
	gSmogonOU_AbilityBanList
	gSmogonOUDoubles_AbilityBanList
	gBattleTowerStandard_ItemBanList
	gSmogonOU_ItemBanList
	gSmogonOUDoubles_ItemBanList
	gSmogonOUDoubles_MoveBanList
	gSmogon_MoveBanList
	gSmogonLittleCup_SpeciesList
	gSmogonLittleCup_MoveBanList
	gSmogonLittleCup_ItemBanList
	gMiddleCup_SpeciesList
	gMiddleCup_AbilityBanList
	gMiddleCup_ItemBanList
	gSmogonMonotype_SpeciesBanList
	gSmogonMonotype_AbilityBanList
	gSmogonMonotype_ItemBanList
	gSmogonCamomons_SpeciesBanList
	gSmogonAverageMons_SpeciesBanList
	gSmogonAverageMons_ItemBanList
	gSmogonAverageMons_MoveBanList
	gSmogonAverageMons_AbilityBanList
	gSmogon350Cup_SpeciesBanList
	gSmogon350Cup_ItemBanList
	gSmogon350Cup_AbilityBanList
	gSmogonScalemons_SpeciesBanList
	gSmogonScalemons_ItemBanList
	gSmogonScalemons_AbilityBanList
	gSmogonBenjaminButterfree_SpeciesBanList


*/

#define ALTERNATE_SIZE(species, height, weight) {species, height * 10, weight * 10}

const struct AlternateSize gAlternateSpeciesSizeTable[] =
{
	ALTERNATE_SIZE(SPECIES_PIDGEOT, 2.2, 50.5),
	ALTERNATE_SIZE(SPECIES_RAYQUAZA_MEGA, 10.8, 392.0),
	ALTERNATE_SIZE(SPECIES_GIRATINA_ORIGIN, 6.9, 650.0),
	ALTERNATE_SIZE(SPECIES_SHAYMIN_SKY, 0.4, 5.2),
	ALTERNATE_SIZE(SPECIES_TORNADUS_THERIAN, 1.4, 63.0),
	ALTERNATE_SIZE(SPECIES_THUNDURUS_THERIAN, 3.0, 61.0),
	ALTERNATE_SIZE(SPECIES_LANDORUS_THERIAN, 1.3, 68.0),
	ALTERNATE_SIZE(SPECIES_KYUREM_BLACK, 3.3, 325.0),
	ALTERNATE_SIZE(SPECIES_KYUREM_WHITE, 3.6, 325.0),
	ALTERNATE_SIZE(SPECIES_ZYGARDE_10, 1.2, 33.5),
	ALTERNATE_SIZE(SPECIES_ZYGARDE_COMPLETE, 4.5, 610.0),
	ALTERNATE_SIZE(SPECIES_LYCANROC_N, 1.1, 25.0),
	ALTERNATE_SIZE(SPECIES_NECROZMA_DAWN_WINGS, 4.2, 350.0),
	ALTERNATE_SIZE(SPECIES_NECROZMA_DUSK_MANE, 3.8, 460.0),
	ALTERNATE_SIZE(SPECIES_NECROZMA_ULTRA, 7.5, 230.0),
	ALTERNATE_SIZE(SPECIES_TABLES_TERMIN, 0, 0),
};

//The move Telekinesis don't affect these Pokemon
const species_t gTelekinesisBanList[] =
{
	SPECIES_DIGLETT,
	SPECIES_DUGTRIO,
	SPECIES_TABLES_TERMIN
};

const species_t gSkyBattleBannedSpeciesList[] =
{
#ifndef UNBOUND
	SPECIES_SPEAROW,
	SPECIES_FARFETCHD,
	SPECIES_HOOTHOOT,
	SPECIES_NATU,
	SPECIES_MURKROW,
	SPECIES_DELIBIRD,
	SPECIES_TAILLOW,
	SPECIES_SHAYMIN_SKY,
	SPECIES_ARCHEN,
#endif
	SPECIES_GENGAR,
	SPECIES_DODUO,
	SPECIES_DODRIO,
	SPECIES_TABLES_TERMIN
};

//For the purposes of the Beast Ball
const species_t gUltraBeastList[] =
{
	SPECIES_NIHILEGO,
	SPECIES_BUZZWOLE,
	SPECIES_PHEROMOSA,
	SPECIES_XURKITREE,
	SPECIES_CELESTEELA,
	SPECIES_KARTANA,
	SPECIES_GUZZLORD,
	SPECIES_POIPOLE,
	SPECIES_NAGANADEL,
	SPECIES_STAKATAKA,
	SPECIES_BLACEPHALON,
	SPECIES_TABLES_TERMIN
};

const species_t gDeerlingForms[] =
{
	SPECIES_NONE
	//No termin here
};

const u8 gNumDeerlingForms = NELEMS(gDeerlingForms);

const species_t gSawsbuckForms[] =
{
	SPECIES_NONE
	//No termin here
};

const u8 gNumSawsbuckForms = NELEMS(gSawsbuckForms);

const species_t gVivillonForms[] =
{
	SPECIES_NONE
	//No termin here
};

const u8 gNumVivillonForms = NELEMS(gVivillonForms);

const species_t gFlabebeForms[] =
{
	SPECIES_FLABEBE,
	SPECIES_FLABEBE_ROSE
	//No termin here
};

const u8 gNumFlabebeForms = NELEMS(gFlabebeForms);

const species_t gFloetteForms[] =
{
	SPECIES_FLOETTE,
	SPECIES_FLOETTE_ROSE,
	SPECIES_FLOETTE_ETERNAL
	//No termin here
};

const u8 gNumFloetteForms = NELEMS(gFloetteForms);

const species_t gFlorgesForms[] =
{
	SPECIES_FLORGES,
	SPECIES_FLORGES_ROSE
	//No termin here
};

const u8 gNumFlorgesForms = NELEMS(gFlorgesForms);

const species_t gFurfrouForms[] =
{
	SPECIES_NONE
	//No termin here
};

const u8 gNumFurfrouForms = NELEMS(gFurfrouForms);

const species_t gPikachuCapForms[] =
{
	SPECIES_NONE
	//No termin here
};

const u8 gNumPikachuCapForms = NELEMS(gPikachuCapForms);

const species_t gAlcremieForms[] =
{
	SPECIES_NONE
	//No termin here
};

const u8 gNumAlcremieForms = NELEMS(gAlcremieForms);

const species_t gBattleTowerStandardSpeciesBanList[] =
{
	SPECIES_MEWTWO,
	SPECIES_MEW,
	SPECIES_LUGIA,
	SPECIES_HO_OH,
	SPECIES_CELEBI,
	SPECIES_KYOGRE,
	SPECIES_GROUDON,
	SPECIES_RAYQUAZA,
	SPECIES_JIRACHI,
	SPECIES_DEOXYS,
	SPECIES_DEOXYS_ATTACK,
	SPECIES_DEOXYS_DEFENSE,
	SPECIES_DEOXYS_SPEED,
	SPECIES_DIALGA,
	SPECIES_PALKIA,
	SPECIES_GIRATINA,
	SPECIES_GIRATINA_ORIGIN,
	SPECIES_DARKRAI,
	SPECIES_SHAYMIN,
	SPECIES_SHAYMIN_SKY,
	SPECIES_ARCEUS,
	SPECIES_ARCEUS_FIGHT,
	SPECIES_ARCEUS_FLYING,
	SPECIES_ARCEUS_POISON,
	SPECIES_ARCEUS_GROUND,
	SPECIES_ARCEUS_ROCK,
	SPECIES_ARCEUS_BUG,
	SPECIES_ARCEUS_GHOST,
	SPECIES_ARCEUS_STEEL,
	SPECIES_ARCEUS_FIRE,
	SPECIES_ARCEUS_WATER,
	SPECIES_ARCEUS_GRASS,
	SPECIES_ARCEUS_ELECTRIC,
	SPECIES_ARCEUS_PSYCHIC,
	SPECIES_ARCEUS_ICE,
	SPECIES_ARCEUS_DRAGON,
	SPECIES_ARCEUS_DARK,
	SPECIES_ARCEUS_FAIRY,
	SPECIES_KYUREM,
	SPECIES_KYUREM_BLACK,
	SPECIES_KYUREM_WHITE,
	SPECIES_GENESECT,
	SPECIES_GENESECT_SHOCK,
	SPECIES_GENESECT_BURN,
	SPECIES_GENESECT_CHILL,
	SPECIES_GENESECT_DOUSE,
	SPECIES_DIANCIE,
	SPECIES_ZYGARDE,
	SPECIES_ZYGARDE_10,
	SPECIES_COSMOG,
	SPECIES_COSMOEM,
	SPECIES_SOLGALEO,
	SPECIES_LUNALA,
	SPECIES_NECROZMA,
	SPECIES_NECROZMA_DUSK_MANE,
	SPECIES_NECROZMA_DAWN_WINGS,
	SPECIES_MELTAN,
	SPECIES_MELMETAL,
	SPECIES_ETERNATUS,
	SPECIES_TABLES_TERMIN
};

const species_t gGSCup_LegendarySpeciesList[] =
{
	SPECIES_MEWTWO,
	SPECIES_LUGIA,
	SPECIES_HO_OH,
	SPECIES_GROUDON,
	SPECIES_KYOGRE,
	SPECIES_RAYQUAZA,
	SPECIES_DIALGA,
	SPECIES_PALKIA,
	SPECIES_GIRATINA,
	SPECIES_GIRATINA_ORIGIN,
	SPECIES_KYUREM,
	SPECIES_KYUREM_BLACK,
	SPECIES_KYUREM_WHITE,
	SPECIES_ZYGARDE,
	SPECIES_ZYGARDE_10,
	SPECIES_SOLGALEO,
	SPECIES_LUNALA,
	SPECIES_NECROZMA,
	SPECIES_NECROZMA_DUSK_MANE,
	SPECIES_NECROZMA_DAWN_WINGS,
	SPECIES_ETERNATUS,
	SPECIES_TABLES_TERMIN
};

const species_t gSmogonOU_SpeciesBanList[] =
{
	SPECIES_AEGISLASH,
	SPECIES_ARCEUS,
	SPECIES_ARCEUS_FIGHT,
	SPECIES_ARCEUS_FLYING,
	SPECIES_ARCEUS_POISON,
	SPECIES_ARCEUS_GROUND,
	SPECIES_ARCEUS_ROCK,
	SPECIES_ARCEUS_BUG,
	SPECIES_ARCEUS_GHOST,
	SPECIES_ARCEUS_STEEL,
	SPECIES_ARCEUS_FIRE,
	SPECIES_ARCEUS_WATER,
	SPECIES_ARCEUS_GRASS,
	SPECIES_ARCEUS_ELECTRIC,
	SPECIES_ARCEUS_PSYCHIC,
	SPECIES_ARCEUS_ICE,
	SPECIES_ARCEUS_DRAGON,
	SPECIES_ARCEUS_DARK,
	SPECIES_ARCEUS_FAIRY,
	SPECIES_BLAZIKEN,
	SPECIES_DARKRAI,
	SPECIES_DEOXYS,
	SPECIES_DEOXYS_ATTACK,
	SPECIES_DEOXYS_DEFENSE,
	SPECIES_DEOXYS_SPEED,
	SPECIES_DIALGA,
	SPECIES_GENESECT,
	SPECIES_GENESECT_SHOCK,
	SPECIES_GENESECT_BURN,
	SPECIES_GENESECT_CHILL,
	SPECIES_GENESECT_DOUSE,
	SPECIES_GIRATINA,
	SPECIES_GIRATINA_ORIGIN,
	SPECIES_GROUDON,
	SPECIES_HO_OH,
	SPECIES_KYOGRE,
	SPECIES_KYUREM_WHITE,
	SPECIES_LANDORUS,
	SPECIES_LUGIA,
	SPECIES_LUNALA,
	SPECIES_MEWTWO,
	SPECIES_NAGANADEL,
	SPECIES_NECROZMA_DUSK_MANE,
	SPECIES_NECROZMA_DAWN_WINGS,
	SPECIES_PALKIA,
	SPECIES_PHEROMOSA,
	SPECIES_RAYQUAZA,
	SPECIES_SHAYMIN_SKY,
	SPECIES_SOLGALEO,
	SPECIES_ZYGARDE,
	SPECIES_ETERNATUS,
	SPECIES_TABLES_TERMIN
};

const species_t gSmogonNationalDexOU_SpeciesBanList[] =
{
	SPECIES_ARCEUS,
	SPECIES_ARCEUS_FIGHT,
	SPECIES_ARCEUS_FLYING,
	SPECIES_ARCEUS_POISON,
	SPECIES_ARCEUS_GROUND,
	SPECIES_ARCEUS_ROCK,
	SPECIES_ARCEUS_BUG,
	SPECIES_ARCEUS_GHOST,
	SPECIES_ARCEUS_STEEL,
	SPECIES_ARCEUS_FIRE,
	SPECIES_ARCEUS_WATER,
	SPECIES_ARCEUS_GRASS,
	SPECIES_ARCEUS_ELECTRIC,
	SPECIES_ARCEUS_PSYCHIC,
	SPECIES_ARCEUS_ICE,
	SPECIES_ARCEUS_DRAGON,
	SPECIES_ARCEUS_DARK,
	SPECIES_ARCEUS_FAIRY,
	SPECIES_BLAZIKEN,
	SPECIES_DARKRAI,
	SPECIES_DEOXYS,
	SPECIES_DEOXYS_ATTACK,
	SPECIES_DEOXYS_SPEED,
	SPECIES_DIALGA,
	SPECIES_GENESECT,
	SPECIES_GENESECT_SHOCK,
	SPECIES_GENESECT_BURN,
	SPECIES_GENESECT_CHILL,
	SPECIES_GENESECT_DOUSE,
	SPECIES_GIRATINA,
	SPECIES_GIRATINA_ORIGIN,
	SPECIES_GROUDON,
	SPECIES_HO_OH,
	SPECIES_KYOGRE,
	SPECIES_KYUREM_BLACK,
	SPECIES_KYUREM_WHITE,
	SPECIES_LANDORUS,
	SPECIES_LUGIA,
	SPECIES_LUNALA,
	SPECIES_MEWTWO,
	SPECIES_NAGANADEL,
	SPECIES_NECROZMA_DUSK_MANE,
	SPECIES_NECROZMA_DAWN_WINGS,
	SPECIES_PALKIA,
	SPECIES_PHEROMOSA,
	SPECIES_RAYQUAZA,
	SPECIES_SHAYMIN_SKY,
	SPECIES_SOLGALEO,
	SPECIES_ZYGARDE,
	SPECIES_ETERNATUS,
	SPECIES_TABLES_TERMIN
};

const species_t gSmogonOUDoubles_SpeciesBanList[] =
{
	SPECIES_SNORLAX,
	SPECIES_MEWTWO,
	SPECIES_LUGIA,
	SPECIES_HO_OH,
	SPECIES_KYOGRE,
	SPECIES_GROUDON,
	SPECIES_RAYQUAZA,
	SPECIES_JIRACHI,
	SPECIES_DIALGA,
	SPECIES_PALKIA,
	SPECIES_GIRATINA,
	SPECIES_GIRATINA_ORIGIN,
	SPECIES_ARCEUS,
	SPECIES_ARCEUS_FIGHT,
	SPECIES_ARCEUS_FLYING,
	SPECIES_ARCEUS_POISON,
	SPECIES_ARCEUS_GROUND,
	SPECIES_ARCEUS_ROCK,
	SPECIES_ARCEUS_BUG,
	SPECIES_ARCEUS_GHOST,
	SPECIES_ARCEUS_STEEL,
	SPECIES_ARCEUS_FIRE,
	SPECIES_ARCEUS_WATER,
	SPECIES_ARCEUS_GRASS,
	SPECIES_ARCEUS_ELECTRIC,
	SPECIES_ARCEUS_PSYCHIC,
	SPECIES_ARCEUS_ICE,
	SPECIES_ARCEUS_DRAGON,
	SPECIES_ARCEUS_DARK,
	SPECIES_ARCEUS_FAIRY,
	SPECIES_KYUREM_WHITE,
	SPECIES_SOLGALEO,
	SPECIES_LUNALA,
	SPECIES_ETERNATUS,
	SPECIES_TABLES_TERMIN
};

const ability_t gSmogonOU_AbilityBanList[] =
{
	ABILITY_ARENATRAP,
	ABILITY_SHADOWTAG,
	ABILITY_POWERCONSTRUCT,
	ABILITY_MOODY,
	ABILITY_TABLES_TERMIN
};

const ability_t gSmogonOUDoubles_AbilityBanList[] =
{
	ABILITY_POWERCONSTRUCT,
	ABILITY_MOODY,
	ABILITY_TABLES_TERMIN
};

const item_t gBattleTowerStandard_ItemBanList[] =
{
	#ifdef OLD_SOUL_DEW_EFFECT
	ITEM_SOUL_DEW,
	#endif
	ITEM_TABLES_TERMIN
};

const item_t gSmogonOU_ItemBanList[] =
{
	ITEM_BLAZIKENITE,
	ITEM_GENGARITE,
	ITEM_LUCARIONITE,
	ITEM_KANGASKHANITE,
	ITEM_METAGROSSITE,
	ITEM_SALAMENCITE,
	ITEM_RED_ORB,
	ITEM_BLUE_ORB,
	#ifdef OLD_SOUL_DEW_EFFECT
	ITEM_SOUL_DEW,
	#endif
	ITEM_TABLES_TERMIN
};

const item_t gSmogonNationalDexOU_ItemBanList[] =
{
	ITEM_BLAZIKENITE,
	ITEM_GENGARITE,
	ITEM_LUCARIONITE,
	ITEM_KANGASKHANITE,
	ITEM_SALAMENCITE,
	ITEM_RED_ORB,
	ITEM_BLUE_ORB,
	#ifdef OLD_SOUL_DEW_EFFECT
	ITEM_SOUL_DEW,
	#endif
	ITEM_TABLES_TERMIN
};

const item_t gSmogonOUDoubles_ItemBanList[] =
{
	ITEM_GENGARITE,
	ITEM_EEVIUM_Z,
	ITEM_KANGASKHANITE,
	ITEM_RED_ORB,
	ITEM_BLUE_ORB,
	#ifdef OLD_SOUL_DEW_EFFECT
	ITEM_SOUL_DEW,
	#endif
	ITEM_TABLES_TERMIN
};

const move_t gSmogonOUDoubles_MoveBanList[] =
{
	MOVE_DARKVOID,
	MOVE_SWAGGER,
	MOVE_TABLES_TERMIN
};

const move_t gSmogon_MoveBanList[] =
{
	MOVE_DOUBLETEAM,
	MOVE_MINIMIZE,
	MOVE_FISSURE,
	MOVE_GUILLOTINE,
	MOVE_HORNDRILL,
	MOVE_SHEERCOLD,
	MOVE_TABLES_TERMIN
};

const species_t gSmogonLittleCup_SpeciesList[] =
{
	SPECIES_ABRA,
	SPECIES_ANORITH,
	SPECIES_ARCHEN,
	SPECIES_ARON,
	SPECIES_AZURILL,
	SPECIES_BAGON,
	SPECIES_BALTOY,
	SPECIES_BARBOACH,
	SPECIES_BELDUM,
	SPECIES_BELLSPROUT,
	SPECIES_BONSLY,
	SPECIES_BRONZOR,
	SPECIES_BUDEW,
	SPECIES_BULBASAUR,
	SPECIES_CACNEA,
	SPECIES_CARVANHA,
	SPECIES_CATERPIE,
	SPECIES_CHARMANDER,
	SPECIES_CHIKORITA,
	SPECIES_CHIMCHAR,
	SPECIES_CHINCHOU,
	SPECIES_CHINGLING,
	SPECIES_CLAMPERL,
	SPECIES_CLEFFA,
	SPECIES_CORPHISH,
	SPECIES_COSMOG,
	SPECIES_CROAGUNK,
	SPECIES_CUBONE,
	SPECIES_CYNDAQUIL,
	SPECIES_DEINO,
	SPECIES_DIGLETT,
	SPECIES_DODUO,
	SPECIES_DRATINI,
	SPECIES_DRILBUR,
	SPECIES_DROWZEE,
	SPECIES_DUSKULL,
	SPECIES_EEVEE,
	SPECIES_EKANS,
	SPECIES_ELECTRIKE,
	SPECIES_ELEKID,
	SPECIES_EXEGGCUTE,
	SPECIES_FEEBAS,
	SPECIES_FLABEBE,
	SPECIES_FRILLISH,
	SPECIES_GASTLY,
	SPECIES_GEODUDE,
	SPECIES_GIBLE,
	SPECIES_GOLDEEN,
	SPECIES_GOLETT,
	SPECIES_GRIMER,
	SPECIES_GROWLITHE,
	SPECIES_GULPIN,
	SPECIES_HAPPINY,
	SPECIES_HONEDGE,
	SPECIES_HOOTHOOT,
	SPECIES_HOPPIP,
	SPECIES_HORSEA,
	SPECIES_HOUNDOUR,
	SPECIES_IGGLYBUFF,
	SPECIES_KABUTO,
	SPECIES_KLINK,
	SPECIES_KOFFING,
	SPECIES_KRABBY,
	SPECIES_LARVESTA,
	SPECIES_LARVITAR,
	SPECIES_LEDYBA,
	SPECIES_LICKITUNG,
	SPECIES_LILEEP,
	SPECIES_LOTAD,
	SPECIES_MACHOP,
	SPECIES_MAGBY,
	SPECIES_MAGIKARP,
	SPECIES_MAGNEMITE,
	SPECIES_MAKUHITA,
	SPECIES_MANKEY,
	SPECIES_MANTYKE,
	SPECIES_MAREEP,
	SPECIES_MEOWTH,
	SPECIES_MIME_JR,
	SPECIES_MUDKIP,
	SPECIES_MUNCHLAX,
	SPECIES_NATU,
	SPECIES_NIDORAN_F,
	SPECIES_NIDORAN_M,
	SPECIES_NINCADA,
	SPECIES_NOSEPASS,
	SPECIES_NUMEL,
	SPECIES_ODDISH,
	SPECIES_OMANYTE,
	SPECIES_ONIX,
	SPECIES_PARAS,
	SPECIES_PAWNIARD,
	SPECIES_PHANPY,
	SPECIES_PHANTUMP,
	SPECIES_PICHU,
	SPECIES_PIDGEY,
	SPECIES_PINECO,
	SPECIES_PIPLUP,
	SPECIES_POLIWAG,
	SPECIES_PONYTA,
	SPECIES_POOCHYENA,
	SPECIES_PSYDUCK,
	SPECIES_PUMPKABOO,
	SPECIES_RALTS,
	SPECIES_RATTATA,
	SPECIES_REMORAID,
	SPECIES_RHYHORN,
	SPECIES_RIOLU,
	SPECIES_ROCKRUFF,
	SPECIES_SANDSHREW,
	SPECIES_SCRAGGY,
	SPECIES_SEEDOT,
	SPECIES_SEEL,
	SPECIES_SENTRET,
	SPECIES_SHELLDER,
	SPECIES_SHINX,
	SPECIES_SHROOMISH,
	SPECIES_SHUPPET,
	SPECIES_SKITTY,
	SPECIES_SLAKOTH,
	SPECIES_SLOWPOKE,
	SPECIES_SLUGMA,
	SPECIES_SMOOCHUM,
	SPECIES_SNORUNT,
	SPECIES_SNOVER,
	SPECIES_SNUBBULL,
	SPECIES_SOLOSIS,
	SPECIES_SPEAROW,
	SPECIES_SPHEAL,
	SPECIES_SPINARAK,
	SPECIES_SPOINK,
	SPECIES_SQUIRTLE,
	SPECIES_STARYU,
	SPECIES_SUNKERN,
	SPECIES_SURSKIT,
	SPECIES_SWABLU,
	SPECIES_SWINUB,
	SPECIES_TAILLOW,
	SPECIES_TEDDIURSA,
	SPECIES_TENTACOOL,
	SPECIES_TIMBURR,
	SPECIES_TOGEPI,
	SPECIES_TOTODILE,
	SPECIES_TRAPINCH,
	SPECIES_TREECKO,
	SPECIES_TRUBBISH,
	SPECIES_TURTWIG,
	SPECIES_TYROGUE,
	SPECIES_TYRUNT,
	SPECIES_VENONAT,
	SPECIES_VOLTORB,
	SPECIES_VULPIX_A,
	SPECIES_WAILMER,
	SPECIES_WEEDLE,
	SPECIES_WHISMUR,
	SPECIES_WINGULL,
	SPECIES_WOOPER,
	SPECIES_WURMPLE,
	SPECIES_WYNAUT,
	SPECIES_YAMASK,
	SPECIES_ZIGZAGOON,
	SPECIES_ZUBAT,
	SPECIES_TABLES_TERMIN
};

const move_t gSmogonLittleCup_MoveBanList[] =
{
	MOVE_DRAGONRAGE,
	MOVE_SONICBOOM,
	MOVE_SWAGGER,
	MOVE_TABLES_TERMIN
};

const item_t gSmogonLittleCup_ItemBanList[] =
{
	ITEM_EEVIUM_Z,
	ITEM_TABLES_TERMIN
};

const species_t gMiddleCup_SpeciesList[] =
{
	SPECIES_IVYSAUR,
	SPECIES_CHARMELEON,
	SPECIES_WARTORTLE,
	SPECIES_METAPOD,
	SPECIES_KAKUNA,
	SPECIES_PIDGEOTTO,
	SPECIES_PIKACHU,
	SPECIES_PIKACHU_SURFING,
	SPECIES_PIKACHU_FLYING,
	SPECIES_NIDORINA,
	SPECIES_NIDORINO,
	SPECIES_CLEFAIRY,
	SPECIES_JIGGLYPUFF,
	SPECIES_GOLBAT,
	SPECIES_GLOOM,
	SPECIES_POLIWHIRL,
//	SPECIES_KADABRA, //Banned
	SPECIES_MACHOKE,
	SPECIES_WEEPINBELL,
	SPECIES_GRAVELER,
	SPECIES_MAGNETON,
	SPECIES_HAUNTER,
	SPECIES_RHYDON,
//	SPECIES_CHANSEY, //Banned
	SPECIES_SEADRA,
	SPECIES_ELECTABUZZ,
	SPECIES_MAGMAR,
	SPECIES_PORYGON2,
	SPECIES_DRAGONAIR,
	SPECIES_BAYLEEF,
	SPECIES_QUILAVA,
	SPECIES_CROCONAW,
	SPECIES_TOGETIC,
	SPECIES_FLAAFFY,
	SPECIES_MARILL,
	SPECIES_SKIPLOOM,
	SPECIES_PILOSWINE,
	SPECIES_PUPITAR,
	SPECIES_GROVYLE,
//	SPECIES_COMBUSKEN, //Banned
	SPECIES_MARSHTOMP,
	SPECIES_SILCOON,
	SPECIES_CASCOON,
	SPECIES_LOMBRE,
	SPECIES_NUZLEAF,
	SPECIES_KIRLIA,
	SPECIES_VIGOROTH,
	SPECIES_LOUDRED,
	SPECIES_LAIRON,
	SPECIES_ROSELIA,
	SPECIES_VIBRAVA,
	SPECIES_DUSCLOPS,
	SPECIES_SEALEO,
	SPECIES_SHELGON,
	SPECIES_METANG,
	SPECIES_GROTLE,
	SPECIES_MONFERNO,
	SPECIES_PRINPLUP,
	SPECIES_LUXIO,
	SPECIES_GABITE,
	SPECIES_GURDURR,
	SPECIES_DUOSION,
	SPECIES_KLANG,
	SPECIES_ZWEILOUS,
	SPECIES_DOUBLADE,
	SPECIES_COSMOEM,
	SPECIES_TABLES_TERMIN
};

const ability_t gMiddleCup_AbilityBanList[] =
{
	ABILITY_CONTRARY,
	ABILITY_PROTEAN,
	ABILITY_TABLES_TERMIN
};

const species_t gMiddleCup_ItemBanList[] =
{
	ITEM_LIGHT_BALL,
	ITEM_TABLES_TERMIN
};

const species_t gSmogonMonotype_SpeciesBanList[] =
{
	SPECIES_AEGISLASH,
	SPECIES_ARCEUS,
	SPECIES_ARCEUS_FIGHT,
	SPECIES_ARCEUS_FLYING,
	SPECIES_ARCEUS_POISON,
	SPECIES_ARCEUS_GROUND,
	SPECIES_ARCEUS_ROCK,
	SPECIES_ARCEUS_BUG,
	SPECIES_ARCEUS_GHOST,
	SPECIES_ARCEUS_STEEL,
	SPECIES_ARCEUS_FIRE,
	SPECIES_ARCEUS_WATER,
	SPECIES_ARCEUS_GRASS,
	SPECIES_ARCEUS_ELECTRIC,
	SPECIES_ARCEUS_PSYCHIC,
	SPECIES_ARCEUS_ICE,
	SPECIES_ARCEUS_DRAGON,
	SPECIES_ARCEUS_DARK,
	SPECIES_ARCEUS_FAIRY,
	SPECIES_BLAZIKEN,
	SPECIES_DARKRAI,
	SPECIES_DEOXYS,
	SPECIES_DEOXYS_ATTACK,
	SPECIES_DIALGA,
	SPECIES_GENESECT,
	SPECIES_GENESECT_SHOCK,
	SPECIES_GENESECT_BURN,
	SPECIES_GENESECT_CHILL,
	SPECIES_GENESECT_DOUSE,
	SPECIES_GIRATINA,
	SPECIES_GIRATINA_ORIGIN,
	SPECIES_GROUDON,
	SPECIES_HO_OH,
	SPECIES_KARTANA,
	SPECIES_KYOGRE,
	SPECIES_KYUREM_WHITE,
	SPECIES_LUGIA,
	SPECIES_LUNALA,
	SPECIES_MEWTWO,
	SPECIES_NAGANADEL,
	SPECIES_NECROZMA_DAWN_WINGS,
	SPECIES_NECROZMA_DUSK_MANE,
	SPECIES_PALKIA,
	SPECIES_PHEROMOSA,
	SPECIES_RAYQUAZA,
	SPECIES_SHAYMIN_SKY,
	SPECIES_SOLGALEO,
	SPECIES_ZYGARDE,
	SPECIES_ZYGARDE_10,
	SPECIES_TABLES_TERMIN
};

const ability_t gSmogonMonotype_AbilityBanList[] =
{
	ABILITY_BATTLEBOND,
	ABILITY_TABLES_TERMIN
};

const item_t gSmogonMonotype_ItemBanList[] =
{
	ITEM_DAMP_ROCK,
	ITEM_GENGARITE,
	ITEM_KANGASKHANITE,
	ITEM_LUCARIONITE,
	ITEM_MAWILITE,
	ITEM_MEDICHAMITE,
	ITEM_METAGROSSITE,
	ITEM_SALAMENCITE,
	ITEM_SMOOTH_ROCK,
	ITEM_TERRAIN_EXTENDER,
	ITEM_RED_ORB,
	ITEM_BLUE_ORB,
	#ifdef OLD_SOUL_DEW_EFFECT
	ITEM_SOUL_DEW,
	#endif
	ITEM_TABLES_TERMIN
};

const species_t gSmogonCamomons_SpeciesBanList[] =
{
	SPECIES_DRAGONITE,
	SPECIES_KARTANA,
	SPECIES_KYUREM_BLACK,
	SPECIES_SHEDINJA,
	SPECIES_TABLES_TERMIN //+ OU Banned Pokemon
};

const species_t gSmogonAverageMons_SpeciesBanList[] =
{
	SPECIES_SMEARGLE,
	SPECIES_TABLES_TERMIN,
};

const item_t gSmogonAverageMons_ItemBanList[] =
{
	ITEM_THICK_CLUB,
	ITEM_DEEP_SEA_TOOTH,
	ITEM_LIGHT_BALL,
	ITEM_EVIOLITE,
	ITEM_MAWILITE,
	ITEM_MEDICHAMITE,
	ITEM_GENGARITE,
	ITEM_TABLES_TERMIN
};

const move_t gSmogonAverageMons_MoveBanList[] =
{
	MOVE_CHATTER,
	MOVE_BATONPASS,
	MOVE_TABLES_TERMIN
};

const u8 gSmogonAverageMons_AbilityBanList[] =
{
	ABILITY_HUGEPOWER,
//	ABILITY_PUREPOWER,
	ABILITY_SHADOWTAG,
	ABILITY_ARENATRAP,
	ABILITY_TABLES_TERMIN
};

const species_t gSmogon350Cup_SpeciesBanList[] =
{
	SPECIES_TABLES_TERMIN
};

const item_t gSmogon350Cup_ItemBanList[] =
{
	ITEM_DEEP_SEA_TOOTH,
	ITEM_LIGHT_BALL,
	ITEM_EVIOLITE,
	ITEM_EEVIUM_Z,
	ITEM_TABLES_TERMIN
};

const u8 gSmogon350Cup_AbilityBanList[] =
{
	ABILITY_SHADOWTAG,
	ABILITY_ARENATRAP,
	ABILITY_TABLES_TERMIN
};

const species_t gSmogonScalemons_SpeciesBanList[] =
{
	SPECIES_ABRA,
	SPECIES_CARVANHA,
	SPECIES_GASTLY,
	SPECIES_SHEDINJA,
	SPECIES_TABLES_TERMIN
};

const item_t gSmogonScalemons_ItemBanList[] =
{
	ITEM_DEEP_SEA_SCALE,
	ITEM_DEEP_SEA_TOOTH,
	ITEM_EEVIUM_Z,
	ITEM_EVIOLITE,
	ITEM_LIGHT_BALL,
	ITEM_THICK_CLUB,
	ITEM_MAWILITE,
	ITEM_MEDICHAMITE,
	ITEM_GENGARITE,
	ITEM_TABLES_TERMIN
};

const u8 gSmogonScalemons_AbilityBanList[] =
{
	ABILITY_SHADOWTAG,
	ABILITY_HUGEPOWER,
	ABILITY_ARENATRAP,
	ABILITY_TABLES_TERMIN
};

const species_t gSmogonBenjaminButterfree_SpeciesBanList[] =
{
	SPECIES_BLISSEY,
	SPECIES_TABLES_TERMIN //+ OU Banned Pokemon
};

#ifdef CREATE_WITH_X_PERFECT_IVS
const species_t gSetPerfectXIvList[] =
{
	SPECIES_ARTICUNO,
	SPECIES_ZAPDOS,
	SPECIES_MOLTRES,
	SPECIES_MEWTWO,
	SPECIES_MEW,
	SPECIES_RAIKOU,
	SPECIES_ENTEI,
	SPECIES_SUICUNE,
	SPECIES_LUGIA,
	SPECIES_HO_OH,
	SPECIES_CELEBI,
	SPECIES_REGIROCK,
	SPECIES_REGICE,
	SPECIES_REGISTEEL,
	SPECIES_LATIAS,
	SPECIES_LATIOS,
	SPECIES_KYOGRE,
	SPECIES_GROUDON,
	SPECIES_RAYQUAZA,
	SPECIES_JIRACHI,
	SPECIES_DEOXYS,
	SPECIES_DEOXYS_ATTACK,
	SPECIES_DEOXYS_DEFENSE,
	SPECIES_DEOXYS_SPEED,
	SPECIES_DIALGA,
//	SPECIES_DIALGA_PRIMAL,
	SPECIES_PALKIA,
//	SPECIES_PALKIA_PRIMAL,
	SPECIES_GIRATINA,
	SPECIES_GIRATINA_ORIGIN,
	SPECIES_HEATRAN,
	SPECIES_REGIGIGAS,
	SPECIES_DARKRAI,
	SPECIES_SHAYMIN,
	SPECIES_SHAYMIN_SKY,
	SPECIES_ARCEUS,
	SPECIES_ARCEUS_FIGHT,
	SPECIES_ARCEUS_FLYING,
	SPECIES_ARCEUS_POISON,
	SPECIES_ARCEUS_GROUND,
	SPECIES_ARCEUS_ROCK,
	SPECIES_ARCEUS_BUG,
	SPECIES_ARCEUS_GHOST,
	SPECIES_ARCEUS_STEEL,
	SPECIES_ARCEUS_FIRE,
	SPECIES_ARCEUS_WATER,
	SPECIES_ARCEUS_GRASS,
	SPECIES_ARCEUS_ELECTRIC,
	SPECIES_ARCEUS_PSYCHIC,
	SPECIES_ARCEUS_ICE,
	SPECIES_ARCEUS_DRAGON,
	SPECIES_ARCEUS_DARK,
	SPECIES_ARCEUS_FAIRY,
	SPECIES_TORNADUS,
	SPECIES_TORNADUS_THERIAN,
	SPECIES_THUNDURUS,
	SPECIES_THUNDURUS_THERIAN,
	SPECIES_LANDORUS,
	SPECIES_LANDORUS_THERIAN,
	SPECIES_KYUREM,
	SPECIES_KYUREM_BLACK,
	SPECIES_KYUREM_WHITE,
	SPECIES_GENESECT,
	SPECIES_GENESECT_SHOCK,
	SPECIES_GENESECT_BURN,
	SPECIES_GENESECT_CHILL,
	SPECIES_GENESECT_DOUSE,
	SPECIES_DIANCIE,
	SPECIES_ZYGARDE,
	SPECIES_ZYGARDE_10,
	SPECIES_COSMOG,
	SPECIES_COSMOEM,
	SPECIES_SOLGALEO,
	SPECIES_LUNALA,
	SPECIES_NIHILEGO,
	SPECIES_BUZZWOLE,
	SPECIES_PHEROMOSA,
	SPECIES_XURKITREE,
	SPECIES_CELESTEELA,
	SPECIES_KARTANA,
	SPECIES_GUZZLORD,
	SPECIES_POIPOLE,
	SPECIES_NAGANADEL,
	SPECIES_STAKATAKA,
	SPECIES_BLACEPHALON,
	SPECIES_NECROZMA,
	SPECIES_NECROZMA_DUSK_MANE,
	SPECIES_NECROZMA_DAWN_WINGS,
	SPECIES_MELTAN,
	SPECIES_MELMETAL,
	SPECIES_ETERNATUS,
};
#endif

#ifdef FLAG_POKEMON_RANDOMIZER
const species_t gRandomizerSpeciesBanList[] =
{
	0xFC,
	0xFD,
	0xFE,
	0xFF,
	0x100,
	0x101,
	0x102,
	0x103,
	0x104,
	0x105,
	0x106,
	0x107,
	0x108,
	0x109,
	0x10A,
	0x10B,
	0x10C,
	0x10D,
	0x10E,
	0x10F,
	0x110,
	0x111,
	0x112,
	0x113,
	0x114,
	SPECIES_EGG,
	SPECIES_UNOWN_B,
	SPECIES_UNOWN_C,
	SPECIES_UNOWN_D,
	SPECIES_UNOWN_E,
	SPECIES_UNOWN_F,
	SPECIES_UNOWN_G,
	SPECIES_UNOWN_H,
	SPECIES_UNOWN_I,
	SPECIES_UNOWN_J,
	SPECIES_UNOWN_K,
	SPECIES_UNOWN_L,
	SPECIES_UNOWN_M,
	SPECIES_UNOWN_N,
	SPECIES_UNOWN_O,
	SPECIES_UNOWN_P,
	SPECIES_UNOWN_Q,
	SPECIES_UNOWN_R,
	SPECIES_UNOWN_S,
	SPECIES_UNOWN_T,
	SPECIES_UNOWN_U,
	SPECIES_UNOWN_V,
	SPECIES_UNOWN_W,
	SPECIES_UNOWN_X,
	SPECIES_UNOWN_Y,
	SPECIES_UNOWN_Z,
	SPECIES_UNOWN_EXCLAMATION,
	SPECIES_UNOWN_QUESTION,
	SPECIES_UNFEZANT_F,
	SPECIES_FRILLISH_F,
	SPECIES_JELLICENT_F,
	SPECIES_SHADOW_WARRIOR,
	SPECIES_ROTOM_HEAT,
	SPECIES_ROTOM_WASH,
	SPECIES_ROTOM_FROST,
	SPECIES_ROTOM_FAN,
	SPECIES_ROTOM_MOW,
	SPECIES_GIRATINA_ORIGIN,
	SPECIES_SHAYMIN_SKY,
	SPECIES_ARCEUS_FIGHT,
	SPECIES_ARCEUS_FLYING,
	SPECIES_ARCEUS_POISON,
	SPECIES_ARCEUS_GROUND,
	SPECIES_ARCEUS_ROCK,
	SPECIES_ARCEUS_BUG,
	SPECIES_ARCEUS_GHOST,
	SPECIES_ARCEUS_STEEL,
	SPECIES_ARCEUS_FIRE,
	SPECIES_ARCEUS_WATER,
	SPECIES_ARCEUS_GRASS,
	SPECIES_ARCEUS_ELECTRIC,
	SPECIES_ARCEUS_PSYCHIC,
	SPECIES_ARCEUS_ICE,
	SPECIES_ARCEUS_DRAGON,
	SPECIES_ARCEUS_DARK,
	SPECIES_DARMANITANZEN,
	SPECIES_HIPPOPOTAS_F,
	SPECIES_HIPPOWDON_F,
	SPECIES_MELOETTA_PIROUETTE,
	SPECIES_GENESECT_SHOCK,
	SPECIES_GENESECT_BURN,
	SPECIES_GENESECT_CHILL,
	SPECIES_GENESECT_DOUSE,
	SPECIES_CHERRIM_SUN,
	SPECIES_KYUREM_BLACK,
	SPECIES_KYUREM_WHITE,
	SPECIES_TORNADUS_THERIAN,
	SPECIES_THUNDURUS_THERIAN,
	SPECIES_LANDORUS_THERIAN,
	SPECIES_KELDEO_RESOLUTE,
	SPECIES_HOOPA_UNBOUND,
	SPECIES_PYROAR_FEMALE,
	SPECIES_MEOWSTIC_FEMALE,
	SPECIES_AEGISLASH_BLADE,
	SPECIES_ARCEUS_FAIRY,
	SPECIES_ZYGARDE_CELL,
	SPECIES_ZYGARDE_CORE,
	SPECIES_ZYGARDE_10,
	SPECIES_ZYGARDE_COMPLETE,
	SPECIES_ASHGRENINJA,
	SPECIES_FURFROU_HEART,
	SPECIES_FURFROU_DIAMOND,
	SPECIES_FURFROU_STAR,
	SPECIES_FURFROU_PHAROAH,
	SPECIES_FURFROU_KABUKI,
	SPECIES_FURFROU_LA_REINE,
	SPECIES_FURFROU_MATRON,
	SPECIES_FURFROU_DANDY,
	SPECIES_FURFROU_DEBUTANTE,
	SPECIES_VENUSAUR_MEGA,
	SPECIES_CHARIZARD_MEGA_X,
	SPECIES_CHARIZARD_MEGA_Y,
	SPECIES_BLASTOISE_MEGA,
	SPECIES_BEEDRILL_MEGA,
	SPECIES_PIDGEOT_MEGA,
	SPECIES_ALAKAZAM_MEGA,
	SPECIES_SLOWBRO_MEGA,
	SPECIES_GENGAR_MEGA,
	SPECIES_KANGASKHAN_MEGA,
	SPECIES_PINSIR_MEGA,
	SPECIES_GYARADOS_MEGA,
	SPECIES_AERODACTYL_MEGA,
	SPECIES_MEWTWO_MEGA_X,
	SPECIES_MEWTWO_MEGA_Y,
	SPECIES_AMPHAROS_MEGA,
	SPECIES_STEELIX_MEGA,
	SPECIES_SCIZOR_MEGA,
	SPECIES_HERACROSS_MEGA,
	SPECIES_HOUNDOOM_MEGA,
	SPECIES_TYRANITAR_MEGA,
	SPECIES_SCEPTILE_MEGA,
	SPECIES_BLAZIKEN_MEGA,
	SPECIES_SWAMPERT_MEGA,
	SPECIES_GARDEVOIR_MEGA,
	SPECIES_SABLEYE_MEGA,
	SPECIES_MAWILE_MEGA,
	SPECIES_AGGRON_MEGA,
	SPECIES_MEDICHAM_MEGA,
	SPECIES_MANECTRIC_MEGA,
	SPECIES_SHARPEDO_MEGA,
	SPECIES_CAMERUPT_MEGA,
	SPECIES_ALTARIA_MEGA,
	SPECIES_BANETTE_MEGA,
	SPECIES_ABSOL_MEGA,
	SPECIES_GLALIE_MEGA,
	SPECIES_SALAMENCE_MEGA,
	SPECIES_METAGROSS_MEGA,
	SPECIES_LATIAS_MEGA,
	SPECIES_LATIOS_MEGA,
	SPECIES_GROUDON_PRIMAL,
	SPECIES_KYOGRE_PRIMAL,
	SPECIES_RAYQUAZA_MEGA,
	SPECIES_LOPUNNY_MEGA,
	SPECIES_GARCHOMP_MEGA,
	SPECIES_LUCARIO_MEGA,
	SPECIES_ABOMASNOW_MEGA,
	SPECIES_GALLADE_MEGA,
	SPECIES_AUDINO_MEGA,
	SPECIES_DIANCIE_MEGA,
//	SPECIES_DIALGA_PRIMAL,
//	SPECIES_PALKIA_PRIMAL,
	SPECIES_DEOXYS_ATTACK,
	SPECIES_DEOXYS_DEFENSE,
	SPECIES_DEOXYS_SPEED,
	SPECIES_WISHIWASHI_S,
	SPECIES_SILVALLY_FIGHT,
	SPECIES_SILVALLY_FLYING,
	SPECIES_SILVALLY_POISON,
	SPECIES_SILVALLY_GROUND,
	SPECIES_SILVALLY_ROCK,
	SPECIES_SILVALLY_BUG,
	SPECIES_SILVALLY_GHOST,
	SPECIES_SILVALLY_STEEL,
	SPECIES_SILVALLY_FIRE,
	SPECIES_SILVALLY_WATER,
	SPECIES_SILVALLY_GRASS,
	SPECIES_SILVALLY_ELECTRIC,
	SPECIES_SILVALLY_PSYCHIC,
	SPECIES_SILVALLY_ICE,
	SPECIES_SILVALLY_DRAGON,
	SPECIES_SILVALLY_DARK,
	SPECIES_SILVALLY_FAIRY,
	SPECIES_MIMIKYU_BUSTED,
	SPECIES_MAGEARNA_P,
	SPECIES_NECROZMA_DUSK_MANE,
	SPECIES_NECROZMA_DAWN_WINGS,
	SPECIES_NECROZMA_ULTRA,
	SPECIES_PIKACHU_SURFING,
	SPECIES_PIKACHU_FLYING,
	SPECIES_PIKACHU_COSPLAY,
	SPECIES_PIKACHU_LIBRE,
	SPECIES_PIKACHU_POP_STAR,
	SPECIES_PIKACHU_ROCK_STAR,
	SPECIES_PIKACHU_BELLE,
	SPECIES_PIKACHU_PHD,
	SPECIES_PIKACHU_CAP_ORIGINAL,
	SPECIES_PIKACHU_CAP_HOENN,
	SPECIES_PIKACHU_CAP_SINNOH,
	SPECIES_PIKACHU_CAP_UNOVA,
	SPECIES_PIKACHU_CAP_KALOS,
	SPECIES_PIKACHU_CAP_ALOLA,
	SPECIES_PIKACHU_CAP_PARTNER,
	SPECIES_PICHU_SPIKY,
	SPECIES_XERNEAS_NATURAL,
	SPECIES_TABLES_TERMIN
};

#endif

#ifdef FLAG_ABILITY_RANDOMIZER

const ability_t gRandomizerAbilityBanList[] =
{
	ABILITY_TABLES_TERMIN
};

#endif
