#pragma once

enum trainer_classes {
	CLASS_BLANK_0, // 0
	
    CLASS_PKMN_TRAINER0, // 1
    CLASS_LORLEADER, // 2
    CLASS_TEAMAQUA, // 3
	
    CLASS_BLANK_1, // 4
    CLASS_BLANK_2, // 5
	
    CLASS_INTERVIEWER, // 6
	
    CLASS_BLANK_3, // 7
    CLASS_BLANK_4, // 8
    CLASS_BLANK_5, // 9
	
    CLASS_NURSE, // 0xA
    CLASS_BLANK_5half, // 0xB
	
    CLASS_BLANK_6, // 0xC
	
    CLASS_RICHBOY, // 0xD
    CLASS_TERRORGRANBULL, // 0xE
    CLASS_CAMPINGDUO, // 0xF
    CLASS_SKIIER, // 0x10
    CLASS_GUITARIST_R, // 0x11
    CLASS_KINDLER, // 0x12
    CLASS_SHOCKER, // 0x13
    CLASS_BUG_MANIAC, // 0x14
    CLASS_OFFICER, // 0x15
    CLASS_BLACKFERROTHORN, // 0x16
	
    CLASS_BLANK_7, // 0x17
	
    CLASS_SUCCESSOR, // 0x18
    CLASS_SCHOOLKID, // 0x19
    CLASS_SRANDJR, // 0x1A
    CLASS_POKEFAN, // 0x1B
    CLASS_EXPERT, // 0x1C
	
    CLASS_BLANK_8, // 0x1D
    CLASS_BLANK_9, // 0x1E
    CLASS_BLANK_10, // 0x1F
	
    CLASS_TRIATHLETE, // 0x20
    CLASS_DRAGONTAMER, // 0x21
	
    CLASS_BLANK_11, // 0x22
	
    CLASS_NINJABOY, // 0x23
    CLASS_BATTLEGIRL, // 0x24
    CLASS_PARASOLLADY, // 0x25
	
    CLASS_BLANK_12, // 0x26
    CLASS_BLANK_13, // 0x27
    CLASS_BLANK_14, // 0x28
    CLASS_BLANK_15, // 0x29
	
    CLASS_BOARDER, // 0x2A
    CLASS_COLLECTOR, // 0x2B
	
    CLASS_BLANK_16, // 0x2C
	
    CLASS_BLANK_17, // 0x2D
    CLASS_LORADMIN, // 0x2E
    CLASS_LIGHTOFRUIN, // 0x2F
    CLASS_SHADOWADMIN, // 0x30
	
    CLASS_BLANK_18, // 0x31
    CLASS_BLANK_19, // 0x32
    CLASS_BLANK_20, // 0x33	
    CLASS_BLANK_21, // 0x34
	
    CLASS_EXPERTDUO, // 0x35
	
    CLASS_BLANK_22, // 0x36
	
    CLASS_AQUAADMIN, // 0x37
    CLASS_MAGMAADMIN, // 0x38
    CLASS_YOUNGSTER, // 0x39
    CLASS_BUGCATCHER, // 0x3A
    CLASS_LASS, // 0x3B
    CLASS_SAILOR, // 0x3C
    CLASS_CAMPER, // 0x3D
    CLASS_PICNICKER, // 0x3E
    CLASS_POKEMANIAC, // 0x3F
    CLASS_SUPERNERD, // 0x40
    CLASS_HIKER, // 0x41
    CLASS_BIKER, // 0x42
	CLASS_BURGLAR, // 0x43
	CLASS_WORKER, // 0x44
	CLASS_FISHERMAN, // 0x45
	CLASS_SWIMMERM, // 0x46
	CLASS_ROUGHNECK, // 0x47
	CLASS_GAMBLER, // 0x48
	CLASS_BEAUTY, // 0x49
	CLASS_SWIMMERF, // 0x4A
	CLASS_PSYCHIC, // 0x4B
	CLASS_GUITARIST, // 0x4C
	CLASS_JUGGLER, // 0x4D
	CLASS_TAMER, // 0x4E
	CLASS_BIRDKEEPER, // 0x4F
	CLASS_BLACKBELT, // 0x50
	CLASS_RIVAL, // 0x51
	CLASS_SCIENTIST, // 0x52
	CLASS_BOSS, // 0x53
	CLASS_LEADER, // 0x54
	CLASS_SHADOW, // 0x55
	CLASS_ACETRAINER, // 0x56
	CLASS_ELITEFOUR, // 0x57
	CLASS_GENTLEMAN, // 0x58
	CLASS_BLANK_23, // 0x59
	CLASS_CHAMPION, // 0x5A
	CLASS_MEDIUM, // 0x5B
	CLASS_TWINS, // 0x5C
	CLASS_ACEDUO, // 0x5D
	CLASS_YOUNGCOUPLE, // 0x5E
	CLASS_CRUSHKIN, // 0x5F
	CLASS_SISANDBRO, // 0x60
	CLASS_PKMNPROF, // 0x61
	CLASS_PLAYER, // 0x62
	CLASS_CRUSHGIRL, // 0x63
	CLASS_TUBER, // 0x64
	CLASS_PKMNBREEDER, // 0x65
	CLASS_PKMNRANGER, // 0x66
	CLASS_AROMALADY, // 0x67
	CLASS_RUINMANIAC, // 0x68
	CLASS_LADY, // 0x69
	CLASS_PAINTER, // 0x6A
};

enum trainer_sprites {
	TRAINER_SPRITE_ARCHIE, // 0
    TRAINER_SPRITE_AQUA_GRUNT_M, // 1
    TRAINER_SPRITE_AQUA_GRUNT_F, // 2
    TRAINER_SPRITE_INTERVIEWER, // 3
    TRAINER_SPRITE_CAMERAMAN, // 4
    TRAINER_SPRITE_CAMERADUO, // 5
    TRAINER_SPRITE_RS_TUBER_F, // 6
    TRAINER_SPRITE_RS_TUBER_M, // 7
    TRAINER_SPRITE_RIVAL, // 8
    TRAINER_SPRITE_RS_COOLTRAINER_F, // 9
    TRAINER_SPRITE_HEXMANIAC, // 0xA
    TRAINER_SPRITE_RS_LADY, // 0xB
    TRAINER_SPRITE_RS_BEAUTY, // 0xC
    TRAINER_SPRITE_RICHBOY, // 0xD
    TRAINER_SPRITE_FIREBREATHER, // 0xE
    TRAINER_SPRITE_BIRDKEEPER_F, // 0xF
    TRAINER_SPRITE_CAMPINGDUO, // 0x10
    TRAINER_SPRITE_GUITARIST, // 0x11
    TRAINER_SPRITE_KINDLER, // 0x12
    TRAINER_SPRITE_BIGMO, // 0x13
    TRAINER_SPRITE_BUG_MANIAC, // 0x14
    TRAINER_SPRITE_RS_PSYCHIC_M, // 0x15
    TRAINER_SPRITE_RS_PSYCHIC_F, // 0x16
    TRAINER_SPRITE_RS_GENTLEMAN, // 0x17
    TRAINER_SPRITE_MEL, // 0x18
    TRAINER_SPRITE_MAXIMA, // 0x19
    TRAINER_SPRITE_RS_ROXANNE, // 0x1A
    TRAINER_SPRITE_RS_BRAWLY, // 0x1B
    TRAINER_SPRITE_RS_LIZAANDTATE, // 0x1C
    TRAINER_SPRITE_SCHOOLBOY, // 0x1D
    TRAINER_SPRITE_RS_SCHOOLGIRL, // 0x1E
    TRAINER_SPRITE_RS_SRANDJR, // 0x1F
    TRAINER_SPRITE_POKEFAN_M, // 0x20
    TRAINER_SPRITE_POKRFAN_F, // 0x21
    TRAINER_SPRITE_EXPERT_M, // 0x22
    TRAINER_SPRITE_EXPERT_F, // 0x23
    TRAINER_SPRITE_OFFICER, // 0x24
    TRAINER_SPRITE_RS_STEVEN, // 0x25
    TRAINER_SPRITE_AKLOVE, // 0x26
    TRAINER_SPRITE_CYCLIST_M, // 0x27
    TRAINER_SPRITE_CYCLIST_F, // 0x28
    TRAINER_SPRITE_JOGGER, // 0x29
    TRAINER_SPRITE_RS_TRIATHLETE_F, // 0x2A
    TRAINER_SPRITE_RS_TRIATHLETE_M, // 0x2B
    TRAINER_SPRITE_RS_TRIATHLETE_F_2, // 0x2C
    TRAINER_SPRITE_DRAGONTAMER, // 0x2D
    TRAINER_SPRITE_RS_BIRDKEEPER, // 0x2E
    TRAINER_SPRITE_NINJABOY, // 0x2F
    TRAINER_SPRITE_RS_CRUSHGIRL, // 0x30
    TRAINER_SPRITE_PARASOL_LADY, // 0x31
    TRAINER_SPRITE_RS_SWIMMER_F, // 0x32
    TRAINER_SPRITE_RS_PICNICKER, // 0x33	
    TRAINER_SPRITE_RS_TWINS, // 0x34
    TRAINER_SPRITE_SCIENTIST_F, // 0x35
    TRAINER_SPRITE_COLLECTOR, // 0x36
    TRAINER_SPRITE_RS_WALLY, // 0x37
    TRAINER_SPRITE_RS_BRENDAN, // 0x38
    TRAINER_SPRITE_RS_MAY, // 0x39
    TRAINER_SPRITE_BLANK, // 0x3A	
    TRAINER_SPRITE_RS_BREEDER_F, // 0x3B
    TRAINER_SPRITE_RS_RANGER_M, // 0x3C
    TRAINER_SPRITE_RS_RANGER_F, // 0x3D		
	TRAINER_SPRITE_RS_MAXIE, // 0x3E
	TRAINER_SPRITE_SKIIER_F, // 0x3F
	TRAINER_SPRITE_SKIIER_M, // 0x40
	TRAINER_SPRITE_RS_LASS, // 0x41
	TRAINER_SPRITE_RS_BUGCATCHER, // 0x42
	TRAINER_SPRITE_NURSE, // 0x43
	TRAINER_SPRITE_RS_YOUNGCOUPLE, // 0x44
	TRAINER_SPRITE_EXPERTDUO, // 0x45
	TRAINER_SPRITE_RS_SISANDBRO, // 0x46
	TRAINER_SPRITE_RS_MATT, // 0x47
	TRAINER_SPRITE_RS_SHELLY, // 0x48
	TRAINER_SPRITE_MARLON, // 0x49
	TRAINER_SPRITE_IVORY, // 0x4A
	TRAINER_SPRITE_LORGRUNT, // 0x4B
	TRAINER_SPRITE_RS_FLANNERY, // 0x4C
	TRAINER_SPRITE_RS_NORMAN, // 0x4D
	TRAINER_SPRITE_ALICE, // 0x4E
	TRAINER_SPRITE_RS_WALLACE, // 0x4F
	TRAINER_SPRITE_RS_GLACIA, // 0x50
	TRAINER_SPRITE_RS_DRAKE, // 0x51
	
	TRAINER_SPRITE_YOUNGSTER, // 0x52
    TRAINER_SPRITE_BUGCATCHER, // 0x53
    TRAINER_SPRITE_LASS, // 0x54
    TRAINER_SPRITE_SAILOR, // 0x55
    TRAINER_SPRITE_CAMPER, // 0x56
    TRAINER_SPRITE_PICNICKER, // 0x57
    TRAINER_SPRITE_POKEMANIAC, // 0x58
    TRAINER_SPRITE_SUPERNERD, // 0x59
    TRAINER_SPRITE_HIKER, // 0x5A
    TRAINER_SPRITE_BIKER, // 0x5B
	TRAINER_SPRITE_BURGLAR, // 0x5C
	TRAINER_SPRITE_WORKER, // 0x5D
	TRAINER_SPRITE_FISHERMAN, // 0x5E
	TRAINER_SPRITE_SWIMMERM, // 0x5F
	TRAINER_SPRITE_ROUGHNECK, // 0x60
	TRAINER_SPRITE_GAMBLER, // 0x61
	TRAINER_SPRITE_BEAUTY, // 0x62
	TRAINER_SPRITE_SWIMMERF, // 0x63
	TRAINER_SPRITE_PSYCHIC_M, // 0x64
	TRAINER_SPRITE_ROCKER, // 0x65
	TRAINER_SPRITE_JUGGLER, // 0x66
	TRAINER_SPRITE_TAMER, // 0x67
	TRAINER_SPRITE_BIRDKEEPER, // 0x68
	TRAINER_SPRITE_BLACKBELT, // 0x69
	TRAINER_SPRITE_GARY, // 0x6A
	TRAINER_SPRITE_SCIENTIST_M, // 0x6B
	TRAINER_SPRITE_GIOVANNI, // 0x6C
	TRAINER_SPRITE_SHADOWGRUNT_M, // 0x6D
	TRAINER_SPRITE_ACETRAINER_M, // 0x6E
	TRAINER_SPRITE_ACETRAINER_F, // 0x6F
	
	TRAINER_SPRITE_FR_LORLEI, // 0x70
	TRAINER_SPRITE_FR_BRUNO, // 0x71
	TRAINER_SPRITE_FR_AGATHA, // 0x72
	TRAINER_SPRITE_MIRSKLE, // 0x73
	TRAINER_SPRITE_ZEPH, // 0x74
	TRAINER_SPRITE_FR_MISTY, // 0x75
	TRAINER_SPRITE_GALAVAN, // 0x76
	TRAINER_SPRITE_FR_ERIKA, // 0x77
	TRAINER_SPRITE_VEGA, // 0x78
	TRAINER_SPRITE_FR_BLAINE, // 0x79
	TRAINER_SPRITE_FR_SABRINA, // 0x7A
	TRAINER_SPRITE_GENTLEMAN, // 0x7B
	TRAINER_SPRITE_GARY_2, // 0x7C
	TRAINER_SPRITE_GARY_3, // 0x7D
	TRAINER_SPRITE_MEDIUM, // 0x7E
	TRAINER_SPRITE_TWINS, // 0x7F
	TRAINER_SPRITE_ACEDUO, // 0x80
	TRAINER_SPRITE_YOUNGCOUPLE, // 0x81
	TRAINER_SPRITE_CRUSHKIN, // 0x82
	TRAINER_SPRITE_SISANDBRO, // 0x83
	TRAINER_SPRITE_PROFOAK, // 0x84
	TRAINER_SPRITE_BRENDAN_2, // 0x85
	TRAINER_SPRITE_MAY_2, // 0x86
	TRAINER_SPRITE_PLAYER_M, // 0x87
	TRAINER_SPRITE_PLAYER_F, // 0x88
	TRAINER_SPRITE_SHADOWGRUNT_F, // 0x89
	TRAINER_SPRITE_PSYCHIC_F, // 0x8A
	TRAINER_SPRITE_CRUSHGIRL, // 0x8B
	TRAINER_SPRITE_TUBER_F, // 0x8C
	TRAINER_SPRITE_PKMNBREEDER_F, // 0x8D
	TRAINER_SPRITE_PKMNRANGER_M, // 0x8E
	TRAINER_SPRITE_PKMNRANGER_F, // 0x8F
	TRAINER_SPRITE_AROMALADY, // 0x90
	TRAINER_SPRITE_RUINMANIAC, // 0x91
	TRAINER_SPRITE_SELPHY, // 0x92
	TRAINER_SPRITE_PAINTER, // 0x93
};

enum OW_sprites {
	OW_LITTLE_BOY = 16,
	OW_LITTLE_GIRL,
	OW_YOUNGSTER,
	OW_RANDOM_GUY,
	OW_BUG_CATCHER,
	OW_BABY_CARRIAGE,
	OW_LASS,
	OW_RANDOM_GIRL,
	OW_CRUSH_GIRL,
	OW_RANDOM_GUY_2,
	OW_GUITARIST,
	OW_FAT_GUY,
	OW_RANDOM_WOMAN,
	OW_BEAUTY,
	OW_MIDDLE_AGED_MAN,
	OW_MIDDLE_AGED_WOMAN,
	OW_OLD_MAN,
	OW_OLD_MAN_2,
	OW_OLD_MAN_SLEEPING,
	OW_OLD_WOMAN,
	OW_NINJA_BOY,
	OW_TUBER_F,
	OW_TUBER_M,
	OW_CAMPER,
	OW_PICNICKER,
	OW_ACE_TRAINER_M,
	OW_ACE_TRAINER_F,
	OW_SWIMMER_M,
	OW_SWIMMER_F,
	OW_SKIER_M,
	OW_SKIER_F,
	OW_POKEMANIAC,
	OW_AROMA_LADY,
	OW_SHADOW_GRUNT_M,
	OW_SHADOW_GRUNT_F,
	OW_SNOW_CAMPER,
	OW_ROUGHNECK,
	OW_KARATE_GUY,
	OW_SCIENTIST_MALE,
	OW_HIKER,
	OW_FISHERMAN,
	OW_MEDIUM,
	OW_CHEF,
	OW_POLICEMAN,
	OW_GENTLEMAN,
	OW_SAILOR,
	OW_SHIP_CAPTAIN,
	OW_NURSE_JOY,
	OW_MEDIC_FEMALE,
	
	OW_SCIENTIST_F = 73,
	
	OW_BIRD_KEEPER = 152,
	OW_BIKER,
	OW_EXPERT_F,
	OW_EXPERT_M,
	OW_KINDLER,
	OW_PAINTER,
	OW_POKE_MANIAC,
	OW_RANGER_F,
	OW_RANGER_M,
	OW_RUIN_MANIAC,
	OW_DRAGON_TAMER,
	OW_SCHOOL_BOY,
	OW_CUE_BALL,
	OW_MARLON,
	OW_IVORY,
	OW_WORKER,
	OW_BUG_MANIAC,
	OW_INTERVIEWER,
	OW_CAMERAMAN,
	OW_COLLECTOR,
	OW_PSYCHIC_M,
	OW_SNOW_GIRL,
	OW_PRIMAL_GROUDON,
	OW_YOUNG_MARLON,
	OW_YOUNG_IVORY,
	OW_AROS,
	OW_SCIENTIST_SHADOW_M,
	OW_SCIENTIST_SHADOW_F,
	OW_SHADOW_WARRIOR,
	OW_ABRA,
	OW_CHARMELEON,
	OW_FLOETTE_O,
	OW_FLOETTE_B,
	OW_FLOETTE_R,
	OW_GIRATINA_O,
	OW_KECLEON,
	OW_INVISIBLE_PLAYER,
	OW_SHOCKER,
	OW_BREEDER_M,
	OW_BREEDER_F,
	OW_GAMBLER,
	OW_IDOL,
	OW_JUGGLER,
	OW_JOGGER,
	OW_CYCLIST_M,
	OW_CYCLIST_F,
	OW_RANCHER_M,
	OW_RANCHER_F,
	OW_RICH_MAN,
	OW_RICH_WOMAN,
	OW_RICH_BOY,
	OW_RICH_GIRL,
	OW_KOOKY_OLD_MAN,
	OW_KOOKY_OLD_WOMAN,
	OW_WAITER,
	OW_WAITRESS,
	OW_SERVICE_MALE,
	OW_SERVICE_FEMALE,
	OW_MAID,
	OW_POKEFAN_M,
	OW_POKEKID,
	OW_SAGE,
	OW_ELDER,
	OW_SOCIALITE,
	OW_ATTENDANT_F,
	OW_PALMER,
	OW_BURGLAR,
	OW_CLOWN,
	OW_PARASOL_LADY,
	OW_TAMER,
	OW_VIDEO_GAME_KID,
	OW_MART_CLERK_F
};