#pragma once

#define TRAINER_SPRITE_POKE_KID 6
#define TRAINER_SPRITE_TUBER_M 7
#define TRAINER_SPRITE_RICHGIRL 11
#define TRAINER_SPRITE_RANCHER_M 21
#define TRAINER_SPRITE_RANCHER_F 22
#define TRAINER_SPRITE_JAX 46
#define TRAINER_SPRITE_PKMN_BREEDER_M 58
#define TRAINER_SPRITE_IDOL 59
#define TRAINER_SPRITE_WAITER 60
#define TRAINER_SPRITE_WAITRESS 61
#define TRAINER_SPRITE_CYNTHIA 62
#define TRAINER_SPRITE_SKELI 65
#define TRAINER_SPRITE_GOLCHE 66
#define TRAINER_SPRITE_GAIL 80
#define TRAINER_SPRITE_PALMER 81

#define OW_PSYCHIC_F 0
#define OW_GAIL 0

#define TRAINER_SPRITE_ARCHIE 0
#define TRAINER_SPRITE_AQUA_GRUNT_M 1
#define TRAINER_SPRITE_AQUA_GRUNT_F 2
#define TRAINER_SPRITE_INTERVIEWER 3
#define TRAINER_SPRITE_CAMERAMAN 4
#define TRAINER_SPRITE_CAMERADUO 5
#define TRAINER_SPRITE_RS_TUBER_F 6
#define TRAINER_SPRITE_RS_TUBER_M 7
#define TRAINER_SPRITE_RIVAL 8
#define TRAINER_SPRITE_RS_COOLTRAINER_F 9
#define TRAINER_SPRITE_HEXMANIAC 0xA
#define TRAINER_SPRITE_RS_LADY 0xB
#define TRAINER_SPRITE_RS_BEAUTY 0xC
#define TRAINER_SPRITE_RICHBOY 0xD
#define TRAINER_SPRITE_FIREBREATHER 0xE
#define TRAINER_SPRITE_BIRDKEEPER_F 0xF
#define TRAINER_SPRITE_CAMPINGDUO 0x10
#define TRAINER_SPRITE_GUITARIST 0x11
#define TRAINER_SPRITE_KINDLER 0x12
#define TRAINER_SPRITE_BIGMO 0x13
#define TRAINER_SPRITE_BUG_MANIAC 0x14
#define TRAINER_SPRITE_RS_PSYCHIC_M 0x15
#define TRAINER_SPRITE_RS_PSYCHIC_F 0x16
#define TRAINER_SPRITE_RS_GENTLEMAN 0x17
#define TRAINER_SPRITE_MEL 0x18
#define TRAINER_SPRITE_MAXIMA 0x19
#define TRAINER_SPRITE_RS_ROXANNE 0x1A
#define TRAINER_SPRITE_RS_BRAWLY 0x1B
#define TRAINER_SPRITE_RS_LIZAANDTATE 0x1C
#define TRAINER_SPRITE_SCHOOLBOY 0x1D
#define TRAINER_SPRITE_RS_SCHOOLGIRL 0x1E
#define TRAINER_SPRITE_RS_SRANDJR 0x1F
#define TRAINER_SPRITE_POKEFAN_M 0x20
#define TRAINER_SPRITE_POKRFAN_F 0x21
#define TRAINER_SPRITE_EXPERT_M 0x22
#define TRAINER_SPRITE_EXPERT_F 0x23
#define TRAINER_SPRITE_OFFICER 0x24
#define TRAINER_SPRITE_RS_STEVEN 0x25
#define TRAINER_SPRITE_AKLOVE 0x26
#define TRAINER_SPRITE_CYCLIST_M 0x27
#define TRAINER_SPRITE_CYCLIST_F 0x28
#define TRAINER_SPRITE_JOGGER 0x29
#define TRAINER_SPRITE_RS_TRIATHLETE_F 0x2A
#define TRAINER_SPRITE_RS_TRIATHLETE_M 0x2B
#define TRAINER_SPRITE_RS_TRIATHLETE_F_2 0x2C
#define TRAINER_SPRITE_DRAGON_TAMER 0x2D
#define TRAINER_SPRITE_RS_BIRDKEEPER 0x2E
#define TRAINER_SPRITE_NINJABOY 0x2F
#define TRAINER_SPRITE_RS_CRUSHGIRL 0x30
#define TRAINER_SPRITE_PARASOL_LADY 0x31
#define TRAINER_SPRITE_RS_SWIMMER_F 0x32
#define TRAINER_SPRITE_RS_PICNICKER 0x33
#define TRAINER_SPRITE_RS_TWINS 0x34
#define TRAINER_SPRITE_SCIENTIST_F 0x35
#define TRAINER_SPRITE_COLLECTOR 0x36
#define TRAINER_SPRITE_RS_WALLY 0x37
#define TRAINER_SPRITE_RS_BRENDAN 0x38
#define TRAINER_SPRITE_RS_MAY 0x39
#define TRAINER_SPRITE_BLANK 0x3A#define 
#define TRAINER_SPRITE_RS_BREEDER_F 0x3B
#define TRAINER_SPRITE_RS_RANGER_M 0x3C
#define TRAINER_SPRITE_RS_RANGER_F 0x3D
#define TRAINER_SPRITE_RS_MAXIE 0x3E
#define TRAINER_SPRITE_SKIIER_F 0x3F
#define TRAINER_SPRITE_SKIIER_M 0x40
#define TRAINER_SPRITE_RS_LASS 0x41
#define TRAINER_SPRITE_RS_BUGCATCHER 0x42
#define TRAINER_SPRITE_NURSE 0x43
#define TRAINER_SPRITE_RS_YOUNGCOUPLE 0x44
#define TRAINER_SPRITE_EXPERTDUO 0x45
#define TRAINER_SPRITE_RS_SISANDBRO 0x46
#define TRAINER_SPRITE_RS_MATT 0x47
#define TRAINER_SPRITE_RS_SHELLY 0x48
#define TRAINER_SPRITE_MARLON 0x49
#define TRAINER_SPRITE_IVORY 0x4A
#define TRAINER_SPRITE_LORGRUNT 0x4B
#define TRAINER_SPRITE_RS_FLANNERY 0x4C
#define TRAINER_SPRITE_RS_NORMAN 0x4D
#define TRAINER_SPRITE_ALICE 0x4E
#define TRAINER_SPRITE_RS_WALLACE 0x4F
#define TRAINER_SPRITE_RS_GLACIA 0x50
#define TRAINER_SPRITE_RS_DRAKE 0x51
#define TRAINER_SPRITE_YOUNGSTER 0x52
#define TRAINER_SPRITE_BUGCATCHER 0x53
#define TRAINER_SPRITE_LASS 0x54
#define TRAINER_SPRITE_SAILOR 0x55
#define TRAINER_SPRITE_CAMPER 0x56
#define TRAINER_SPRITE_PICNICKER 0x57
#define TRAINER_SPRITE_POKEMANIAC 0x58
#define TRAINER_SPRITE_SUPERNERD 0x59
#define TRAINER_SPRITE_HIKER 0x5A
#define TRAINER_SPRITE_BIKER 0x5B
#define TRAINER_SPRITE_BURGLAR 0x5C
#define TRAINER_SPRITE_WORKER 0x5D
#define TRAINER_SPRITE_FISHERMAN 0x5E
#define TRAINER_SPRITE_SWIMMERM 0x5F
#define TRAINER_SPRITE_ROUGHNECK 0x60
#define TRAINER_SPRITE_GAMBLER 0x61
#define TRAINER_SPRITE_BEAUTY 0x62
#define TRAINER_SPRITE_SWIMMERF 0x63
#define TRAINER_SPRITE_PSYCHIC_M 0x64
#define TRAINER_SPRITE_ROCKER 0x65
#define TRAINER_SPRITE_JUGGLER 0x66
#define TRAINER_SPRITE_TAMER 0x67
#define TRAINER_SPRITE_BIRDKEEPER 0x68
#define TRAINER_SPRITE_BLACKBELT 0x69
#define TRAINER_SPRITE_GARY 0x6A
#define TRAINER_SPRITE_SCIENTIST_M 0x6B
#define TRAINER_SPRITE_GIOVANNI 0x6C
#define TRAINER_SPRITE_SHADOWGRUNT_M 0x6D
#define TRAINER_SPRITE_ACETRAINER_M 0x6E
#define TRAINER_SPRITE_ACETRAINER_F 0x6F 
#define TRAINER_SPRITE_FR_LORLEI 0x70
#define TRAINER_SPRITE_FR_BRUNO 0x71
#define TRAINER_SPRITE_FR_AGATHA 0x72
#define TRAINER_SPRITE_MIRSKLE 0x73
#define TRAINER_SPRITE_ZEPH 0x74
#define TRAINER_SPRITE_FR_MISTY 0x75
#define TRAINER_SPRITE_GALAVAN 0x76
#define TRAINER_SPRITE_FR_ERIKA 0x77
#define TRAINER_SPRITE_VEGA 0x78
#define TRAINER_SPRITE_FR_BLAINE 0x79
#define TRAINER_SPRITE_FR_SABRINA 0x7A
#define TRAINER_SPRITE_GENTLEMAN 0x7B
#define TRAINER_SPRITE_GARY_2 0x7C
#define TRAINER_SPRITE_GARY_3 0x7D
#define TRAINER_SPRITE_MEDIUM 0x7E
#define TRAINER_SPRITE_TWINS 0x7F
#define TRAINER_SPRITE_ACEDUO 0x80
#define TRAINER_SPRITE_YOUNGCOUPLE 0x81
#define TRAINER_SPRITE_CRUSHKIN 0x82
#define TRAINER_SPRITE_SISANDBRO 0x83
#define TRAINER_SPRITE_PROFOAK 0x84
#define TRAINER_SPRITE_BRENDAN_2 0x85
#define TRAINER_SPRITE_MAY_2 0x86
#define TRAINER_SPRITE_PLAYER_M 0x87
#define TRAINER_SPRITE_PLAYER_F 0x88
#define TRAINER_SPRITE_SHADOWGRUNT_F 0x89
#define TRAINER_SPRITE_PSYCHIC_F 0x8A
#define TRAINER_SPRITE_CRUSHGIRL 0x8B
#define TRAINER_SPRITE_TUBER_F 0x8C
#define TRAINER_SPRITE_PKMN_BREEDER_F 0x8D
#define TRAINER_SPRITE_PKMNRANGER_M 0x8E
#define TRAINER_SPRITE_PKMNRANGER_F 0x8F
#define TRAINER_SPRITE_AROMALADY 0x90
#define TRAINER_SPRITE_RUINMANIAC 0x91
#define TRAINER_SPRITE_SELPHY 0x92
#define TRAINER_SPRITE_PAINTER 0x93

enum OW_sprites 
{
	OW_LITTLE_BOY = 16,
	OW_LITTLE_GIRL,
	OW_YOUNGSTER,
	OW_RANDOM_GUY,
	OW_BUG_CATCHER,
	OW_BABY_CARRIAGE,
	OW_LASS,
	OW_RANDOM_GIRL,
	OW_CRUSH_GIRL,
	OW_RANDOM_GUY_2,
	OW_GUITARIST,
	OW_FAT_GUY,
	OW_RANDOM_WOMAN,
	OW_BEAUTY,
	OW_MIDDLE_AGED_MAN,
	OW_MIDDLE_AGED_WOMAN,
	OW_OLD_MAN,
	OW_OLD_MAN_2,
	OW_OLD_MAN_SLEEPING,
	OW_OLD_WOMAN,
	OW_NINJA_BOY,
	OW_TUBER_F,
	OW_TUBER_M,
	OW_CAMPER,
	OW_PICNICKER,
	OW_ACE_TRAINER_M,
	OW_ACE_TRAINER_F,
	OW_SWIMMER_M,
	OW_SWIMMER_F,
	OW_SKIER_M,
	OW_SKIER_F,
	OW_POKEMANIAC,
	OW_AROMA_LADY,
	OW_SHADOW_GRUNT_M,
	OW_SHADOW_GRUNT_F,
	OW_SNOW_CAMPER,
	OW_SUPER_NERD,
	OW_ROUGHNECK,
	OW_KARATE_GUY,
	OW_SCIENTIST_MALE,
	OW_HIKER,
	OW_FISHERMAN,
	OW_MEDIUM,
	OW_CHEF,
	OW_POLICEMAN,
	OW_GENTLEMAN,
	OW_SAILOR,
	OW_SHIP_CAPTAIN,
	OW_NURSE_JOY,
	OW_MEDIC_FEMALE,
	
	OW_SCIENTIST_F = 70,
	
	OW_BIRD_KEEPER = 152,
	OW_BIKER,
	OW_EXPERT_F,
	OW_EXPERT_M,
	OW_KINDLER,
	OW_PAINTER,
	OW_POKE_MANIAC,
	OW_RANGER_F,
	OW_RANGER_M,
	OW_RUIN_MANIAC,
	OW_DRAGON_TAMER,
	OW_SCHOOL_BOY,
	OW_CUE_BALL,
	OW_MARLON,
	OW_IVORY,
	OW_WORKER,
	OW_BUG_MANIAC,
	OW_INTERVIEWER,
	OW_CAMERAMAN,
	OW_COLLECTOR,
	OW_PSYCHIC_M,
	OW_SNOW_GIRL,
	OW_PRIMAL_GROUDON,
	OW_YOUNG_MARLON,
	OW_YOUNG_IVORY,
	OW_AROS,
	OW_SCIENTIST_SHADOW_M,
	OW_SCIENTIST_SHADOW_F,
	OW_SHADOW_WARRIOR,
	OW_ABRA,
	OW_CHARMELEON,
	OW_FLOETTE_O,
	OW_FLOETTE_B,
	OW_FLOETTE_R,
	OW_GIRATINA_O,
	OW_KECLEON,
	OW_INVISIBLE_PLAYER,
	OW_SHOCKER,
	OW_BREEDER_M,
	OW_BREEDER_F,
	OW_GAMBLER,
	OW_IDOL,
	OW_JUGGLER,
	OW_JOGGER,
	OW_CYCLIST_M,
	OW_CYCLIST_F,
	OW_RANCHER_M,
	OW_RANCHER_F,
	OW_RICH_MAN,
	OW_RICH_WOMAN,
	OW_RICH_BOY,
	OW_RICH_GIRL,
	OW_KOOKY_OLD_MAN,
	OW_KOOKY_OLD_WOMAN,
	OW_WAITER,
	OW_WAITRESS,
	OW_SKELI,
	OW_GOLCHE,
	OW_MAID,
	OW_POKEFAN_M,
	OW_POKEKID,
	OW_SAGE,
	OW_ELDER,
	OW_SOCIALITE,
	OW_ATTENDANT_F,
	OW_PALMER,
	OW_BURGLAR,
	OW_CLOWN,
	OW_PARASOL_LADY,
	OW_TAMER,
	OW_VIDEO_GAME_KID,
	OW_MART_CLERK_F,
	OW_CYNTHIA,
};