#pragma once

#include "global.h"

void ResetPokedex(void);
void CopyMonCategoryText(u16 species, u8 *dst);
u16 GetPokedexHeightWeight(u16 dexNum, u8 data);
u16 GetNationalPokedexCount(u8);
u16 GetHoennPokedexCount(u8);
u8 CreateDexDisplayMonDataTask(u16 dexNum, u32 trainerId, u32 personality);

enum
{
    FLAG_GET_SEEN,
    FLAG_GET_CAUGHT,
    FLAG_SET_SEEN,
    FLAG_SET_CAUGHT
};

enum
{
	PKDX_GET_HEIGHT,
	PKDX_GET_WEIGHT
};

u16 pokedex_count(u8);
u16 sub_80C0844(u8);

enum PokedexSpecies {
PKDX_NIDORAN_F = 29,
PKDX_NIDORINA,
PKDX_NIDOQUEEN,
PKDX_NIDORAN_M,
PKDX_NIDORINO,
PKDX_NIDOKING,
PKDX_CLEFAIRY,
PKDX_CLEFABLE,
PKDX_VULPIX,
PKDX_NINETALES,
PKDX_JIGGLYPUFF,
PKDX_WIGGLYTUFF,

PKDX_CLEFFA = 173,
PKDX_IGGLYBUFF,

PKDX_SKITTY = 300,
PKDX_DELCATTY,

PKDX_ARCEUS = 493,

PKDX_MUNNA = 517,
PKDX_MUSHARNA,

PKDX_GENESECT = 649,

PKDX_SILVALLY = 773,

PKDX_NIHILEGO = 793,
PKDX_BUZZWOLE,
PKDX_PHEROMOSA,
PKDX_XURKITREE,
PKDX_CELESTEELA,
PKDX_KARTANA,
PKDX_GUZZLORD,
PKDX_NECROZMA,
PKDX_MAGEARNA,
PKDX_MARSHADOW,
PKDX_POIPOLE,
PKDX_NAGANADEL,
PKDX_STAKATAKA,
PKDX_BLACEPHALON,
PKDX_ZERAORA,
PKDX_MELTAN,
PKDX_MELMETAL
};
