#pragma once

#include "global.h"

enum
{
	CLASS_YOUNGSTER = 0x39, // 0x39
    CLASS_BUGCATCHER, // 0x3A
    CLASS_LASS, // 0x3B
    CLASS_SAILOR, // 0x3C
    CLASS_CAMPER, // 0x3D
    CLASS_PICNICKER, // 0x3E
    CLASS_POKEMANIAC, // 0x3F
    CLASS_SUPERNERD, // 0x40
    CLASS_HIKER, // 0x41
    CLASS_BIKER, // 0x42
	CLASS_BURGLAR, // 0x43
	CLASS_ENGINEER, // 0x44
	CLASS_FISHERMAN, // 0x45
	CLASS_SWIMMERM, // 0x46
	CLASS_CUEBALL, // 0x47
	CLASS_GAMBLER, // 0x48
	CLASS_BEAUTY, // 0x49
	CLASS_SWIMMERF, // 0x4A
	CLASS_PSYCHIC, // 0x4B
	CLASS_ROCKER, // 0x4C
	CLASS_JUGGLER, // 0x4D
	CLASS_TAMER, // 0x4E
	CLASS_BIRDKEEPER, // 0x4F
	CLASS_BLACKBELT, // 0x50
	CLASS_RIVAL, // 0x51
	CLASS_SCIENTIST, // 0x52
	CLASS_BOSS, // 0x53
	CLASS_LEADER, // 0x54
	CLASS_TEAMROCKET, // 0x55
	CLASS_COOLTRAINER, // 0x56
	CLASS_ELITE_4, // 0x57
	CLASS_GENTLEMAN, // 0x58
	CLASS_RIVAL_2, // 0x59
	CLASS_CHAMPION, // 0x5A
	CLASS_CHANNELER, // 0x5B
	CLASS_TWINS, // 0x5C
	CLASS_COOLCOUPLE, // 0x5D
	CLASS_YOUNGCOUPLE, // 0x5E
	CLASS_CRUSHKIN, // 0x5F
	CLASS_SISANDBRO, // 0x60
	CLASS_PKMNPROF, // 0x61
	CLASS_PLAYER, // 0x62
	CLASS_CRUSHGIRL, // 0x63
	CLASS_TUBER, // 0x64
	CLASS_PKMNBREEDER, // 0x65
	CLASS_PKMNRANGER, // 0x66
	CLASS_AROMALADY, // 0x67
	CLASS_RUINMANIAC, // 0x68
	CLASS_LADY, // 0x69
	CLASS_PAINTER, // 0x6A
};

#ifdef UNBOUND

#define CLASS_LOR_LEADER 		0x2
#define CLASS_TERROR_GRANBULL 	0xE
#define CLASS_BLACK_FERROTHORN 	0x16
#define CLASS_SUCCESSOR			0x18
#define CLASS_LOR_ADMIN 		0x2E
#define CLASS_LOR 				0x2F
#define CLASS_SHADOW_ADMIN 		0x30
#define CLASS_WORKER 			0x44
#define CLASS_ROUGHNECK 		0x47
#define CLASS_GUITARIST 		0x4C
#define CLASS_BOSS 				0x53
#define CLASS_SHADOW			0x55
#define CLASS_SHADOW 			0x55
#define CLASS_ACE_TRAINER 		0x56
#define CLASS_MEDIUM 			0x5B
#define CLASS_ACEDUO 			0x5D

#endif
