#pragma once

enum BattleBeginStates {
GetTurnOrder,
ThirdTypeRemoval,
SwitchInAbilities,
Intimidate,
AmuletCoin_WhiteHerb,
AirBalloon,
TotemPokemon,
StartTurnEnd,
};

enum SpeedWarResults {
FirstMon, 
SecondMon, 
SpeedTie
};

const struct SpecialZMoves SpecialZMoveTable[] = 
{
	{PKMN_RAICHU_A,					ITEM_ALORAICHUIUM_Z, 	MOVE_THUNDERBOLT, 		MOVE_STOKED_SPARKSURFER},
	{PKMN_DECIDUEYE,				ITEM_DECIDIUM_Z, 		MOVE_SPIRITSHACKLE,		MOVE_SINISTER_ARROW_RAID},
	{PKMN_EEVEE,					ITEM_EEVIUM_Z, 			MOVE_LASTRESORT,		MOVE_EXTREME_EVOBOOST},
	{PKMN_INCINEROAR,				ITEM_INCINIUM_Z, 		MOVE_DARKESTLARIAT,		MOVE_MALICIOUS_MOONSAULT},
	{PKMN_KOMMO_O,					ITEM_KOMMONIUM_Z,		MOVE_CLANGINGSCALES,	MOVE_CLANGOROUS_SOULBLAZE},
	{PKMN_LUNALA,					ITEM_LUNALIUM_Z,		MOVE_MOONGEISTBEAM,		MOVE_MENACING_MOONRAZE_MAELSTROM},
	{PKMN_NECROZMA_WINGS,			ITEM_LUNALIUM_Z,		MOVE_MOONGEISTBEAM,		MOVE_MENACING_MOONRAZE_MAELSTROM},
	{PKMN_LYCANROC,					ITEM_LYCANIUM_Z,		MOVE_STONEEDGE,			MOVE_SPLINTERED_STORMSHARDS},
	{PKMN_LYCANROC_N,				ITEM_LYCANIUM_Z,		MOVE_STONEEDGE,			MOVE_SPLINTERED_STORMSHARDS},
	{PKMN_LYCANROC_DUSK,			ITEM_LYCANIUM_Z,		MOVE_STONEEDGE,			MOVE_SPLINTERED_STORMSHARDS},
	{PKMN_MARSHADOW,				ITEM_MARSHADIUM_Z, 		MOVE_SPECTRALTHIEF,		MOVE_SOUL_STEALING_7_STAR_STRIKE},
	{PKMN_MEW,						ITEM_MEWNIUM_Z, 		MOVE_PSYCHIC,			MOVE_GENESIS_SUPERNOVA},
	{PKMN_MIMIKYU,					ITEM_MIMIKIUM_Z, 		MOVE_PLAYROUGH,			MOVE_LETS_SNUGGLE_FOREVER},
	{PKMN_MIMIKYU_BUSTED,			ITEM_MIMIKIUM_Z, 		MOVE_PLAYROUGH,			MOVE_LETS_SNUGGLE_FOREVER},
	{PKMN_PIKACHU,					ITEM_PIKANIUM_Z, 		MOVE_VOLTTACKLE,		MOVE_CATASTROPIKA},
	{PKMN_PIKACHU_CAP_ORIGINAL,		ITEM_PIKASHUNIUM_Z, 	MOVE_THUNDERBOLT,		MOVE_10000000_VOLT_THUNDERBOLT},
	{PKMN_PIKACHU_CAP_HOENN,		ITEM_PIKASHUNIUM_Z, 	MOVE_THUNDERBOLT,		MOVE_10000000_VOLT_THUNDERBOLT},
	{PKMN_PIKACHU_CAP_SINNOH,		ITEM_PIKASHUNIUM_Z, 	MOVE_THUNDERBOLT,		MOVE_10000000_VOLT_THUNDERBOLT},
	{PKMN_PIKACHU_CAP_UNOVA,		ITEM_PIKASHUNIUM_Z, 	MOVE_THUNDERBOLT,		MOVE_10000000_VOLT_THUNDERBOLT},
	{PKMN_PIKACHU_CAP_KALOS,		ITEM_PIKASHUNIUM_Z, 	MOVE_THUNDERBOLT,		MOVE_10000000_VOLT_THUNDERBOLT},
	{PKMN_PIKACHU_CAP_ALOLA,		ITEM_PIKASHUNIUM_Z, 	MOVE_THUNDERBOLT,		MOVE_10000000_VOLT_THUNDERBOLT},
	{PKMN_PIKACHU_CAP_PARTNER,		ITEM_PIKASHUNIUM_Z, 	MOVE_THUNDERBOLT,		MOVE_10000000_VOLT_THUNDERBOLT},
	{PKMN_PRIMARINA,				ITEM_PRIMARIUM_Z, 		MOVE_SPARKLINGARIA,		MOVE_OCEANIC_OPERETTA},
	{PKMN_SNORLAX,					ITEM_SNORLIUM_Z, 		MOVE_GIGAIMPACT,		MOVE_PULVERIZING_PANCAKE},
	{PKMN_SOLGALEO,					ITEM_SOLGANIUM_Z, 		MOVE_SUNSTEELSTRIKE,	MOVE_SEARING_SUNRAZE_SMASH},
	{PKMN_NECROZMA_MANE,			ITEM_SOLGANIUM_Z, 		MOVE_SUNSTEELSTRIKE,	MOVE_SEARING_SUNRAZE_SMASH},
	{PKMN_TAPU_KOKO,				ITEM_TAPUNIUM_Z, 		MOVE_NATURESMADNESS,	MOVE_GUARDIAN_OF_ALOLA},
	{PKMN_TAPU_BULU,				ITEM_TAPUNIUM_Z, 		MOVE_NATURESMADNESS,	MOVE_GUARDIAN_OF_ALOLA},
	{PKMN_TAPU_LELE,				ITEM_TAPUNIUM_Z, 		MOVE_NATURESMADNESS,	MOVE_GUARDIAN_OF_ALOLA},
	{PKMN_TAPU_FINI,				ITEM_TAPUNIUM_Z, 		MOVE_NATURESMADNESS,	MOVE_GUARDIAN_OF_ALOLA},
	{PKMN_NECROZMA_ULTRA,			ITEM_ULTRA_NECROZIUM_Z, 	MOVE_PHOTONGEYSER, 		MOVE_LIGHT_THAT_BURNS_THE_SKY},
	{0xFFFF,						0xFFFF, 				0xFFFF,					0xFFFF}
};