#pragma once

#include "defines.h"

#define BattleScript_SuccessBallThrow 	((u8*) 0x81D9A42)
#define BattleScript_TutorialThrow 		((u8*) 0x81D9A88)
#define BattleScript_ShakeBallThrow 	((u8*) 0x81D9A93)
#define BattleScript_TrainerBallBlock 	((u8*) 0x81D9AC1)
#define BattleScript_DodgedBall 		((u8*) 0x81D9AD1)

#define sBallCatchBonuses ((u8*) 0x8250892)

#define NUM_BALLS BALL_TYPE_DREAM_BALL

enum BallTypes {
BALL_TYPE_MASTER_BALL = 1,
BALL_TYPE_ULTRA_BALL,
BALL_TYPE_GREAT_BALL,
BALL_TYPE_POKE_BALL,
BALL_TYPE_SAFARI_BALL,
BALL_TYPE_NET_BALL,
BALL_TYPE_DIVE_BALL,
BALL_TYPE_NEST_BALL,
BALL_TYPE_REPEAT_BALL,
BALL_TYPE_TIMER_BALL,
BALL_TYPE_LUXURY_BALL,
BALL_TYPE_PREMIER_BALL,
BALL_TYPE_DUSK_BALL,
BALL_TYPE_HEAL_BALL,
BALL_TYPE_QUICK_BALL,
BALL_TYPE_CHERISH_BALL,
BALL_TYPE_PARK_BALL,
BALL_TYPE_FAST_BALL,
BALL_TYPE_LEVEL_BALL,
BALL_TYPE_LURE_BALL,
BALL_TYPE_HEAVY_BALL,
BALL_TYPE_LOVE_BALL,
BALL_TYPE_FRIEND_BALL,
BALL_TYPE_MOON_BALL,
BALL_TYPE_SPORT_BALL,
BALL_TYPE_BEAST_BALL,
BALL_TYPE_DREAM_BALL
};

struct BallIdItemIdRelation
{
	u16 itemId;
	u8 ballId;
};